/* Independent IRON ASSAULT engine. No tank defense, shared game state or character skills. */
(function(root){'use strict';const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);const CONFIG={easy:{fire:1.45,speed:.8,bullets:.8,extra:0,healthEvery:3},normal:{fire:1,speed:1,bullets:1,extra:3,healthEvery:5},hard:{fire:.74,speed:1.15,bullets:1.2,extra:7,healthEvery:7}};class Match{
constructor(options={}){this.options={mode:'solo',difficulty:'normal',ai:'normal',characters:['explorer','dora'],...options};this.settings=CONFIG[this.options.difficulty];this.map=JSON.parse(JSON.stringify(root.AssaultMap));this.phase='playing';this.paused=false;this.time=0;this.score=0;this.events=[];this.camera=3060;this.furthest=3480;this.players=[this.player(0,this.options.mode==='local'?360:400,3480)];if(this.options.mode==='local'||this.options.mode==='ai')this.players.push(this.player(1,440,3480));if(this.options.mode==='ai')this.players[1].ai=true;this.solids=this.map.solids;this.enemies=this.map.enemies.map(([type,x,y],id)=>this.enemy(type,x,y,id));this.shots=[];this.explosives=[];this.warnings=[];this.pickups=this.map.pickups.map((p,i)=>({...p,id:i,taken:false}));this.hostages=this.map.hostages.map((h,i)=>({...h,id:i,rescued:false}));this.rescued=0;this.kills=0;this.boss=null;this.nextId=1;for(let i=0;i<this.settings.extra;i++)this.enemies.push(this.enemy(i%2?'rifle':'infantry',i%2?610:185,2920-i*330,100+i));}
player(id,x,y){return {id,x,y,spawnX:x,spawnY:y,hp:5,lives:3,alive:true,invincible:2,shield:0,speedBoost:0,weapon:1,secondary:1,ammo:6,cooldown:0,secondaryCooldown:0,dirX:0,dirY:-1,character:this.options.characters[id]||'dora',ai:false};}
emit(type,x,y){this.events.push({type,x,y,time:this.time});}
blocked(x,y,r=16){const w=this.map.water;if(y+r>w.y&&y-r<w.y+w.h&&(x-r<w.bridge.x||x+r>w.bridge.x+w.bridge.w))return true;return this.solids.some(s=>s.hp>0&&x+r>s.x&&x-r<s.x+s.w&&y+r>s.y&&y-r<s.y+s.h);}
move(p,dt,input){let x=input.x||0,y=input.y||0,n=Math.hypot(x,y);if(n>1){x/=n;y/=n;}if(n>.12){p.dirX=x/(Math.hypot(x,y)||1);p.dirY=y/(Math.hypot(x,y)||1);}const speed=210*(p.speedBoost>0?1.35:1),nx=clamp(p.x+x*speed*dt,26,774),ny=clamp(p.y+y*speed*dt,120,Math.min(3540,this.furthest+650));if(!this.blocked(nx,p.y))p.x=nx;if(!this.blocked(p.x,ny))p.y=ny;this.furthest=Math.min(this.furthest,p.y);}
updateCamera(dt){const living=this.players.filter(p=>p.alive&&!p.ai),mean=living.reduce((s,p)=>s+p.y,0)/(living.length||1),target=clamp(mean-310,0,3060);this.camera+=(target-this.camera)*(1-Math.exp(-dt*8));}
enemy(type,x,y,id){const hp={infantry:2,rifle:3,rocket:4,nest:8,light:5,tank:12,armored:9,mortar:6,turret:8,mine:1,helicopter:8};return {id,type,x,y,homeX:x,homeY:y,hp:hp[type]||3,maxHp:hp[type]||3,r:['tank','armored','nest','turret'].includes(type)?23:type==='mine'?13:16,cooldown:1+(id%4)*.3,warning:0,angle:0,hit:0};}
visible(e){return e.y>this.camera+44&&e.y<this.camera+520;}
kill(e){this.kills++;this.score+=e.type==='mine'?25:e.type==='tank'?250:100;this.emit('explosion',e.x,e.y);if(this.kills%this.settings.healthEvery===0)this.pickups.push({x:e.x,y:e.y,type:'health',taken:false});else if(this.kills%4===0)this.pickups.push({x:e.x,y:e.y,type:'ammo',taken:false});}
updateEnemies(dt){for(const e of this.enemies){if(e.hp<=0||!this.visible(e))continue;if(['infantry','light','armored','helicopter'].includes(e.type)){const range=e.type==='helicopter'?110:e.type==='light'?75:35;const nx=e.homeX+Math.sin(this.time*(e.type==='light'?1.4:.65)*this.settings.speed+e.id)*range;if(e.type==='helicopter'||!this.blocked(nx,e.y,e.r))e.x=nx;}}}
damage(p,amount){if(!p.alive||p.invincible>0||p.shield>0)return;p.hp-=amount;p.invincible=.65;this.emit('hurt',p.x,p.y);if(p.hp<=0){p.lives--;this.emit('explosion',p.x,p.y);if(p.lives>0){p.x=p.spawnX;p.y=p.spawnY;p.hp=5;p.invincible=2;p.ammo=Math.max(3,p.ammo);}else p.alive=false;if(!this.players.some(p=>p.alive)||(this.options.mode==='ai'&&!this.players[0].alive))this.end('defeat');}}
end(phase){if(this.phase!=='playing')return;this.phase=phase;this.summary={score:this.score,kills:this.kills,rescued:this.rescued,total:this.hostages.length,time:Math.floor(this.time),allRescued:this.rescued===this.hostages.length};this.emit(phase,400,this.camera+250);}
fireEnemy(e,target){const angle=e.angle,heavy=['rocket','tank','armored'].includes(e.type),speed=(heavy?175:245)*this.settings.bullets;const count=e.type==='nest'?3:1;for(let i=0;i<count;i++){const a=angle+(i-(count-1)/2)*.14;this.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,team:'enemy',damage:heavy?2:1,r:heavy?6:4,life:4,heavy});}e.cooldown=(e.type==='nest'?1.2:2.2)*this.settings.fire;this.emit('enemyFire',e.x,e.y);}
enemyCombat(dt){for(const e of this.enemies){if(e.hp<=0||!this.visible(e))continue;const target=this.players.filter(p=>p.alive&&p.y>this.camera+30&&p.y<this.camera+540).sort((a,b)=>dist(a,e)-dist(b,e))[0];if(!target)continue;if(e.type==='mine'){if(dist(e,target)<29){e.hp=0;this.emit('explosion',e.x,e.y);this.damage(target,2);}continue;}e.cooldown-=dt;if(e.warning>0){e.warning-=dt;if(e.warning<=0){if(e.type==='mortar'){this.warnings.push({x:e.aimX,y:e.aimY,r:46,time:1.1,damage:2});e.cooldown=3.1*this.settings.fire;}else this.fireEnemy(e,target);}}else if(e.cooldown<=0&&dist(e,target)<470){e.warning=e.type==='rocket'||e.type==='tank'?.8:.55;e.angle=Math.atan2(target.y-e.y,target.x-e.x);e.aimX=target.x;e.aimY=target.y;}}
for(const w of this.warnings){w.time-=dt;if(w.time<=0){this.emit('explosion',w.x,w.y);for(const p of this.players)if(dist(p,w)<w.r)this.damage(p,w.damage);}}this.warnings=this.warnings.filter(w=>w.time>0);}
secondary(p){if(p.secondaryCooldown>0||p.ammo<=0)return;p.ammo--;p.secondaryCooldown=.7;const n=p.secondary>=4?3:1;for(let i=0;i<n;i++){const a=Math.atan2(p.dirY,p.dirX)+(i-(n-1)/2)*.25,missile=p.secondary>=3;this.explosives.push({x:p.x,y:p.y,vx:Math.cos(a)*(missile?430:250),vy:Math.sin(a)*(missile?430:250),time:missile?.9:.65,r:p.secondary===1?62:85,damage:p.secondary===1?5:8,owner:p.id,missile});}this.emit('launch',p.x,p.y);}
blast(b){this.emit('explosion',b.x,b.y);for(const e of this.enemies)if(e.hp>0&&dist(e,b)<b.r+e.r){e.hp-=b.damage;if(e.hp<=0)this.kill(e);}for(const s of this.solids)if(s.hp>0&&Math.hypot(s.x+s.w/2-b.x,s.y+s.h/2-b.y)<b.r+Math.max(s.w,s.h)/2){s.hp-=b.damage;if(s.hp<=0)this.emit('explosion',s.x+s.w/2,s.y+s.h/2);}if(this.boss&&this.boss.hp>0&&dist(this.boss,b)<b.r+55)this.damageBoss(b.damage*1.2);}
updateExplosives(dt){for(const b of this.explosives){b.x+=b.vx*dt;b.y+=b.vy*dt;b.time-=dt;if(this.enemies.some(e=>e.hp>0&&dist(e,b)<e.r+10)||this.solids.some(s=>s.hp>0&&b.x>s.x&&b.x<s.x+s.w&&b.y>s.y&&b.y<s.y+s.h))b.time=0;if(b.time<=0)this.blast(b);}this.explosives=this.explosives.filter(b=>b.time>0);}
nearHostage(p){return this.hostages.find(h=>!h.rescued&&dist(h,p)<62);}
rescue(p){const h=this.nearHostage(p);if(!h)return;h.rescued=true;this.rescued++;this.score+=500;p.hp=Math.min(5,p.hp+2);p.ammo=Math.min(20,p.ammo+2);if(this.rescued%3===0)p.lives=Math.min(5,p.lives+1);this.emit('rescue',h.x,h.y);}
collect(p){if(p.ai)return;for(const i of this.pickups){if(i.taken||dist(i,p)>30)continue;i.taken=true;if(i.type==='weapon'){p.weapon=Math.min(5,p.weapon+1);p.secondary=Math.min(4,p.secondary+1);}if(i.type==='health')p.hp=Math.min(5,p.hp+3);if(i.type==='ammo')p.ammo=Math.min(20,p.ammo+4);if(i.type==='armor')p.shield=8;if(i.type==='speed')p.speedBoost=8;if(i.type==='life')p.lives=Math.min(5,p.lives+1);this.score+=75;this.emit('pickup',i.x,i.y);}}
damageBoss(amount){const b=this.boss;if(!b||b.hp<=0)return;if(b.phaseShield>0)return;const old=b.hp;b.hp-=amount*(b.open>0?2:.5);b.hit=.12;const gate=old>60&&b.hp<=60?60:old>30&&b.hp<=30?30:null;if(gate!==null){b.hp=gate;b.phaseShield=.95;b.open=0;b.warning=1.05;this.emit('bossWarn',b.x,b.y);}if(b.hp<=0){b.hp=0;this.score+=2500+(this.rescued===this.hostages.length?3000:this.rescued*150);this.score+=this.players.filter(p=>p.alive).reduce((s,p)=>s+p.lives*200,0);this.emit('bossDown',b.x,b.y);this.end('victory');}}
updateBoss(dt){if(!this.boss&&this.furthest<520){this.boss={x:400,y:245,hp:90,maxHp:90,stage:1,cooldown:1.5,warning:0,pattern:0,open:0,hit:0};this.emit('bossArrival',400,220);}const b=this.boss;if(!b||b.hp<=0)return;b.stage=b.hp>60?1:b.hp>30?2:3;b.x=400+Math.sin(this.time*.55)*90;b.phaseShield=Math.max(0,(b.phaseShield||0)-dt);b.open=Math.max(0,b.open-dt);b.hit=Math.max(0,b.hit-dt);const target=this.players.filter(p=>p.alive).sort((a,c)=>dist(a,b)-dist(c,b))[0];if(!target||!this.visible(b))return;if(b.warning>0){b.warning-=dt;if(b.warning<=0){b.pattern++;b.open=1.4;const angle=b.angle;for(let i=0;i<3+b.stage*2;i++){const a=angle+(i-(2+b.stage*2)/2)*.18;this.shots.push({x:b.x,y:b.y+35,vx:Math.cos(a)*195*this.settings.bullets,vy:Math.sin(a)*195*this.settings.bullets,team:'enemy',damage:2,r:6,life:4,heavy:true});}if(b.stage>=2)for(const dx of [-80,80])this.warnings.push({x:clamp(target.x+dx,45,755),y:target.y,r:43,time:1.25,damage:2});b.cooldown=(3.1-b.stage*.4)*this.settings.fire;this.emit('enemyFire',b.x,b.y);}}else{b.cooldown-=dt;if(b.cooldown<=0){b.warning=1.0;b.angle=Math.atan2(target.y-b.y,target.x-b.x);this.emit('bossWarn',b.x,b.y);}}}
cohesion(){const living=this.players.filter(p=>p.alive);if(living.length<2)return;const [a,b]=living;if(Math.abs(a.y-b.y)>320){const lead=a.y<b.y?a:b,trail=lead===a?b:a;lead.y=trail.y-320;}if(Math.abs(a.x-b.x)>660){const left=a.x<b.x?a:b,right=left===a?b:a;right.x=left.x+660;}}
primary(p){if(p.cooldown>0)return;const level=p.weapon;p.cooldown=[0,.24,.14,.18,.18,.105][level];const count=level===3?2:level===4?3:level===5?5:1;for(let i=0;i<count;i++){const angle=Math.atan2(p.dirY,p.dirX)+(level>=4?(i-(count-1)/2)*.18:0),offset=level===3?(i?7:-7):0;this.shots.push({id:this.nextId++,x:p.x+p.dirX*22-p.dirY*offset,y:p.y+p.dirY*22+p.dirX*offset,vx:Math.cos(angle)*620,vy:Math.sin(angle)*620,team:'player',owner:p.id,damage:1,r:3,life:1.5});}this.emit('fire',p.x,p.y);}
updateShots(dt){for(const s of this.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.team==='enemy'){const p=this.players.find(p=>p.alive&&dist(p,s)<18+s.r);if(p){this.damage(p,s.damage);s.life=0;}}else if(s.team==='player'){if(this.boss&&this.boss.hp>0&&Math.abs(s.x-this.boss.x)<55&&Math.abs(s.y-this.boss.y)<42){this.damageBoss(s.damage);s.life=0;continue;}const hit=this.enemies.find(e=>e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+s.r);if(hit){hit.hp-=s.damage;s.life=0;if(hit.hp<=0)this.kill(hit);}else{const wall=this.solids.find(w=>w.hp>0&&s.x>w.x&&s.x<w.x+w.w&&s.y>w.y&&s.y<w.y+w.h);if(wall){wall.hp-=s.damage;s.life=0;if(wall.hp<=0)this.emit('explosion',wall.x+wall.w/2,wall.y+wall.h/2);}}}}
this.shots=this.shots.filter(s=>s.life>0&&s.x>-20&&s.x<820&&s.y>-30&&s.y<3650);}
step(dt,inputs=[]){if(this.phase!=='playing'||this.paused)return;this.time+=dt;for(const p of this.players){if(!p.alive)continue;p.invincible=Math.max(0,p.invincible-dt);p.shield=Math.max(0,p.shield-dt);p.speedBoost=Math.max(0,p.speedBoost-dt);p.cooldown=Math.max(0,p.cooldown-dt);p.secondaryCooldown=Math.max(0,p.secondaryCooldown-dt);const input=p.ai&&root.AssaultAI?root.AssaultAI.input(this,p,dt):(inputs[p.id]||{});for(const y of [2880,2240,1660,1060,560])if(p.y<y&&p.spawnY>y+40){p.spawnY=y+40;p.spawnX=400;}this.move(p,dt,input);if(p.ai&&input.aim){p.dirX=input.aim.x;p.dirY=input.aim.y;}if(input.fire)this.primary(p);if(input.secondary)this.secondary(p);if(input.action)this.rescue(p);this.collect(p);}
this.cohesion();this.updateCamera(dt);this.updateEnemies(dt);this.enemyCombat(dt);this.updateShots(dt);this.updateExplosives(dt);this.updateBoss(dt);}
snapshot(){return {phase:this.phase,time:this.time,camera:this.camera,score:this.score,players:this.players.map(p=>({...p})),rescued:this.rescued,total:this.hostages.length,kills:this.kills,boss:this.boss&&{hp:this.boss.hp,maxHp:this.boss.maxHp,phase:this.boss.stage}};}}
root.AssaultCore={Match,CONFIG,clamp,dist};if(typeof module!=='undefined')module.exports=root.AssaultCore;})(globalThis);