/* Fallible partner decisions only; never takes human pickups or spends every missile. */
(function(root){const LEVEL={easy:{reaction:.6,aim:.24,dodge:55},normal:{reaction:.32,aim:.13,dodge:75},hard:{reaction:.17,aim:.07,dodge:95}};function input(m,p,dt){const cfg=LEVEL[m.options.ai]||LEVEL.normal;p.brain??={wait:0,input:{},lastX:p.x,lastY:p.y,stuck:0,lastSecondary:-20};const b=p.brain;b.wait-=dt;const human=m.players[0];if(!human.alive)return{};if(Math.hypot(p.x-b.lastX,p.y-b.lastY)<1)b.stuck+=dt;else b.stuck=0;b.lastX=p.x;b.lastY=p.y;if(p.y<m.camera+65||p.y>m.camera+515||b.stuck>3&&Math.hypot(p.x-human.x,p.y-human.y)>150){for(const dx of [65,-65,95,-95])if(!m.blocked(human.x+dx,human.y+35)){p.x=Math.max(26,Math.min(774,human.x+dx));p.y=human.y+35;b.stuck=0;break;}}
if(b.wait>0)return b.input;b.wait=cfg.reaction;let tx=human.x+65,ty=human.y+45,x=tx-p.x,y=ty-p.y,move=Math.hypot(x,y);if(move<35){x=0;y=0;}else{x/=move;y/=move;}
for(const e of m.enemies)if(e.hp>0&&e.type==='mine'&&Math.hypot(p.x-e.x,p.y-e.y)<cfg.dodge){x+=Math.sign(p.x-e.x||1)*1.4;y+=Math.sign(p.y-e.y||1)*.7;}
for(const w of m.warnings)if(Math.hypot(p.x-w.x,p.y-w.y)<w.r+25){x+=Math.sign(p.x-w.x||1)*1.6;y+=.5;}
for(const s of m.shots)if(s.team==='enemy'&&Math.hypot(p.x-s.x,p.y-s.y)<cfg.dodge){x+=(s.vy>0?1:-1)*.7;}
if(m.blocked(p.x+x*24,p.y+y*24)){if(!m.blocked(p.x+30,p.y)){x=1;y=0;}else if(!m.blocked(p.x-30,p.y)){x=-1;y=0;}else{x=0;y=1;}}
const targets=m.enemies.filter(e=>e.hp>0&&e.type!=='mine'&&m.visible(e)&&Math.hypot(p.x-e.x,p.y-e.y)<390);if(m.boss&&m.boss.hp>0&&m.visible(m.boss))targets.push(m.boss);const target=targets.sort((a,c)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(c.x-p.x,c.y-p.y))[0];let fire=false,secondary=false;if(target){const angle=Math.atan2(target.y-p.y,target.x-p.x)+Math.sin(m.time*3+p.id)*cfg.aim;p.dirX=Math.cos(angle);p.dirY=Math.sin(angle);fire=true;if(target===m.boss&&m.boss.open>0&&p.ammo>2&&m.time-b.lastSecondary>12&&m.options.ai!=='easy'){secondary=true;b.lastSecondary=m.time;}}
b.input={x,y,fire,secondary,aim:target?{x:p.dirX,y:p.dirY}:null};return b.input;}
root.AssaultAI={input,LEVEL};if(typeof module!=='undefined')module.exports=root.AssaultAI;})(globalThis);