/* Canvas presentation and controls are private to Pixel Blocks. */
(()=>{'use strict';const C=PixelBlocksCore,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');const COLORS={I:'#69d5ea',J:'#688bee',L:'#efa15d',O:'#f1cf67',S:'#85c58c',T:'#b18ce0',Z:'#ee8496',G:'#7c8f9b'};let match=null,paused=false,last=performance.now(),audio=null,muted=false,saved=null,frames=0;const held=new Map(),smooth=[null,null],flashes=[0,0];for(let i=0;i<=10;i++)$('rows').add(new Option(i+' 行',i));
function note(){$('ai-field').hidden=$('mode').value!=='ai';}$('mode').onchange=note;note();
function tone(f=400,d=.06,type='square',gain=.025){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function wake(){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}catch{}}
function start(replay=false){wake();const opts=replay&&saved?{...saved,seed:Date.now()>>>0}:{mode:$('mode').value,difficulty:$('difficulty').value,ai:$('ai').value,rows:+$('rows').value,rule:'survival',seed:Date.now()>>>0};saved=opts;match=new C.Match(opts);paused=false;held.clear();smooth.fill(null);$('overlay').hidden=true;$('setup').hidden=true;$('message').hidden=true;$('status').textContent=`${opts.difficulty.toUpperCase()} / SURVIVAL`;tone(660,.12);}
$('setup').onsubmit=e=>{e.preventDefault();start();};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';wake();};
function message(tag,title,text){$('message-tag').textContent=tag;$('message-title').textContent=title;$('message-text').textContent=text;$('setup').hidden=true;$('message').hidden=false;$('overlay').hidden=false;}
function pause(){if(!match||match.phase==='finished')return;paused=!paused;held.clear();if(paused){message('TAKE A BREATHER','PAUSED','两块棋盘已同时暂停。准备好后继续。');$('resume').hidden=false;$('resume').focus();}else{$('overlay').hidden=true;$('message').hidden=true;}}
$('pause').onclick=pause;$('resume').onclick=()=>{if(paused)pause();};$('restart').onclick=()=>start(true);$('settings').onclick=()=>{match=null;paused=false;held.clear();$('overlay').hidden=false;$('setup').hidden=false;$('message').hidden=true;note();};$('fullscreen').onclick=()=>{const el=document.querySelector('.cabinet');if(document.fullscreenElement)document.exitFullscreen();else el.requestFullscreen?.();};
const keys={KeyA:[0,'left'],KeyD:[0,'right'],KeyS:[0,'soft'],KeyW:[0,'cw'],KeyQ:[0,'ccw'],Space:[0,'hard'],KeyE:[0,'hold'],ArrowLeft:[1,'left'],ArrowRight:[1,'right'],ArrowDown:[1,'soft'],ArrowUp:[1,'cw'],ShiftRight:[1,'ccw'],Enter:[1,'hard'],ControlRight:[1,'hold']};
function act(i,a){if(!match||paused||match.phase!=='playing'||(i===1&&match.ai))return;const ok=match.action(i,a);if(ok){if(a==='cw'||a==='ccw')tone(340,.035);else if(a==='hold')tone(480,.06);else if(a==='hard')tone(120,.06);}return ok;}
window.addEventListener('keydown',e=>{if(e.target.matches('select,input')||(!$('overlay').hidden&&e.target.matches('button')&&!['KeyP','Escape'].includes(e.code)))return;if(e.code==='KeyP'||e.code==='Escape'){if(match){e.preventDefault();if(!e.repeat)pause();}return;}const k=keys[e.code];if(!k||!match)return;e.preventDefault();if(e.repeat||held.has(e.code))return;act(...k);held.set(e.code,{i:k[0],a:k[1],time:0,next:k[1]==='soft'?.035:.16});});window.addEventListener('keyup',e=>{if(keys[e.code]&&match)e.preventDefault();held.delete(e.code);});window.addEventListener('blur',()=>{held.clear();if(match&&match.phase==='playing'&&!paused)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&match&&match.phase==='playing'&&!paused)pause();});
document.querySelectorAll('[data-action]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const a=b.dataset.action;act(0,a);held.set('touch-'+a,{i:0,a,time:0,next:a==='soft'?.035:.16});};const stop=()=>held.delete('touch-'+b.dataset.action);b.onpointerup=stop;b.onpointercancel=stop;b.onlostpointercapture=stop;});
function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(Math.round(x),Math.round(y),w,h);}function text(str,x,y,size=12,col='#c0d4dc',align='left'){ctx.fillStyle=col;ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillText(str,x,y);}
function tile(type,x,y,size=22,alpha=1){ctx.save();ctx.globalAlpha=alpha;const col=COLORS[type];rect(x+1,y+1,size-2,size-2,col);rect(x+2,y+2,size-4,3,'#ffffff55');rect(x+2,y+size-5,size-4,3,'#00000033');rect(x+size-5,y+5,3,size-9,'#00000020');ctx.restore();}
function preview(type,x,y,size=14){if(!type)return;for(const [xx,yy]of C.cells(type,0))tile(type,x+xx*size,y+yy*size,size);}
function clock(t){return Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');}
function drawBoard(b,i,dt){const left=i===0?110:650,top=142,size=22;rect(left-3,top-3,226,446,i===0?'#d9b663':'#7ac5cd');rect(left,top,220,440,'#0c1824');for(let y=0;y<20;y++)for(let x=0;x<10;x++){rect(left+x*size,top+y*size,1,size,'#1b2b38');rect(left+x*size,top+y*size,size,1,'#1b2b38');if(b.grid[y][x])tile(b.grid[y][x],left+x*size,top+y*size,size);}if(b.clearing.length){for(const y of b.clearing)rect(left,top+y*size,220,size,frames%8<4?'#e9f2cd':'#a3d8de');}
if(b.active&&b.alive){const p=b.active,g=C.landing(b.grid,p);ctx.save();ctx.beginPath();ctx.rect(left,top,220,440);ctx.clip();for(const [x,y]of C.cells(g.type,g.rot)){ctx.strokeStyle=COLORS[g.type];ctx.lineWidth=1;ctx.strokeRect(left+(g.x+x)*size+3,top+(g.y+y)*size+3,size-6,size-6);}let s=smooth[i];if(!s||s.id!==p.id)s=smooth[i]={id:p.id,x:p.x,y:p.y};const speed=1-Math.exp(-dt*35);s.x+=(p.x-s.x)*speed;s.y+=(p.y-s.y)*speed;if(Math.abs(p.y-s.y)>2)s.y=p.y;for(const [x,y]of C.cells(p.type,p.rot))tile(p.type,left+(s.x+x)*size,top+(s.y+y)*size,size);ctx.restore();}
const hx=i===0?30:558,nx=i===0?353:891;text('HOLD',hx,154,11,b.holdUsed?'#6a8593':'#9dcbd5');preview(b.hold,hx-3,170);text('NEXT',nx,154,11);b.bag.preview().forEach((p,j)=>preview(p,nx-4,173+j*66,13));text(i===0?'PLAYER ONE':match.ai?'AI / '+match.options.ai.toUpperCase():'PLAYER TWO',left,65,15,i===0?'#f6c65b':'#93dce4');text(String(b.score).padStart(6,'0'),left,99,26,'#eef1d7');text(`LEVEL ${b.level}  ·  LINES ${b.lines}`,left,122,11);text(b.alive?'KEEP YOUR STACK LOW':'TOPPED OUT',left+110,614,11,b.alive?'#7d9fac':'#ee8496','center');if(!b.alive){ctx.fillStyle='#121e2bba';ctx.fillRect(left,top,220,440);text('TOP OUT',left+110,top+220,25,'#eea2a5','center');}}
function draw(dt){ctx.imageSmoothingEnabled=false;rect(0,0,1000,660,'#112330');for(let x=0;x<1000;x+=40)rect(x,640,20,2,'#263d49');rect(498,58,4,559,'#2b424e');if(!match){text('俄罗斯方块',500,300,48,'#f5b947','center');return;}const rule=match.options.rule,label=rule==='lines'?`${match.options.target} LINES`:rule==='score'?clock(Math.max(0,match.options.duration-match.elapsed)):clock(match.elapsed);text(label,500,35,19,'#f6cf75','center');text(rule==='lines'?'RACE':rule==='score'?'TIME LEFT':'SURVIVAL',500,54,9,'#91aebb','center');drawBoard(match.boards[0],0,dt);drawBoard(match.boards[1],1,dt);if(rule==='lines'){for(let i=0;i<2;i++){const x=i===0?110:650;rect(x,627,220,4,'#263d49');rect(x,627,Math.min(220,220*match.boards[i].lines/match.options.target),4,i===0?'#f5b947':'#83d3e1');}}}
function end(){held.clear();const w=match.winner,tag=w===null?'DRAW':w===0?'PLAYER ONE WINS':match.ai?'AI WINS':'PLAYER TWO WINS';message('MATCH COMPLETE',tag,`1P ${match.boards[0].score} 分 / ${match.boards[0].lines} 行  ·  ${match.ai?'AI':'2P'} ${match.boards[1].score} 分 / ${match.boards[1].lines} 行  ·  用时 ${clock(match.elapsed)}`);$('resume').hidden=true;$('restart').focus();tone(w===0?784:220,.3,'triangle',.04);try{localStorage.setItem('pq-blocks-best',Math.max(+localStorage.getItem('pq-blocks-best')||0,match.boards[0].score));}catch{}}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;frames++;if(match&&!paused&&match.phase==='playing'){for(const h of held.values()){if(!['left','right','soft'].includes(h.a))continue;h.time+=dt;while(h.time>=h.next){act(h.i,h.a);h.next+=h.a==='soft'?.035:.045;}}match.step(dt);for(let i=0;i<2;i++){const events=match.boards[i].events.splice(0);for(const e of events){if(e.type==='clear'){flashes[i]=.18;tone(440+e.lines*110,.14,'triangle');}if(e.type==='topout')tone(100,.2,'sawtooth',.02);}}if(match.phase==='finished')end();}draw(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.PixelBlocks={get match(){return match;},get paused(){return paused;},start,pause,action:act};
})();
