/* Independent rankings adapter. Scores come from existing match state, never alter rules. */
(()=>{'use strict';const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}},clean=s=>String(s).normalize('NFKC').replace(/[^A-Za-z0-9一-鿿]/gu,'').slice(0,12),online=new NumberOnline();const loaded=store.get('pq-blocks-ranking',[]);let rows=(Array.isArray(loaded)?loaded:[]).filter(x=>x&&typeof x.nickname==='string'&&typeof x.group==='string'&&Number.isFinite(x.survival_ms)&&x.survival_ms>=0&&Number.isInteger(x.score)&&x.score>=0&&Number.isInteger(x.lines)&&x.lines>=0),run=null,limit=20,queryJob=0,preparing=false;
const names=document.createElement('div');names.className='bt-names';names.innerHTML='<label>1P 排行榜昵称<input id="bt-nick1" maxlength="12" required></label><label id="bt-name2">2P 排行榜昵称<input id="bt-nick2" maxlength="12" required></label>';
const setup=document.getElementById('setup');setup.querySelector('.fields').after(names);names.querySelector('#bt-nick1').value=store.get('pq-blocks-nick1','玩家'+Math.floor(1000+Math.random()*9000));names.querySelector('#bt-nick2').value=store.get('pq-blocks-nick2','玩家2'+Math.floor(1000+Math.random()*9000));const note=document.createElement('p');note.className='bt-note';note.textContent=online.enabled?'完成比赛后验证并提交在线排行。昵称不代表真实身份。':'排行榜尚未配置在线服务，当前只记录本机成绩。';names.after(note);
const toggleNames=()=>{names.querySelector('#bt-name2').hidden=document.getElementById('mode').value!=='local';names.querySelector('#bt-nick2').required=document.getElementById('mode').value==='local'};document.getElementById('mode').addEventListener('change',toggleNames);toggleNames();
const open=document.createElement('button');open.id='bt-open';open.textContent='排行榜';document.querySelector('.bar').append(open);const result=document.createElement('p');result.id='bt-results';document.getElementById('message-text').after(result);
const dialog=document.createElement('dialog');dialog.className='bt-dialog';dialog.innerHTML='<div class="bt-title"><h2>俄罗斯方块 · LEADERBOARD</h2><button id="bt-close" aria-label="关闭">×</button></div><div class="bt-filter"><label>对战方式<select id="bt-mode"><option value="ai">1P vs AI</option><option value="local">本地双人</option></select></label><label>游戏难度<select id="bt-difficulty"><option value="easy">轻松</option><option value="normal" selected>标准</option><option value="hard">挑战</option><option value="expert">极速</option></select></label><label id="bt-ai-label">AI 难度<select id="bt-ai"><option value="easy">简单</option><option value="normal" selected>普通</option><option value="hard">困难</option></select></label><label>初始障碍行<select id="bt-rows"></select></label></div><p id="bt-caption" class="bt-note"></p><div class="bt-scroll"><table><thead><tr><th>RANK</th><th>NICKNAME</th><th>SURVIVAL</th><th>SCORE</th><th>LINES</th><th>DATE</th></tr></thead><tbody id="bt-table"></tbody></table></div><p id="bt-error" class="bt-note"></p><button id="bt-more" hidden>显示 TOP 100</button><p class="bt-note">生存时间越长越靠前；同时间按得分、消行数排序，再按完成时间先后。每个昵称只显示当前设置下的最佳成绩；AI 不参与排名。</p>';
document.querySelector('main').append(dialog);const $=id=>dialog.querySelector('#'+id);for(let i=0;i<=10;i++)$('bt-rows').add(new Option(i+' 行',i));
const key=o=>[o.mode,o.difficulty,o.rows,o.mode==='ai'?o.ai:'none'].join('|'),cmp=(a,b)=>b.survival_ms-a.survival_ms||b.score-a.score||b.lines-a.lines||Date.parse(a.finished_at)-Date.parse(b.finished_at)||String(a.id).localeCompare(String(b.id));
function best(data,opts){const seen=new Set();return data.filter(x=>x.group===key(opts)).sort(cmp).filter(x=>{const k=x.nickname.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).map((x,i)=>({...x,rank:i+1}))}
function picks(){const values=[...names.querySelectorAll('input')].map(e=>{e.value=clean(e.value);if(e.value.length<2)throw Error('排行榜昵称需为 2～12 个中英文或数字');return e.value});store.set('pq-blocks-nick1',values[0]);store.set('pq-blocks-nick2',values[1]);return values}
function opts(){return {mode:$('bt-mode').value,difficulty:$('bt-difficulty').value,rows:+$('bt-rows').value,ai:$('bt-ai').value}}
async function list(){const id=++queryJob,o=opts();$('bt-ai-label').hidden=o.mode!=='ai';$('bt-caption').textContent=(online.enabled?'在线共享排行':'本机排行 · 仅当前浏览器')+' · 相同比赛设置独立排名';$('bt-table').replaceChildren();$('bt-error').textContent='加载中…';$('bt-more').hidden=true;try{const data=online.enabled?await online.rpc('bt_leaderboard',{p_mode:o.mode,p_difficulty:o.difficulty,p_rows:o.rows,p_ai:o.mode==='ai'?o.ai:'none'}):best(rows,o);if(id!==queryJob)return;for(const row of data.slice(0,limit)){const tr=document.createElement('tr');tr.classList.toggle('bt-current',(run?.names||[names.querySelector('#bt-nick1').value,names.querySelector('#bt-nick2').value]).some(n=>n.toLowerCase()===row.nickname.toLowerCase()));for(const value of [row.rank,row.nickname,NumberCore.time(row.survival_ms),row.score,row.lines,new Date(row.finished_at).toLocaleDateString()]){const td=document.createElement('td');td.textContent=value;tr.append(td)}$('bt-table').append(tr)}$('bt-error').textContent=data.length?'':'当前设置下还没有成绩。';$('bt-more').hidden=data.length<=limit}catch(e){$('bt-error').textContent='排行榜加载失败：'+e.message}}
function show(){const active=run?.opts||{mode:document.getElementById('mode').value,difficulty:document.getElementById('difficulty').value,rows:+document.getElementById('rows').value,ai:document.getElementById('ai').value};for(const [id,k]of [['bt-mode','mode'],['bt-difficulty','difficulty'],['bt-rows','rows'],['bt-ai','ai']])$(id).value=active[k];limit=20;if(window.PixelBlocks?.match?.phase==='playing'&&!PixelBlocks.paused)PixelBlocks.pause();if(!dialog.open)dialog.showModal();list()}
open.onclick=show;$('bt-close').onclick=()=>{queryJob++;dialog.close()};dialog.querySelectorAll('select').forEach(s=>s.onchange=()=>{limit=20;list()});$('bt-more').onclick=()=>{limit=100;list()};
window.addEventListener('keydown',e=>{if(dialog.open)e.stopImmediatePropagation()},true);
function begin(o,n){run={opts:{...o},names:n,log:[],session:null,done:false,overflow:false};result.textContent=''}
async function prepare(o){const n=picks();if(online.enabled){preparing=true;try{const s=await online.rpc('bt_create_session',{p_options:o,p_names:n});begin({...o,seed:s.seed},n);run.session=s.session_id;return {...o,seed:s.seed}}finally{preparing=false}}begin(o,n);return o}
function beginLocal(o){begin(o,picks())}
function record(event){if(!run||run.done||!run.session||run.overflow)return;if(run.log.length>=250000){run.overflow=true;run.log=[];return}run.log.push(event)}
async function finish(match){const current=run;if(!current||current.done)return;current.done=true;const count=match.ai?1:2;
if(!current.session){for(let i=0;i<count;i++){const b=match.boards[i];rows.push({id:crypto.randomUUID(),nickname:current.names[i],group:key(current.opts),survival_ms:Math.round(match.elapsed*1000),score:b.score,lines:b.lines,finished_at:new Date().toISOString()})}const groups=[...new Set(rows.map(r=>r.group))];rows=groups.flatMap(g=>{const seen=new Set();return rows.filter(r=>r.group===g).sort(cmp).filter(r=>{const k=r.nickname.toLowerCase();if(seen.has(k))return false;seen.add(k);return true})});store.set('pq-blocks-ranking',rows);result.textContent=current.names.slice(0,count).map(n=>{const r=best(rows,current.opts).find(x=>x.nickname.toLowerCase()===n.toLowerCase());return n+'：本机最佳第 '+r.rank+' 名'}).join(' · ');return}
result.textContent='正在回放验证并提交在线成绩…';try{if(current.overflow)throw Error('本局记录超过验证上限，未提交在线排行');await online.init();const {data,error}=await online.client.functions.invoke('blocks-submit',{body:{session_id:current.session,log:current.log}});if(error)throw error;if(data.error)throw Error(data.error);if(current===run)result.textContent='在线验证成功，成绩已记录；点击排行榜查看当前设置名次。'}catch(e){if(current===run)result.textContent='在线成绩未提交：'+e.message}}
window.BlocksRanking={enabled:online.enabled,prepare,beginLocal,record,finish,show,best,key,error:e=>{note.textContent=e.message},get preparing(){return preparing},get run(){return run}};
})();
