/* Bomber Battle: isolated grid simulation. Reads no other mode state. */
(function(root){'use strict';
const W=15,H=13,DIRS=[[0,-1],[1,0],[0,1],[-1,0]],idx=(x,y)=>y*W+x,inside=(x,y)=>x>=0&&y>=0&&x<W&&y<H;
const HEROES={explorer:{name:'MARIO',cn:'冒险家',color:'#ffb45d',skill:'烈焰炸弹',tip:'下一颗炸弹的火力 +2'},soldier:{name:'COMMANDO',cn:'魂斗罗',color:'#9eca89',skill:'遥控引爆',tip:'已有炸弹在 0.7 秒后引爆'},mystic:{name:'THREE-EYED KID',cn:'三目童子',color:'#b5a0f5',skill:'光箭炸弹',tip:'下一颗炸弹每条射线可穿透一块木箱'},dora:{name:'DORAEMON',cn:'哆啦A梦',color:'#77d8ef',skill:'空气护盾',tip:'7 秒内抵挡一次爆炸，合作时保护全队'},goku:{name:'SON GOKU',cn:'孙悟空',color:'#ffc35e',skill:'瞬间移动',tip:'移动到附近安全空格，避开危险'},nezha:{name:'NEZHA',cn:'哪吒',color:'#f5a1b7',skill:'风火轮',tip:'7 秒加速，前 2 秒不受爆炸伤害'}};
Object.assign(HEROES,{"astro":{"name":"ASTRO BOY","cn":"阿童木","color":"#83dce8","skill":"原子炸弹","tip":"下一颗炸弹火力 +2"},"happy":{"name":"HAPPY HERO","cn":"开心超人","color":"#f3b857","skill":"机甲护甲","tip":"护盾抵挡一次爆炸"},"wuwa":{"name":"WU WA","cn":"五娃","color":"#70d9ff","skill":"水浪炸弹","tip":"下一颗炸弹射线穿透一块木箱"}});
const THEMES=[{name:'SUNRISE GARDEN',cn:'晨曦庭院',floor:'#66875c',dark:'#58764f',stone:'#acb6a1',crate:'#ae7550',accent:'#e5c37c'},{name:'NEON FACTORY',cn:'霓虹工厂',floor:'#313b53',dark:'#293248',stone:'#698397',crate:'#aa6a64',accent:'#79d9df'},{name:'FROST PALACE',cn:'冰雪宫殿',floor:'#648b9c',dark:'#5b8094',stone:'#b9dfde',crate:'#7095b3',accent:'#d2eafa'}];
const DIFFICULTIES={easy:{name:'RELAXED',cn:'轻松',speed:3.1,think:.25,attack:1.25},medium:{name:'ARCADE',cn:'标准',speed:3.5,think:.14,attack:.65},hard:{name:'EXPERT',cn:'专家',speed:3.9,think:.065,attack:.28}};
class Match{
constructor(options={}){this.options={mode:'solo',p1:'explorer',p2:'dora',map:0,difficulty:'medium',rivals:true,...options};this.options.map=Math.max(0,Math.min(2,+this.options.map||0));if(!DIFFICULTIES[this.options.difficulty])this.options.difficulty='medium';this.seed=(options.seed??Date.now())>>>0;this.serial=0;this.events=[];this.paused=false;this.round=1;this.scores=[0,0,0,0];this.wins=[0,0,0,0];this.actors=[];const count=this.options.mode==='duel'&&!this.options.rivals?2:4,spawns=this.options.mode==='coop'?[[1,1],[13,1],[1,11],[13,11]]:[[1,1],[13,11],[13,1],[1,11]];const ids=Object.keys(HEROES);for(let n=0;n<count;n++){const human=n===0||(n===1&&this.options.mode!=='solo'),id=n===0?this.options.p1:n===1&&human?this.options.p2:ids[(ids.indexOf(this.options.p1)+n+1)%ids.length];this.actors.push({uid:++this.serial,side:n,human,id:HEROES[id]?id:'explorer',team:this.options.mode==='coop'?(n<2?0:1):n,spawn:spawns[n]});}this.startRound();}
random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
startRound(){this.grid=Array(W*H).fill('.');this.hidden={};this.bombs=[];this.flames=[];this.items=[];this.particles=[];this.phase='ready';this.delay=2;this.remaining=120;this.elapsed=0;this.closeRing=0;this.result=null;this.roundWinner=null;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const i=idx(x,y);if(!x||!y||x===W-1||y===H-1||(x%2===0&&y%2===0))this.grid[i]='S';else if(this.random()<.62)this.grid[i]='B';}const extra=this.options.map===1?[[4,5],[10,5],[4,7],[10,7]]:this.options.map===2?[[7,4],[7,8],[3,6],[11,6]]:[];for(const [x,y]of extra)this.grid[idx(x,y)]='S';for(const p of this.actors){const [x,y]=p.spawn;for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++)if(Math.abs(dx)+Math.abs(dy)<=3&&inside(x+dx,y+dy)&&this.grid[idx(x+dx,y+dy)]!=='S')this.grid[idx(x+dx,y+dy)]='.';Object.assign(p,{cx:x,cy:y,x:x+.5,y:y+.5,target:null,dir:2,alive:true,bombMax:1,range:2,speed:p.human?3.7:DIFFICULTIES[this.options.difficulty].speed,energy:100,inv:1.5,guard:0,guardTime:0,haste:0,nextPower:0,nextPierce:0,attackFlash:0,anim:0,think:0,attackWait:.4,roundKills:0,stun:0});}for(let i=0;i<this.grid.length;i++)if(this.grid[i]==='B'&&this.random()<.36)this.hidden[i]=['capacity','flame','speed','shield','energy'][Math.floor(this.random()*5)];this.events.push({type:'round',round:this.round});}
cell(p){return {x:Math.floor(p.x),y:Math.floor(p.y)};}
walkable(x,y,p,bombs=this.bombs){if(!inside(x,y)||this.grid[idx(x,y)]!=='.')return false;return !bombs.some(b=>b.x===x&&b.y===y&&!b.pass.includes(p.uid));}
blast(b,grid=this.grid){const cells=[idx(b.x,b.y)];for(const [dx,dy]of DIRS){let pierced=0;for(let n=1;n<=b.range;n++){const x=b.x+dx*n,y=b.y+dy*n;if(!inside(x,y))break;const i=idx(x,y),t=grid[i];if(t==='S')break;cells.push(i);if(t==='B'){if(pierced++<(b.pierce||0))continue;break;}}}return cells;}
forecast(extra){const danger=Array.from({length:W*H},()=>[]),grid=this.grid.slice(),bombs=this.bombs.map(b=>({...b,fuse:Math.max(0,b.fuse)}));if(extra)bombs.push({...extra});for(const f of this.flames)danger[f.i].push({start:0,end:f.life});let guard=0;while(bombs.length&&guard++<30){bombs.sort((a,b)=>a.fuse-b.fuse);const b=bombs.shift(),cells=this.blast(b,grid),time=b.fuse;for(const i of cells){danger[i].push({start:time,end:time+.66});if(grid[i]==='B')grid[i]='.';for(const other of bombs)if(idx(other.x,other.y)===i)other.fuse=Math.min(other.fuse,time);}}for(let r=this.closeRing+1;r<=5;r++){const time=95+(r-1)*5-this.elapsed;if(time>6)break;for(let y=r;y<H-r;y++)for(let x=r;x<W-r;x++)if(x===r||y===r||x===W-1-r||y===H-1-r)danger[idx(x,y)].push({start:Math.max(0,time),end:999});}return danger;}
safe(danger,i,start,end){return !danger[i].some(h=>h.start<end+.08&&h.end>start-.08);}
place(p){if(!p.alive||p.stun>0)return false;const {x,y}=this.cell(p);if(this.grid[idx(x,y)]!=='.'||this.bombs.some(b=>b.x===x&&b.y===y)||this.bombs.filter(b=>b.owner===p.uid).length>=p.bombMax)return false;const b={uid:++this.serial,owner:p.uid,team:p.team,x,y,range:Math.min(8,p.range+p.nextPower),pierce:p.nextPierce,fuse:2.4,age:0,pass:this.actors.filter(a=>Math.hypot(a.x-x-.5,a.y-y-.5)<.75).map(a=>a.uid),color:HEROES[p.id].color};p.nextPower=p.nextPierce=0;p.attackFlash=.25;this.bombs.push(b);this.events.push({type:'place',side:p.side,x,y});return true;}
explode(b){if(!this.bombs.includes(b))return;this.bombs.splice(this.bombs.indexOf(b),1);const cells=this.blast(b),owner=this.actors.find(p=>p.uid===b.owner);this.events.push({type:'explode',x:b.x,y:b.y});for(const i of cells){this.flames.push({i,owner:b.owner,team:b.team,life:.66,color:b.color});if(this.grid[i]==='B'){this.grid[i]='.';if(owner)this.scores[owner.side]+=10;this.spark(i,b.color,7);if(this.hidden[i]){this.items.push({i,type:this.hidden[i],delay:.7});delete this.hidden[i];}}else this.items=this.items.filter(it=>it.i!==i||it.delay>0);const chain=this.bombs.find(other=>idx(other.x,other.y)===i);if(chain)this.explode(chain);}this.spark(idx(b.x,b.y),'#ffc875',15);}
spark(i,color,count=10){for(let n=0;n<count;n++){const a=this.random()*Math.PI*2,s=1+this.random()*3;this.particles.push({x:i%W+.5,y:Math.floor(i/W)+.5,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+this.random()*.4,color});}}
kill(p,owner){if(!p.alive)return;p.alive=false;p.target=null;this.spark(idx(Math.floor(p.x),Math.floor(p.y)),HEROES[p.id].color,22);const killer=this.actors.find(a=>a.uid===owner);if(killer&&killer!==p&&killer.team!==p.team){this.scores[killer.side]+=200;killer.roundKills++;killer.energy=Math.min(100,killer.energy+30);}this.events.push({type:'out',side:p.side});}
applyFlames(){for(const p of this.actors){if(!p.alive||p.inv>0)continue;const {x,y}=this.cell(p),i=idx(x,y);const f=this.flames.find(f=>f.i===i&&(this.options.mode!=='coop'||f.owner===p.uid||f.team!==p.team));if(!f)continue;if(p.guard>0){p.guard--;p.inv=1;p.stun=.1;this.events.push({type:'shield',side:p.side});}else this.kill(p,f.owner);}}
skill(p){if(!p.alive||p.energy<100||p.stun>0)return false;let used=true;if(['explorer','astro'].includes(p.id))p.nextPower=2;else if(['mystic','wuwa'].includes(p.id))p.nextPierce=1;else if(p.id==='soldier'){const owned=this.bombs.filter(b=>b.owner===p.uid);if(!owned.length)used=false;for(const b of owned)b.fuse=Math.min(b.fuse,.7);}else if(['dora','happy'].includes(p.id)){for(const a of this.actors)if(a.alive&&(a===p||this.options.mode==='coop'&&a.team===p.team)){a.guard=1;a.guardTime=7;}}else if(p.id==='nezha'){p.haste=7;p.inv=Math.max(p.inv,2);}else if(p.id==='goku'){const danger=this.forecast(),start=idx(p.cx,p.cy),q=[{i:start,d:0}],seen=new Set([start]);let best=start,bestScore=-Infinity;for(let j=0;j<q.length;j++){const n=q[j],x=n.i%W,y=Math.floor(n.i/W);if(this.safe(danger,n.i,0,3)&&!this.bombs.some(b=>idx(b.x,b.y)===n.i)){const enemies=this.actors.filter(a=>a.alive&&a.team!==p.team),away=enemies.length?Math.min(...enemies.map(a=>Math.abs(a.cx-x)+Math.abs(a.cy-y))):4,score=n.d*2+Math.min(away,6);if(score>bestScore){bestScore=score;best=n.i;}}if(n.d>=3)continue;for(const [dx,dy]of DIRS){const nx=x+dx,ny=y+dy,i=idx(nx,ny);if(inside(nx,ny)&&!seen.has(i)&&this.walkable(nx,ny,p)){seen.add(i);q.push({i,d:n.d+1});}}}if(best===start)used=false;else{this.spark(start,'#ffe899',15);p.cx=best%W;p.cy=Math.floor(best/W);p.x=p.cx+.5;p.y=p.cy+.5;p.target=null;p.inv=Math.max(p.inv,.3);}}if(!used)return false;p.energy=0;p.attackFlash=.5;this.spark(idx(p.cx,p.cy),HEROES[p.id].color,15);this.events.push({type:'skill',side:p.side,name:HEROES[p.id].skill});return true;}
escape(p,danger,bombs=this.bombs,horizon=3.2){const start=idx(p.cx,p.cy),speed=p.speed*(p.haste>0?1.3:1),duration=1/speed,q=[{i:start,t:0,first:-1}],seen=new Set([start]);for(let j=0;j<q.length;j++){const n=q[j];if(n.first>=0&&this.safe(danger,n.i,n.t,horizon))return n.first;if(n.t>2.8)continue;const x=n.i%W,y=Math.floor(n.i/W);for(const d of [0,1,2,3]){const [dx,dy]=DIRS[d],nx=x+dx,ny=y+dy,i=idx(nx,ny),time=n.t+duration;if(!inside(nx,ny)||seen.has(i)||!this.walkable(nx,ny,p,bombs)||!this.safe(danger,n.i,n.t,time)||!this.safe(danger,i,n.t+duration*.4,time+.12))continue;seen.add(i);q.push({i,t:time,first:n.first<0?d:n.first});}}return -1;}
plan(p,danger){const start=idx(p.cx,p.cy),duration=1/p.speed,q=[{i:start,d:0,first:-1}],seen=new Set([start]),foes=this.actors.filter(a=>a.alive&&a.team!==p.team);let best=-1,bestScore=-Infinity;for(let j=0;j<q.length;j++){const n=q[j],x=n.i%W,y=Math.floor(n.i/W);let score=-n.d*3;const item=this.items.find(it=>it.i===n.i&&it.delay<=0);if(item)score+=65;const crates=DIRS.filter(([dx,dy])=>this.grid[idx(x+dx,y+dy)]==='B').length;score+=crates*10;for(const foe of foes){const distance=Math.abs(x-foe.cx)+Math.abs(y-foe.cy);score=Math.max(score,45-distance*5-n.d*2);}score+=this.random()*.8;if(n.first>=0&&score>bestScore){bestScore=score;best=n.first;}if(n.d>=14)continue;for(let d=0;d<4;d++){const [dx,dy]=DIRS[d],nx=x+dx,ny=y+dy,i=idx(nx,ny),time=(n.d+1)*duration;if(!inside(nx,ny)||seen.has(i)||!this.walkable(nx,ny,p)||!this.safe(danger,n.i,n.d*duration,time)||!this.safe(danger,i,time-duration*.5,time+.3))continue;seen.add(i);q.push({i,d:n.d+1,first:n.first<0?d:n.first});}}return best;}
ai(p,dt){p.think-=dt;p.attackWait=Math.max(0,p.attackWait-dt);if(p.target||p.think>0)return {};p.think=DIFFICULTIES[this.options.difficulty].think;const danger=this.forecast(),i=idx(p.cx,p.cy),threat=!this.safe(danger,i,0,2.8);if(threat){if(p.id==='goku'&&p.energy>=100&&this.skill(p))return {};if((['dora','happy','nezha'].includes(p.id))&&p.energy>=100)this.skill(p);return {dir:this.escape(p,danger)};}
const foes=this.actors.filter(a=>a.alive&&a.team!==p.team),crate=DIRS.some(([dx,dy])=>this.grid[idx(p.cx+dx,p.cy+dy)]==='B'),line=this.blast({x:p.cx,y:p.cy,range:p.range}).some(i=>foes.some(f=>idx(f.cx,f.cy)===i));if((crate||line)&&p.attackWait<=0&&this.bombs.filter(b=>b.owner===p.uid).length<p.bombMax&&!this.bombs.some(b=>idx(b.x,b.y)===i)){const extra={x:p.cx,y:p.cy,range:p.range+((['explorer','astro'].includes(p.id)&&p.energy>=100)?2:p.nextPower),pierce:['mystic','wuwa'].includes(p.id)&&p.energy>=100?1:p.nextPierce,fuse:2.4,pass:[p.uid]};const escape=this.escape(p,this.forecast(extra),[...this.bombs,extra]);if(escape>=0){if(['explorer','mystic','astro','wuwa'].includes(p.id)&&p.energy>=100)this.skill(p);this.place(p);p.attackWait=DIFFICULTIES[this.options.difficulty].attack;return {dir:escape};}}if(p.id==='soldier'&&p.energy>=100&&this.bombs.some(b=>b.owner===p.uid)&&this.bombs.filter(b=>b.owner===p.uid).every(b=>!this.blast(b).includes(i)))this.skill(p);return {dir:this.plan(p,danger)};}
move(p,dir,dt){if(!p.target&&dir>=0&&dir<4){p.dir=dir;const [dx,dy]=DIRS[dir],x=p.cx+dx,y=p.cy+dy;if(this.walkable(x,y,p))p.target={x,y,progress:0};}if(p.target&&!this.walkable(p.target.x,p.target.y,p)){p.target=null;p.x=p.cx+.5;p.y=p.cy+.5;}if(p.target){p.target.progress+=dt*p.speed*(p.haste>0?1.3:1);const t=Math.min(1,p.target.progress);p.x=p.cx+.5+(p.target.x-p.cx)*t;p.y=p.cy+.5+(p.target.y-p.cy)*t;p.anim+=dt*12;if(t>=1){p.cx=p.target.x;p.cy=p.target.y;p.target=null;p.x=p.cx+.5;p.y=p.cy+.5;}}}
pickup(p,item){if(item.type==='capacity')p.bombMax=Math.min(5,p.bombMax+1);else if(item.type==='flame')p.range=Math.min(6,p.range+1);else if(item.type==='speed')p.speed=Math.min(5,p.speed+.4);else if(item.type==='shield'){p.guard=1;p.guardTime=999;}else if(item.type==='energy')p.energy=Math.min(100,p.energy+45);this.scores[p.side]+=25;this.events.push({type:'pickup',side:p.side,name:item.type});this.items.splice(this.items.indexOf(item),1);}
close(){this.closeRing++;const r=this.closeRing;for(let y=r;y<H-r;y++)for(let x=r;x<W-r;x++)if(x===r||y===r||x===W-1-r||y===H-1-r){const i=idx(x,y);this.grid[i]='S';delete this.hidden[i];this.items=this.items.filter(it=>it.i!==i);this.bombs=this.bombs.filter(b=>idx(b.x,b.y)!==i);for(const p of this.actors)if(p.alive&&idx(this.cell(p).x,this.cell(p).y)===i)this.kill(p,null);this.spark(i,'#a9dfe3',4);}this.events.push({type:'close'});}
endRound(winner){this.roundWinner=winner;this.phase='roundover';this.delay=3;const winning=this.actors.filter(p=>p.team===winner);for(const p of winning)this.scores[p.side]+=500;if(winner!==null)this.wins[winner]++;this.events.push({type:'roundover',winner});}
finish(){const teams=[...new Set(this.actors.map(p=>p.team))],highest=Math.max(...teams.map(t=>this.wins[t])),leaders=teams.filter(t=>this.wins[t]===highest);this.result={winner:leaders.length===1?leaders[0]:null,wins:this.wins.slice(),scores:this.scores.slice(),rankings:this.actors.map(p=>({side:p.side,id:p.id,team:p.team,score:this.scores[p.side],wins:this.wins[p.team]})).sort((a,b)=>b.wins-a.wins||b.score-a.score)};this.phase='finished';this.events.push({type:'result',winner:this.result.winner});}
step(dt,inputs=[]){if(this.paused||this.phase==='finished')return;dt=Math.min(Math.max(dt,0),1/30);for(const f of this.particles){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;}this.particles=this.particles.filter(f=>f.life>0);if(this.phase==='ready'||this.phase==='roundover'){this.delay-=dt;if(this.delay<=0){if(this.phase==='ready')this.phase='playing';else if(this.round>=3||this.wins.some(w=>w>=2))this.finish();else{this.round++;this.startRound();}}return;}
this.elapsed+=dt;this.remaining=Math.max(0,120-this.elapsed);for(const f of this.flames)f.life-=dt;this.flames=this.flames.filter(f=>f.life>0);for(const b of this.bombs){b.fuse-=dt;b.age+=dt;b.pass=b.pass.filter(uid=>{const p=this.actors.find(p=>p.uid===uid);return p&&Math.floor(p.x)===b.x&&Math.floor(p.y)===b.y;});if(this.flames.some(f=>f.i===idx(b.x,b.y)))b.fuse=0;}for(const b of this.bombs.slice())if(b.fuse<=0)this.explode(b);this.applyFlames();for(const item of this.items)item.delay=Math.max(0,item.delay-dt);
for(const p of this.actors){if(!p.alive)continue;p.inv=Math.max(0,p.inv-dt);p.stun=Math.max(0,p.stun-dt);p.haste=Math.max(0,p.haste-dt);p.attackFlash=Math.max(0,p.attackFlash-dt);p.guardTime=Math.max(0,p.guardTime-dt);if(!p.guardTime)p.guard=0;p.energy=Math.min(100,p.energy+dt*6);const input=p.human?(inputs[p.side]||{}):this.ai(p,dt);if(p.stun<=0){if(input.skill)this.skill(p);if(input.bomb)this.place(p);this.move(p,input.dir??-1,dt);}const cell=this.cell(p),item=this.items.find(it=>it.delay<=0&&it.i===idx(cell.x,cell.y));if(item)this.pickup(p,item);}
this.applyFlames();for(const p of this.actors){const cell=this.cell(p);if(p.alive&&this.grid[idx(cell.x,cell.y)]==='S')this.kill(p,null);}const ring=Math.min(5,Math.floor((this.elapsed-90)/5));if(ring>this.closeRing)this.close();const teams=[...new Set(this.actors.filter(p=>p.alive).map(p=>p.team))];if(teams.length<=1)this.endRound(teams[0]??null);else if(this.remaining<=0)this.endRound(null);}
snapshot(){return {phase:this.phase,round:this.round,remaining:this.remaining,paused:this.paused,map:this.options.map,mode:this.options.mode,wins:this.wins.slice(),scores:this.scores.slice(),bombs:this.bombs.length,actors:this.actors.map(p=>({...p,target:p.target?{...p.target}:null})),result:this.result};}
}
const api={Match,HEROES,THEMES,DIFFICULTIES,W,H,DIRS,idx,inside};root.PixelBomberCore=api;if(typeof module==='object')module.exports=api;
})(typeof globalThis==='object'?globalThis:this);
