/* Shared original Pixel Quest character sprites. No game state. */
(function(root){'use strict';const data={
  "art": {
    "hero": [
      ".....RRRRR......",
      "....RRRRRRRR....",
      "....HHHSSHS.....",
      "...HSHSSSHSS....",
      "...HSHHSSSHSS...",
      "....HSSSSHHHH...",
      ".....SSSSSS.....",
      "....RRBRR.......",
      "...RRRBRRBRRR...",
      "..RRRRBBBBRRRR..",
      "..SSRBYYBBRSSS..",
      "..SSSBBBBBBSSS..",
      "....BBBBBBBB....",
      "....BBB..BBB....",
      "...HHH....HHH...",
      "..HHHH....HHHH.."
    ],
    "walk": [
      ".....RRRRR......",
      "....RRRRRRRR....",
      "....HHHSSHS.....",
      "...HSHSSSHSS....",
      "...HSHHSSSHSS...",
      "....HSSSSHHHH...",
      ".....SSSSSS.....",
      ".....RBRRR......",
      "...RRRBBRRRSS...",
      "..SSRRBYBBSSS...",
      "..SSSBBBBBB.....",
      "....BBBBBBBB....",
      "...BBBBBBBBB....",
      "..HHHBBB..BB....",
      "..HHHH....HHH...",
      "..........HHHH.."
    ],
    "jump": [
      ".....RRRRR..SS..",
      "....RRRRRRRRSSS.",
      "....HHHSSHS.RR..",
      "...HSHSSSHSSRR..",
      "...HSHHSSSHSS...",
      "....HSSSSHHHH...",
      ".....SSSSSS.....",
      "..RRRRBRRBRR....",
      ".SSRRRBBBBRR....",
      ".SSSRBYYBBRH....",
      "....BBBBBBHH....",
      "...BBBBBBBBH....",
      "..BBBBBBBB......",
      ".HHH..BBB.......",
      ".HHH...HHH......",
      "........HHHH...."
    ],
    "soldier": [
      "......YYYYYY............",
      ".....YDDYYYYY...........",
      ".....BBBBBBBB...........",
      "..BBB..SSSSKS...........",
      ".BB....STSSSS...........",
      ".......STSSS............",
      "......SSSS..............",
      "....SSWSSWSS............",
      "...SSSWWWWWSS...........",
      "...SSSWWWWWSS..KK.......",
      "....SSWGGGGGGGGGGGGGKK..",
      ".....SSSSSGGGGGGGGGGGGG.",
      "......WWWSSSSGGGSS......",
      "......HHHHH..GGG........",
      "......HGGHH..GG.........",
      "......BBBBB.............",
      ".....BBBBBBB............",
      ".....BBBGGBB............",
      "....BBBG.GBBB...........",
      "....BBB...BBB...........",
      "...BBB.....BBB..........",
      "...HHH.....HHH..........",
      "..HHHH.....HHHH.........",
      "..KKKK.....KKKK........."
    ],
    "soldierWalk": [
      "......YYYYYY............",
      ".....YDDYYYYY...........",
      ".....BBBBBBBB...........",
      "..BBB..SSSSKS...........",
      ".BB....STSSSS...........",
      ".......STSSS............",
      "......SSSS..............",
      "....SSWSSWSS............",
      "...SSSWWWWWSS...........",
      "...SSSWWWWWSS..KK.......",
      "....SSWGGGGGGGGGGGGGKK..",
      ".....SSSSSGGGGGGGGGGGGG.",
      "......WWWSSSSGGGSS......",
      "......HHHHH..GGG........",
      "......HGGHH..GG.........",
      "......BBBBB.............",
      ".....BBBBBBB............",
      ".....BBBBBBB............",
      "......BBB.BBB...........",
      ".......BB..BBB..........",
      "......BBB...BB..........",
      ".....HHH....HHH.........",
      "....HHHH.....HHH........",
      "....KKKK.....KKK........"
    ],
    "soldierJump": [
      "......YYYYYY............",
      ".....YDDYYYYY...........",
      ".....BBBBBBBB...........",
      "..BBB..SSSSKS...........",
      ".BB....STSSSS...........",
      ".......STSSS............",
      "......SSSS..............",
      "....SSWSSWSS............",
      "...SSSWWWWWSS...........",
      "...SSSWWWWWSS..KK.......",
      "....SSWGGGGGGGGGGGGGKK..",
      ".....SSSSSGGGGGGGGGGGGG.",
      "......WWWSSSSGGGSS......",
      "......HHHHH..GGG........",
      "......HGGHH..GG.........",
      "......BBBBB.............",
      ".....BBBBBBB............",
      ".....BBBBBBB............",
      "....BBBB.BBBB...........",
      "...BBB....BBBB..........",
      "..HHH......BBB..........",
      "..HHHH.....HHH..........",
      "..KKKK......HHH.........",
      "............KKK........."
    ],
    "mystic": [
      ".......TTTTT........",
      ".....TSSQQSST.......",
      "....TSSQQQSSST......",
      "....TSSSSWWWST......",
      "....SSSSSWKWSS......",
      "...TSSSSSWWWSS......",
      "...STSWKSSSWKS......",
      "....SSWKSSSWKS......",
      ".....SSSTSSSS.......",
      "......SSTTSS........",
      "......SSSS..........",
      "....BBWWWWBB........",
      "...BBBWBBWBBB.......",
      "..SSBBWWBBBBSS......",
      "..SSSBBBBBBSSSS.....",
      ".....HHHHHH.........",
      ".....BBHHBB.........",
      "....BBBBBBBB........",
      "...BBBB..BBBB.......",
      "...BBB....BBB.......",
      "...WWW....WWW.......",
      "..HHHH....HHHH......",
      "..HHHHH..HHHHHH.....",
      "..KKKKK..KKKKKK....."
    ],
    "mysticWalk": [
      ".......TTTTT........",
      ".....TSSQQSST.......",
      "....TSSQQQSSST......",
      "....TSSSSWWWST......",
      "....SSSSSWKWSS......",
      "...TSSSSSWWWSS......",
      "...STSWKSSSWKS......",
      "....SSWKSSSWKS......",
      ".....SSSTSSSS.......",
      "......SSTTSS........",
      "......SSSS..........",
      "....BBWWWWBB........",
      "...BBBWBBWBBB.......",
      "..SSBBWWBBBBSS......",
      "..SSSBBBBBBSSSS.....",
      ".....HHHHHH.........",
      ".....BBHHBB.........",
      "....BBBBBBBB........",
      "....BBBB.BBBB.......",
      ".....BBB..BBB.......",
      "....WWW...WWW.......",
      "...HHHH...HHHH......",
      "..HHHHH....HHHHH....",
      "..KKKKK....KKKKK...."
    ],
    "mysticJump": [
      ".......TTTTT........",
      ".....TSSQQSST.......",
      "....TSSQQQSSST......",
      "....TSSSSWWWST......",
      "....SSSSSWKWSS......",
      "...TSSSSSWWWSS......",
      "...STSWKSSSWKS......",
      "....SSWKSSSWKS......",
      ".....SSSTSSSS.......",
      "......SSTTSS........",
      "......SSSS..........",
      "....BBWWWWBB........",
      "...BBBWBBWBBB.......",
      "..SSBBWWBBBBSS......",
      "..SSSBBBBBBSSSS.....",
      ".....HHHHHH.........",
      ".....BBHHBB.........",
      "....BBBBBBBB........",
      "..BBBB....BBBB......",
      "..BBB......BBB......",
      ".WWW.......WWW......",
      ".HHHH......HHHH.....",
      ".HHHHH.....HHHHH....",
      ".KKKKK.....KKKKK...."
    ],
    "dora": [
      "........BBBBBBBB........",
      "......BBQQQQQQBBBB......",
      ".....BBQQQQQQQQBBBB.....",
      "....BBQQBWWWWWWBBBBB....",
      "...BBQQBWWWKWWKWWBBBB...",
      "...BQQBWWWWKWWKWWWBBB...",
      "..BBQBWWWWWWRRWWWWWBB...",
      "..BBQBWWWWWWRRWWWWWBB...",
      "..BBBWWKKWWWKWWWKKWBB...",
      "..BBBWWWWWWWKWWWWWWBB...",
      "...BBWWKKWWWKWWWKKWBB...",
      "...BBWWWWKKKKKKWWWWBB...",
      "....BBWWWWTTTTWWWWBB....",
      ".....BBWWWWWWWWWWBB.....",
      "......RRRRRYYRRRRR......",
      "....BBBBBWWYYWWBBBB.....",
      "...WWBBBBWWWWWWBBBBWW...",
      "...WWBBBWWWWWWWWBBBWW...",
      ".....BBBWWKKKKWWBBB.....",
      ".....BBBWWWKKWWWBBB.....",
      ".....BBBBWWWWWWBBBB.....",
      "......BBBBBBBBBBBB......",
      ".....WWWWW....WWWWW.....",
      "....WWWWWW....WWWWWW...."
    ],
    "doraWalk": [
      "........BBBBBBBB........",
      "......BBQQQQQQBBBB......",
      ".....BBQQQQQQQQBBBB.....",
      "....BBQQBWWWWWWBBBBB....",
      "...BBQQBWWWKWWKWWBBBB...",
      "...BQQBWWWWKWWKWWWBBB...",
      "..BBQBWWWWWWRRWWWWWBB...",
      "..BBQBWWWWWWRRWWWWWBB...",
      "..BBBWWKKWWWKWWWKKWBB...",
      "..BBBWWWWWWWKWWWWWWBB...",
      "...BBWWKKWWWKWWWKKWBB...",
      "...BBWWWWKKKKKKWWWWBB...",
      "....BBWWWWTTTTWWWWBB....",
      ".....BBWWWWWWWWWWBB.....",
      "......RRRRRYYRRRRR......",
      "....BBBBBWWYYWWBBBB.....",
      "...WWBBBBWWWWWWBBBBWW...",
      "...WWBBBWWWWWWWWBBBWW...",
      ".....BBBWWKKKKWWBBB.....",
      ".....BBBWWWKKWWWBBB.....",
      ".....BBBBWWWWWWBBBB.....",
      "......BBBBBBBBBBBB......",
      "......WWWW....WWWWW.....",
      ".....WWWWW.....WWWWW...."
    ],
    "goku": [
      "............AA..........",
      ".....AA....AAA..AAAA....",
      "......AAA.AAAAAAAAA.....",
      "....AAAAAAAAAAAAAA......",
      ".....AAAAQAAAAAAA.......",
      "......AAASSSASSAA.......",
      "......ASSSSSSSSSA.......",
      ".......SSWESEWSS........",
      ".......SSSSSSSSS........",
      "........SSTTSS..........",
      ".......RRBBRR...........",
      ".....SSRRBBRRSS.........",
      "....BSSRRRRRRSSB........",
      "...BSSRRRWKRRSSSB.......",
      "...SSSRRRWWRRSSSS.......",
      "HH....RRBBBBRR..........",
      ".HHH..RRBBBBRR..........",
      "...HH.RRRBBRRR..........",
      ".....RRRR..RRRR.........",
      ".....RRR....RRR.........",
      ".....BBB....BBB.........",
      "....BBBB....BBBB........",
      "...BBBBB....BBBBB.......",
      "...WWWWW....WWWWW......."
    ],
    "gokuWalk": [
      "............AA..........",
      ".....AA....AAA..AAAA....",
      "......AAA.AAAAAAAAA.....",
      "....AAAAAAAAAAAAAA......",
      ".....AAAAQAAAAAAA.......",
      "......AAASSSASSAA.......",
      "......ASSSSSSSSSA.......",
      ".......SSWESEWSS........",
      ".......SSSSSSSSS........",
      "........SSTTSS..........",
      ".......RRBBRR...........",
      ".....SSRRBBRRSS.........",
      "....BSSRRRRRRSSB........",
      "...BSSRRRWKRRSSSB.......",
      "...SSSRRRWWRRSSSS.......",
      "HH....RRBBBBRR..........",
      ".HHH..RRBBBBRR..........",
      "...HH.RRRBBRRR..........",
      ".....RRRR..RRRR.........",
      "......RRR..RRRR.........",
      ".......BB...BBB.........",
      "......BBB....BBBB.......",
      ".....BBBB.....BBBB......",
      ".....WWWW.....WWWW......"
    ],
    "gokuShoot": [
      "............AA..........",
      ".....AA....AAA..AAAA....",
      "......AAA.AAAAAAAAA.....",
      "....AAAAAAAAAAAAAA......",
      ".....AAAAQAAAAAAA.......",
      "......AAASSSASSAA.......",
      "......ASSSSSSSSSA.......",
      ".......SSWESEWSS........",
      ".......SSSSSSSSS........",
      "........SSTTSS..........",
      ".......RRBBRR...........",
      ".....SSRRBBRRSSSS.......",
      "....BSSRRRRRRRSSSS......",
      "....BSSRRWKRRBBSSSS.....",
      ".....SSRRWWRRBBSSSS.....",
      "HH....RRBBBBRR..........",
      ".HHH..RRBBBBRR..........",
      "...HH.RRRBBRRR..........",
      ".....RRRR..RRRR.........",
      ".....RRR....RRR.........",
      ".....BBB....BBB.........",
      "....BBBB....BBBB........",
      "...BBBBB....BBBBB.......",
      "...WWWWW....WWWWW......."
    ],
    "nezha": [
      "...AAA..........AAA...",
      "..AAAAA........AAAAA..",
      "..AAQAAA......AAAQAA..",
      "...AAAAAA....AAAAAA...",
      "....AAAAAAAAAAAAAA....",
      "...AAASSSSSSSSAAAA...",
      "...AASSSSRSSSSSAAA...",
      "..GASSSSSSSSSSSSAG...",
      "..GASWKSSSSWKSSSAG...",
      "...ASSSSSSSSSSSAA....",
      "....ASSSSTSSSSAA.....",
      ".....AASSSSSSAA......",
      "...PPPYYRRRRYYPPP....",
      "..PPSSYRRYYRRYSSPPP..",
      ".....YYRRYYRRYY..PPP.",
      "......RRRYYRRR....PP.",
      "......RRRRRRRR.......",
      ".....PPPRRRRPPP......",
      "......VVVVVVVV.......",
      ".....VVVV..VVVV......",
      ".....VVV....VVV......",
      ".....VVV....VVV......",
      "....SSSS....SSSS......",
      "....SSSS....SSSS......"
    ],
    "nezhaWalk": [
      "...AAA..........AAA...",
      "..AAAAA........AAAAA..",
      "..AAQAAA......AAAQAA..",
      "...AAAAAA....AAAAAA...",
      "....AAAAAAAAAAAAAA....",
      "...AAASSSSSSSSAAAA...",
      "...AASSSSRSSSSSAAA...",
      "..GASSSSSSSSSSSSAG...",
      "..GASWKSSSSWKSSSAG...",
      "...ASSSSSSSSSSSAA....",
      "....ASSSSTSSSSAA.....",
      ".....AASSSSSSAA......",
      "...PPPYYRRRRYYPPP....",
      "..PPSSYRRYYRRYSSPPP..",
      ".....YYRRYYRRYY..PPP.",
      "......RRRYYRRR....PP.",
      "......RRRRRRRR.......",
      ".....PPPRRRRPPP......",
      "......VVVVVVVV.......",
      "......VVVVVVVV.......",
      ".......VVV.VVVV.......",
      "......VVV...VVV.......",
      ".....SSSS....SSSS.....",
      "....SSSS......SSSS...."
    ]
  },
  "palette": {
    "R": "#e7533f",
    "H": "#603b31",
    "S": "#ffd49a",
    "B": "#27779c",
    "Y": "#ffdd62",
    "D": "#a55b37",
    "W": "#fff4d5",
    "K": "#293038",
    "T": "#eaa86b",
    "G": "#78b84a"
  },
  "colors": {
    "soldier": {
      "B": "#237bea",
      "Y": "#ffc15e",
      "D": "#b97735",
      "S": "#ffc394",
      "T": "#dd885c",
      "W": "#eeeede",
      "G": "#5b6977",
      "K": "#1b2735",
      "H": "#675045"
    },
    "mystic": {
      "Q": "#ffe1b1",
      "S": "#ffc18d",
      "T": "#df8655",
      "W": "#fff4e1",
      "K": "#253343",
      "B": "#2675de",
      "H": "#9b532b"
    },
    "dora": {
      "B": "#1389dc",
      "Q": "#3dbbff",
      "W": "#fff9e9",
      "K": "#263947",
      "R": "#f34c4a",
      "Y": "#ffcf45",
      "T": "#ee9164"
    },
    "goku": {
      "A": "#18202c",
      "Q": "#3b4550",
      "S": "#ffc28c",
      "T": "#df7850",
      "R": "#f78a28",
      "B": "#2269b4",
      "W": "#fff1d5",
      "K": "#232c38",
      "E": "#242a35",
      "H": "#94552c"
    },
    "nezha": {
      "A": "#182027",
      "Q": "#3b4149",
      "S": "#ffc18e",
      "T": "#dd8058",
      "K": "#27323c",
      "R": "#dc3d36",
      "Y": "#ffd066",
      "P": "#e887ab",
      "V": "#6159a1",
      "G": "#36c185",
      "W": "#fff8eb"
    }
  },
  "ids": [
    "explorer",
    "soldier",
    "mystic",
    "dora",
    "goku",
    "nezha"
  ],
  "names": {
    "explorer": "Pixel Explorer",
    "soldier": "Commando",
    "mystic": "Three-Eyed Kid",
    "dora": "Doraemon",
    "goku": "Son Goku",
    "nezha": "Nezha"
  }
};function freeze(o){Object.values(o).forEach(v=>{if(v&&typeof v==='object')freeze(v);});return Object.freeze(o);}root.PixelQuestCharacters=freeze(data);if(typeof module==='object')module.exports=root.PixelQuestCharacters;})(typeof globalThis==='object'?globalThis:this);
