const assert=require('node:assert/strict'),{chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route(/fonts\.(googleapis|gstatic)\.com/,r=>r.abort());let n=0;const pass=s=>{n++;console.log('PASS',s);};try{
await p.goto('http://localhost:4173/');assert.equal(await p.locator('.lobby-card').count(),8);await p.locator('[data-launch=play-blocks]').focus();await p.keyboard.press('Enter');await p.waitForURL('**/blocks.html');assert(await p.locator('#setup').isVisible());pass('the sixth menu card opens independent Blocks via keyboard');
assert.equal(await p.locator('#rule').count(),0);assert((await p.locator('#rule-note').textContent()).includes('最后')||(await p.locator('#rule-note').textContent()).includes('堆顶'));assert((await p.title()).includes('俄罗斯方块'));pass('Russian Blocks uses survival only');
await p.selectOption('#mode','local');assert(await p.locator('#ai-field').isHidden());await p.selectOption('#rows','5');await p.click('button[type=submit]');assert(await p.locator('#overlay').isHidden());assert(await p.evaluate(()=>JSON.stringify(PixelBlocks.match.boards[0].grid)===JSON.stringify(PixelBlocks.match.boards[1].grid)));pass('local two-player starts identical fields');
await p.evaluate(()=>{for(const b of PixelBlocks.match.boards)b.gravity=0;});const x0=await p.evaluate(()=>PixelBlocks.match.boards[0].active.x);await p.keyboard.press('a');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[0].active.x),x0-1);const x1=await p.evaluate(()=>PixelBlocks.match.boards[1].active.x);await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[1].active.x),x1+1);pass('both players have independent movement');
await p.keyboard.press('w');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[0].active.rot),1);await p.keyboard.press('q');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[0].active.rot),0);await p.keyboard.press('ArrowUp');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[1].active.rot),1);await p.keyboard.press('ShiftRight');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[1].active.rot),0);pass('clockwise and counterclockwise bindings for both players');
const dropScores=await p.evaluate(()=>PixelBlocks.match.boards.map(b=>b.score));await p.keyboard.press('s');await p.keyboard.press('ArrowDown');assert(await p.evaluate(scores=>PixelBlocks.match.boards.every((b,i)=>b.score>scores[i]),dropScores));pass('both soft-drop keys score on their own fields');await p.keyboard.press('e');assert(await p.evaluate(()=>!!PixelBlocks.match.boards[0].hold));await p.keyboard.press('ControlRight');assert(await p.evaluate(()=>!!PixelBlocks.match.boards[1].hold));const ids=await p.evaluate(()=>PixelBlocks.match.boards.map(b=>b.serial));await p.keyboard.press('Space');await p.keyboard.press('Enter');assert(await p.evaluate(ids=>PixelBlocks.match.boards.every((b,i)=>b.serial>ids[i]),ids));pass('hold and hard drop bindings for both players');
const before=await p.evaluate(()=>PixelBlocks.match.boards[0].serial);await p.keyboard.down('Space');await p.waitForTimeout(350);await p.keyboard.up('Space');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[0].serial),before+1);pass('holding hard-drop does not drop repeated pieces');
await p.keyboard.down('a');await p.waitForTimeout(350);await p.keyboard.up('a');assert(await p.evaluate(()=>PixelBlocks.match.boards[0].active.x<=1));pass('DAS and auto-repeat provide held movement');
await p.keyboard.press('p');assert(await p.evaluate(()=>PixelBlocks.paused));const time=await p.evaluate(()=>PixelBlocks.match.elapsed);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>PixelBlocks.match.elapsed),time);await p.locator('#resume').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>PixelBlocks.paused),false);pass('pause freezes both fields and timer; keyboard resumes');
await p.evaluate(()=>{PixelBlocks.match.boards[0].lines=100;PixelBlocks.match.boards[0].score=99999;});await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>PixelBlocks.match.phase),'playing');await p.evaluate(()=>{PixelBlocks.match.boards[1].alive=false;});await p.waitForFunction(()=>PixelBlocks.match.phase==='finished');assert.equal(await p.locator('#message-title').textContent(),'PLAYER ONE WINS');assert(await p.locator('#resume').isHidden());pass('survival ignores score and line totals, awards last survivor');
await p.click('#restart');assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[0].lines),0);await p.keyboard.press('p');pass('rematch resets all progress');
await p.click('#settings');await p.selectOption('#mode','ai');await p.selectOption('#ai','hard');await p.selectOption('#rows','0');await p.click('button[type=submit]');await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>PixelBlocks.match.boards[1].serial),1);await p.waitForFunction(()=>PixelBlocks.match.boards[1].serial>=4);assert(await p.evaluate(()=>PixelBlocks.match.boards[1].score>0));const save=await p.evaluate(()=>localStorage.getItem('pq-save'));await p.screenshot({path:'preview-blocks-match.png',fullPage:true});pass('Hard AI visibly plays through several pieces');
for(const width of [390,760,1440]){await p.setViewportSize({width,height:1100});await p.keyboard.press('p');await p.click('#settings');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await p.locator('button[type=submit]').isVisible());await p.click('button[type=submit]');assert(await p.locator('#overlay').isHidden());if(width===390){await p.locator('[data-action=left]').click();await p.locator('[data-action=hard]').click();await p.screenshot({path:'preview-blocks-mobile.png',fullPage:true});}assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}pass('phone tablet desktop layouts and touch input fit');
assert.equal(await p.evaluate(()=>localStorage.getItem('pq-save')),save);await p.click('.back');await p.waitForURL('http://localhost:4173/');assert(await p.locator('#arcade-lobby').isVisible());pass('home navigation and adventure save remain intact');assert.deepEqual(errors,[]);pass('no browser runtime errors');console.log(n+' Pixel Blocks browser checks passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
