/* Standalone combat simulation. Shares no adventure, kart or badminton state. */
(function(root){'use strict';
const HEROES={explorer:{name:'Pixel Explorer',special:'Fireball',ultimate:'Star Rush',color:'#ffb64b'},soldier:{name:'Commando',special:'Spread Shot',ultimate:'Thunder Barrage',color:'#79caff'},mystic:{name:'Three-Eyed Kid',special:'Returning Arrow',ultimate:'Third Eye Burst',color:'#ba9cff'},dora:{name:'Doraemon',special:'Air Cannon',ultimate:'Super Air Cannon',color:'#71e0ec'},goku:{name:'Son Goku',special:'Kamehameha',ultimate:'Super Saiyan Wave',color:'#ffc451'},nezha:{name:'Nezha',special:'Qiankun Ring',ultimate:'Red Sash Storm',color:'#ff789e'}};
Object.assign(HEROES,{"astro":{"name":"Astro Boy","special":"Energy Ball","ultimate":"Atomic Cannon","color":"#83dce8"},"happy":{"name":"Happy Hero","special":"Iron Fist","ultimate":"Flame Impact","color":"#f3b857"},"wuwa":{"name":"Wu Wa","special":"Water Jet","ultimate":"Tidal Wave","color":"#70d9ff"}});
const {COMBOS}=typeof module==='object'?require('./fighting-combos.js'):root.PixelFightingCombos;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
class Match{
 constructor(options={}){this.options={mode:'ai',difficulty:'medium',p1:'goku',p2:'nezha',...options};for(const k of ['p1','p2'])if(!HEROES[this.options[k]])this.options[k]=k==='p1'?'goku':'nezha';this.wins=[0,0];this.round=1;this.events=[];this.paused=false;this.winner=null;this.newRound();}
 newRound(){this.players=[this.fighter(0,this.options.p1),this.fighter(1,this.options.p2)];this.projectiles=[];this.attackSerial=0;this.time=60;this.phase='ready';this.delay=1.5;this.aiThink=0;this.aiInput={};this.events.push({type:'round',round:this.round});}
 fighter(side,id){return {side,id,x:side?710:250,y:440,vx:0,vy:0,facing:side?-1:1,ground:true,hp:100,energy:35,stun:0,blockStun:false,dodgeFlash:0,invincible:0,receivedHits:0,receivedWindow:0,lastReceivedAttack:null,action:null,guard:false,combo:0,comboWindow:0,hitCount:0,chain:0,chainTimer:0,flash:0,animation:0,roll:0,rollDirection:1,rollCooldown:0,history:[],historyTime:0,queued:null,moveLabel:null,labelTime:0};}
 attack(p,kind){if(this.phase!=='fight'||p.stun>0||p.action||p.guard||p.roll>0)return false;const history=p.historyTime>0?[...p.history,kind]:[kind],move=COMBOS[p.id].find(m=>history.slice(-m.sequence.length).join(',')===m.sequence.join(','));const cost=move?move.cost:kind==='special'?25:kind==='ultimate'?100:0;if(p.energy<cost){this.events.push({type:'empty',side:p.side,cost});return false;}p.energy-=cost;let combo=0;if(kind==='light'){combo=p.comboWindow>0?p.combo%3:0;p.combo=combo+1;p.comboWindow=.65;}else p.combo=0;
 const spec={light:[.13,.32,combo===2?5:2.5,combo===2?86:69],heavy:[.25,.57,8,92],special:[.22,.65,11,0],ultimate:[.48,1.15,28,0]}[kind];if(!spec)return false;const style=STYLES[p.id]?.[kind]||{};p.action={...style,id:++this.attackSerial,kind,t:0,start:move?.start??spec[0],duration:move?.range ? .75 : spec[1],damage:move?.damage??spec[2],range:move?.range??style.range??spec[3],combo,hit:false,move,direction:p.facing};p.history=move?[]:history.slice(-2);p.historyTime=1.15;if(move){p.moveLabel=move.name;p.labelTime=1.2;this.events.push({type:'combo',side:p.side,name:move.name});}this.events.push({type:'swing',side:p.side,kind});return true;} hit(attacker,target,damage,force=1,attack={}){if(target.hp<=0)return "ignored";if(target.invincible>0)return "immune";if(attack.dodgeable&&target.roll>.08&&target.roll<=.30){if(target.dodgeFlash<=0)this.events.push({type:"dodge",side:target.side});target.dodgeFlash=.18;return "dodged";}const front=(attacker.x-target.x)*target.facing>0,guardCost=attack.guardCost??(attack.ultimate?18:attack.combo?10:8),blocked=target.guard&&target.ground&&front&&target.energy>=guardCost;if(blocked){target.energy-=guardCost;target.hp=Math.max(0,target.hp-damage*.30);target.stun=.08;target.blockStun=true;target.vx=-target.facing*65;this.events.push({type:'block',side:target.side});}else{const broken=target.guard&&front;target.hp=Math.max(0,target.hp-damage);target.stun=broken?.42:.23+force*.07;target.guard=false;target.blockStun=false;target.action=null;target.roll=0;target.history=[];target.queued=null;target.vx=Math.sign(target.x-attacker.x||attacker.facing)*(145+force*80);target.flash=.16;target.energy=clamp(target.energy+damage*.5,0,100);attacker.energy=clamp(attacker.energy+damage*.65,0,100);attacker.chain=attacker.chainTimer>0?attacker.chain+1:1;attacker.chainTimer=1.1;attacker.hitCount++;this.events.push({type:broken?'break':'hit',side:target.side,damage,chain:attacker.chain});
// Count distinct landed attacks; pellets from one volley belong to the same attack.
if(attack.attackId===undefined||target.lastReceivedAttack!==attack.attackId){target.receivedHits=target.receivedWindow>0?target.receivedHits+1:1;target.receivedWindow=1.2;target.lastReceivedAttack=attack.attackId??null;}
if(target.receivedHits>=4&&target.hp>0){target.invincible=1;target.receivedHits=0;target.receivedWindow=0;target.stun=0;target.vx=0;target.chain=0;target.chainTimer=0;this.events.push({type:'protection',side:target.side});}}if(target.hp<=0)this.endRound(attacker.side);return blocked?"blocked":target.invincible>0?"protected":"hit";}
 launch(p,a){const ultimate=a.kind==='ultimate',id=p.id,count=a.move?(a.move.count??1):(a.count??(id==='soldier'&&!ultimate?3:1));for(let i=0;i<count;i++){this.projectiles.push({owner:p.side,attackId:a.id,id,x:p.x+p.facing*(34-i*20),y:p.y-(id==='wuwa'?65:id==='mystic'&&ultimate?74:48)+(id==='soldier'?(i-(count-1)/2)*7:0),vx:p.facing*(a.move?.speed??a.speed??(ultimate?570:420)),vy:0,age:0,life:ultimate?1.35:1.8,damage:((a.move?.splitDamage??a.splitDamage)||(!a.move&&id==='soldier'&&!ultimate))?a.damage/count:a.damage,combo:!!a.move,guardCost:(ultimate?18:a.move?10:8)/count,effect:a.move?.effect??a.effect,radius:a.move?.radius??a.radius??(ultimate?38:id==='soldier'?6:15),returnArrow:a.move?.returnArrow??(id==='mystic'&&!a.move?.noReturn),ultimate,returning:false,hits:new Set()});}this.events.push({type:'power',side:p.side,ultimate});}
 endRound(winner){if(this.phase!=='fight')return;this.phase='roundover';this.roundWinner=winner;if(winner!==null)this.wins[winner]++;this.delay=2.5;this.events.push({type:'roundEnd',winner});if(this.wins.some(n=>n>=2)){this.winner=this.wins[0]>=2?0:1;this.phase='finished';this.events.push({type:'finish',winner:this.winner});}}
 ai(dt){const p=this.players[1],foe=this.players[0],difficulty={easy:[.3,.55],medium:[.16,.8],hard:[.07,1]}[this.options.difficulty]||[.16,.8];this.aiThink-=dt;if(this.aiThink<=0){this.aiThink=difficulty[0];const distance=Math.abs(p.x-foe.x),incoming=this.projectiles.some(b=>b.owner===0&&Math.abs(b.x-p.x)<160);this.aiInput={move:distance>78?Math.sign(foe.x-p.x):distance<45?-Math.sign(foe.x-p.x):0,block:(incoming||foe.action?.t>foe.action?.start*.5)&&Math.random()<difficulty[1],jump:incoming&&Math.random()<.25,light:distance<88&&Math.random()<difficulty[1],heavy:distance<92&&Math.random()<.18,special:distance>145&&Math.random()<.45,ultimate:p.energy>=100&&Math.random()<.6};}return this.aiInput;}
 step(dt,inputs=[{},{}]){dt=clamp(dt,0,1/30);if(this.paused||this.phase==='finished')return;if(this.phase!=='fight'){this.delay-=dt;if(this.delay<=0){if(this.phase==='ready'){this.phase='fight';this.events.push({type:'fight'});}else{this.round++;this.newRound();}}return;}this.time=Math.max(0,this.time-dt);if(this.time===0){const [a,b]=this.players;this.endRound(a.hp===b.hp?null:a.hp>b.hp?0:1);return;}
 if(this.options.mode==='ai')inputs=[inputs[0]||{},this.ai(dt)];
 for(const p of this.players){const input=inputs[p.side]||{},foe=this.players[1-p.side];p.facing=foe.x>=p.x?1:-1;p.stun=Math.max(0,p.stun-dt);if(p.stun===0)p.blockStun=false;p.dodgeFlash=Math.max(0,p.dodgeFlash-dt);p.invincible=Math.max(0,p.invincible-dt);p.receivedWindow=Math.max(0,p.receivedWindow-dt);if(p.receivedWindow===0){p.receivedHits=0;p.lastReceivedAttack=null;}p.roll=Math.max(0,p.roll-dt);p.rollCooldown=Math.max(0,p.rollCooldown-dt);p.historyTime=Math.max(0,p.historyTime-dt);p.labelTime=Math.max(0,p.labelTime-dt);if(p.queued){p.queued.life-=dt;if(p.queued.life<=0)p.queued=null;}p.flash=Math.max(0,p.flash-dt);p.comboWindow=Math.max(0,p.comboWindow-dt);p.chainTimer=Math.max(0,p.chainTimer-dt);p.energy=clamp(p.energy+dt*2.1,0,100);p.guard=!!input.block&&p.ground&&(p.stun===0||p.blockStun)&&!p.action&&p.roll===0;
 if(input.roll&&p.ground&&p.stun===0&&!p.action&&p.rollCooldown===0){p.roll=.38;p.rollCooldown=.7;p.rollDirection=Math.sign(input.move||p.facing);p.guard=false;this.events.push({type:'roll',side:p.side});}if(p.roll>0){p.vx=p.rollDirection*400;}else if(p.stun===0){const target=!p.action&&!p.guard?clamp(input.move||0,-1,1)*205:0;p.vx+=(target-p.vx)*Math.min(1,dt*14);if(input.jump&&p.ground&&!p.action&&!p.guard){p.vy=-470;p.ground=false;this.events.push({type:'jump',side:p.side});}if(p.action&&!p.action.hit&&(p.action.move?.dash??p.action.dash))p.vx=p.action.direction*(p.action.move?.dash??p.action.dash);for(const kind of ['ultimate','special','heavy','light'])if(input[kind]){if(p.action)p.queued={kind,life:.32};else this.attack(p,kind);break;}if(!p.action&&p.queued){const kind=p.queued.kind;p.queued=null;this.attack(p,kind);}}else p.vx*=Math.max(0,1-dt*4);
 p.x=clamp(p.x+p.vx*dt,50,910);if(!p.ground){p.vy+=1250*dt;p.y+=p.vy*dt;if(p.y>=440){p.y=440;p.vy=0;p.ground=true;}}p.animation+=dt;
 if(p.action){const a=p.action;a.t+=dt;if(a.t>=a.start&&!a.hit){a.hit=true;if(a.range){if(Math.abs(p.x-foe.x)<a.range&&Math.abs(p.y-foe.y)<64){const result=this.hit(p,foe,a.damage,a.move?.force??a.force??(a.kind==='heavy'?1.5:1),{combo:!!a.move,attackId:a.id});if(a.move?.lift&&result==='hit'){foe.ground=false;foe.vy=-a.move.lift;}};}else this.launch(p,a);}if(a.t>=a.duration)p.action=null;}}
 const [a,b]=this.players;if(Math.abs(a.x-b.x)<42&&Math.abs(a.y-b.y)<56){const direction=a.x<=b.x?1:-1,shift=(42-Math.abs(a.x-b.x))/2;a.x=clamp(a.x-direction*shift,50,910);b.x=clamp(b.x+direction*shift,50,910);}
 for(const shot of this.projectiles){shot.age+=dt;shot.life-=dt;if(shot.returnArrow&&!shot.ultimate&&shot.age>.65&&!shot.returning){shot.vx*=-1;shot.returning=true;}shot.x+=shot.vx*dt;const foe=this.players[1-shot.owner];if(!shot.hits.has(foe.side)&&Math.abs(shot.x-foe.x)<shot.radius+20&&Math.abs(shot.y-(foe.y-43))<shot.radius+30){shot.hits.add(foe.side);const result=this.hit(this.players[shot.owner],foe,shot.damage,shot.ultimate?2:1,{dodgeable:!shot.ultimate,combo:shot.combo,ultimate:shot.ultimate,guardCost:shot.guardCost,attackId:shot.attackId});if(result!=="dodged")shot.life=0;}if(shot.returning&&Math.abs(shot.x-this.players[shot.owner].x)<20)shot.life=0;}
 this.projectiles=this.projectiles.filter(b=>b.life>0&&b.x>-80&&b.x<1040);}
 snapshot(){return {phase:this.phase,round:this.round,wins:[...this.wins],time:this.time,winner:this.winner,players:this.players.map(p=>({...p,history:[...p.history],queued:p.queued?{...p.queued}:null,action:p.action?{...p.action}:null})),projectiles:this.projectiles.length};}
}
const api={Match,HEROES,COMBOS};if(typeof module==='object')module.exports=api;root.PixelFightingCore=api;
})(typeof globalThis==='object'?globalThis:this);
