/* Local-only UI: no accounts, rooms, remote libraries or other engines. */
(()=>{'use strict';const C=FlightCore,A=FlightAI,art=FlightArt,$=id=>document.getElementById(id),CN=['红','黄','蓝','绿'];let game=null,players=[],settings=null,paused=false,busy=false,epoch=0,timer=null,sound=true,audio=null,lastHit=null;const buttons=[];const clean=x=>String(x).normalize('NFKC').replace(/[^A-Za-z0-9一-鿿]/gu,'').slice(0,12);
let remembered=[];try{remembered=JSON.parse(localStorage.getItem('pq-flight-names')||'[]')}catch{}if(!Array.isArray(remembered))remembered=[];
function tone(type='move'){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type='square';o.frequency.setValueAtTime(type==='win'?660:type==='hit'?130:type==='roll'?330:440,t);o.frequency.exponentialRampToValueAtTime(type==='win'?990:220,t+.13);g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(audio.destination);o.start();o.stop(t+.21)}catch{}}
function cancel(){epoch++;clearTimeout(timer);timer=null;busy=false;$('dice').classList.remove('rolling')}
function humanTurn(){return game&&game.winner===null&&!players[game.turn].ai&&!paused&&!busy&&!$('setup').open&&!$('rules').open}
function draw(){if(!game)return;const legal=game.phase==='choose'&&humanTurn()?C.legal(game):[],occupied=new Map();for(let c=0;c<4;c++)for(let i=0;i<4;i++){const xy=art.point(c,i,game.planes[c][i]),key=xy.join(',');if(!occupied.has(key))occupied.set(key,[]);occupied.get(key).push([c,i])}
for(let c=0;c<4;c++)for(let i=0;i<4;i++){const b=buttons[c*4+i],p=game.planes[c][i],xy=art.point(c,i,p),stack=occupied.get(xy.join(',')),k=stack.findIndex(([a,j])=>a===c&&j===i),n=stack.length,cols=Math.ceil(Math.sqrt(n)),rows=Math.ceil(n/cols),extent=p===57?.55:.84,offset=n===1?[0,0]:[(k%cols-(cols-1)/2)*extent/cols,(Math.floor(k/cols)-(rows-1)/2)*extent/cols];b.style.setProperty('--plane-size',(n===1?.6:extent/cols)/15*100+'%');b.classList.toggle('dense',n>4);b.style.left=(xy[0]+.5+offset[0])/15*100+'%';b.style.top=(xy[1]+.5+offset[1])/15*100+'%';b.classList.toggle('legal',c===game.turn&&legal.includes(i));b.classList.toggle('done',p===57);b.disabled=!(c===game.turn&&legal.includes(i));b.setAttribute('aria-label',`${players[c].nickname} ${CN[c]}方 ${i+1}号飞机，${p<0?'基地':p===57?'已完成':p>=52?'终点航线 '+(p-51):'主航线 '+p}${b.disabled?'':'，可移动'}`);b.title=b.getAttribute('aria-label');if(lastHit?.includes(c+':'+i)){b.classList.remove('hit');void b.offsetWidth;b.classList.add('hit')}}lastHit=null;
const markers=[];for(const [key,stack]of occupied){if(stack.length<2||game.planes[stack[0][0]][stack[0][1]]===57)continue;const [x,y]=key.split(',').map(Number),tag=document.createElement('span');tag.className='stack-count';tag.textContent=stack.length;tag.setAttribute('aria-label','同格 '+stack.length+' 架飞机');tag.style.left=(x+.96)/15*100+'%';tag.style.top=(y+.05)/15*100+'%';markers.push(tag)}$('stack-markers').replaceChildren(...markers);
$('players').replaceChildren(...players.map((p,c)=>{const d=document.createElement('div');d.className='player'+(c===game.turn&&game.winner===null?' active':'');d.style.setProperty('--color',art.colors[c]);const name=document.createElement('strong'),detail=document.createElement('small');name.textContent=CN[c]+' · '+p.nickname;detail.textContent=(p.ai?'AI '+settings.difficulty.toUpperCase():'真人')+' · 完成 '+game.planes[c].filter(p=>p===57).length+'/4';d.append(name,detail);return d}));$('turn-label').textContent=game.winner!==null?players[game.winner].nickname+' 获胜':CN[game.turn]+' · '+players[game.turn].nickname;$('turn-label').style.color=art.colors[game.winner??game.turn];$('dice').textContent=game.dice??'?';$('dice').setAttribute('aria-label','骰子点数 '+(game.dice??'未掷'));$('roll').disabled=!humanTurn()||game.phase!=='roll';$('pause').disabled=busy||game.winner!==null;$('pause').textContent=paused?'继续 RESUME':'暂停 PAUSE';$('result').hidden=game.winner===null;$('winner').textContent=game.winner===null?'':C.COLORS[game.winner]+' WINS';$('mode-label').textContent=settings.mode==='single'?'1P VS 3 AI / '+settings.difficulty.toUpperCase():players.filter(p=>!p.ai).length+'P LOCAL / '+settings.difficulty.toUpperCase();
let text=game.winner!==null?'四架飞机全部完成，恭喜！':paused?'已暂停，所有 AI 停止行动。':busy?'正在行动…':players[game.turn].ai?'AI 正在思考…':game.phase==='choose'?'点选一架金色飞机，或使用下方选机按钮。':'请 '+players[game.turn].nickname+' 掷骰。';const action=game.last;if(!busy&&action?.type==='skip')text=CN[action.color]+'方 '+action.value+' 点无飞机可动；'+text;if(!busy&&action?.type==='move'){const note=action.captured.length?'撞回 '+action.captured.length+' 架飞机！ ':action.jump?'跳跃 '+action.jump+' 格。 ':action.to===57?'一架飞机到达终点！ ':'';text=note+(game.winner===null&&action.value===6?'6 点追加掷骰。 ':'')+text}$('status').textContent=text;$('choices').hidden=!legal.length;$('choices').replaceChildren(...legal.map(i=>{const b=document.createElement('button');b.type='button';b.textContent=(i+1)+' 号飞机 '+(game.planes[game.turn][i]<0?'起飞':'前进');b.onclick=()=>performMove(i);return b}))}
function schedule(){clearTimeout(timer);if(!game||paused||busy||game.winner!==null||$('setup').open||$('rules').open||!players[game.turn].ai)return;const id=epoch;timer=setTimeout(()=>{if(id!==epoch)return;if(game.phase==='roll')performRoll();else performMove(A.choose(game,settings.difficulty))},650)}
function performRoll(){if(!game||game.phase!=='roll'||game.winner!==null||paused||busy||$('setup').open||$('rules').open)return;busy=true;draw();$('dice').classList.add('rolling');tone('roll');const id=epoch,value=C.dice();timer=setTimeout(()=>{if(id!==epoch)return;game=C.roll(game,value);busy=false;$('dice').classList.remove('rolling');draw();schedule()},350)}
function performMove(i){if(!game||paused||busy||game.winner!==null||game.phase!=='choose'||!C.legal(game).includes(i)||$('setup').open||$('rules').open)return;clearTimeout(timer);const id=epoch;game=C.move(game,i);busy=true;lastHit=game.last.captured.map(([c,j])=>c+':'+j);tone(game.winner!==null?'win':lastHit.length?'hit':'move');draw();timer=setTimeout(()=>{if(id!==epoch)return;busy=false;draw();schedule()},400)}
function start(next){cancel();settings=JSON.parse(JSON.stringify(next));players=Array.from({length:4},(_,c)=>({color:c,nickname:'AI '+CN[c],ai:true}));if(next.mode==='single')players[next.color]={color:next.color,nickname:'玩家',ai:false};else for(const p of next.humans)players[p.color]={...p,ai:false};game=C.initial();paused=false;$('setup').close();draw();schedule()}
for(let c=0;c<4;c++)for(let i=0;i<4;i++){const b=document.createElement('button');b.className='plane';b.type='button';b.dataset.color=c;b.dataset.plane=i;b.style.setProperty('--color',art.colors[c]);const canvas=document.createElement('canvas');canvas.width=canvas.height=80;art.plane(canvas.getContext('2d'),0,0,80,art.colors[c]);const no=document.createElement('small');no.textContent=i+1;b.append(canvas,no);b.onclick=()=>{if(humanTurn()&&c===game.turn)performMove(i)};$('planes').append(b);buttons.push(b)}const markers=document.createElement('div');markers.id='stack-markers';$('planes').append(markers);art.board($('board'));
function setupRows(){const existing=[...$('local-players').children].map(row=>({nickname:row.querySelector('input').value,color:Number(row.querySelector('select').value)})),local=$('mode').value==='local';$('count-label').hidden=!local;$('local-players').hidden=!local;$('single-color-label').hidden=local;const count=Number($('count').value);$('local-players').replaceChildren(...Array.from({length:count},(_,i)=>{const row=document.createElement('div');row.className='local-player-row';const nameLabel=document.createElement('label'),name=document.createElement('input'),colorLabel=document.createElement('label'),color=document.createElement('select');nameLabel.textContent='玩家 '+(i+1)+' 昵称';name.value=existing[i]?.nickname||remembered[i]||'玩家'+(i+1);name.maxLength=12;name.minLength=2;name.required=local;name.autocomplete='nickname';name.oninput=()=>{name.value=clean(name.value);$('setup-error').textContent=''};colorLabel.textContent='棋子颜色';for(let c=0;c<4;c++){const o=document.createElement('option');o.value=c;o.textContent=C.COLORS[c]+' / '+CN[c];color.append(o)}color.value=existing[i]?.color??i;nameLabel.append(name);colorLabel.append(color);row.append(nameLabel,colorLabel);return row}));$('setup-error').textContent=''}
$('mode').onchange=setupRows;$('count').onchange=setupRows;$('setup-form').onsubmit=e=>{e.preventDefault();const next={mode:$('mode').value,difficulty:$('difficulty').value,color:Number($('color').value),humans:[]};if(next.mode==='local'){next.humans=[...$('local-players').children].map(row=>({nickname:clean(row.querySelector('input').value),color:Number(row.querySelector('select').value)}));if(next.humans.some(p=>p.nickname.length<2)){$('setup-error').textContent='昵称需为 2～12 个中文、英文或数字。';return}if(new Set(next.humans.map(p=>p.color)).size!==next.humans.length){$('setup-error').textContent='每名玩家请选择不同的棋子颜色。';return}remembered=next.humans.map(p=>p.nickname);try{localStorage.setItem('pq-flight-names',JSON.stringify(remembered))}catch{}}start(next)};
$('roll').onclick=()=>{if(humanTurn())performRoll()};$('pause').onclick=()=>{if(!game||busy||game.winner!==null)return;paused=!paused;clearTimeout(timer);draw();schedule()};$('rematch').onclick=()=>{if(settings)start(settings)};$('configure').onclick=()=>{if(busy)return;clearTimeout(timer);$('setup').showModal();draw()};$('cancel').onclick=()=>{if(game){$('setup').close();draw();schedule()}else location.href='./'};$('setup').addEventListener('cancel',e=>{if(!game)e.preventDefault();else setTimeout(()=>{draw();schedule()},0)});$('rules-open').onclick=()=>{if(busy)return;clearTimeout(timer);$('rules').showModal();draw()};$('rules-close').onclick=()=>{$('rules').close();draw();schedule()};$('rules').addEventListener('cancel',()=>setTimeout(()=>{draw();schedule()},0));$('sound').onclick=()=>{sound=!sound;$('sound').textContent='SOUND '+(sound?'ON':'OFF')};document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&game.winner===null){paused=true;if(!busy)clearTimeout(timer);draw()}});window.addEventListener('pagehide',cancel);window.PixelFlight={get game(){return game},get players(){return players},get settings(){return settings},get busy(){return busy},start,draw};setupRows();$('setup').showModal();
})();
