/* Pixel Quest. Original art, levels, and synthesized audio. No runtime dependencies. */
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const W=480,H=270,T=16,keys=new Set(),pressed=new Set();
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
let state='title',world,player,camera=0,score=0,coins=0,lives=3,stage=0,time=300,checkpoint=0,particles=[],popups=[],items=[],shots=[],fireworks=[],frame=0,transition=0,finishTime=0,exitPhase='',exitTick=0,muted=false,last=0,acc=0,best=0,saved=null,selectedCharacter='explorer';
try{best=Number(localStorage.getItem('pq-best'))||0;saved=JSON.parse(localStorage.getItem('pq-save'));}catch{}$('#best').textContent='BEST '+String(best).padStart(6,'0');if(saved&&saved.stage>=0&&saved.stage<4)$('#continue').hidden=false;
const themes=[{name:'SUNRISE MEADOW',sky:'#7dcbe8',hills:'#54bda0',far:'#a1dfcf',ground:'#b85e38',edge:'#edac5f',dark:'#713d32',grass:'#6fbc4d'},{name:'THE CRYSTAL CAVERN',sky:'#192c46',hills:'#253c59',far:'#304e69',ground:'#466788',edge:'#8ba1b5',dark:'#223b56',grass:'#77b5c2'},{name:'CLOUDTOP CROSSING',sky:'#80c8de',hills:'#e4eef0',far:'#b4e2e7',ground:'#b97a45',edge:'#f6d095',dark:'#755036',grass:'#f0eee2'},{name:'EMBER KEEP',sky:'#2e2539',hills:'#45334b',far:'#644052',ground:'#66536b',edge:'#a18a94',dark:'#352f43',grass:'#bb7970'}];
class AudioEngine{
 constructor(){this.context=null;this.next=0;this.beat=0;}
 init(){if(!this.context){this.context=new (window.AudioContext||window.webkitAudioContext)();this.bus=this.context.createGain();this.bus.gain.value=.16;this.bus.connect(this.context.destination);}this.context.resume().catch(()=>{});}
 tone(freq,duration=.12,type='square',volume=.25,delay=0,slide=0){if(!this.context||muted)return;const c=this.context,o=c.createOscillator(),g=c.createGain(),now=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,slide),now+duration);g.gain.setValueAtTime(volume,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(this.bus);o.start(now);o.stop(now+duration);}
 sfx(name){const lists={coin:[[988,.07],[1319,.17]],jump:[[250,.13,'square',.22,0,600]],bump:[[160,.08]],power:[[392,.1],[494,.1],[587,.1],[784,.22]],stomp:[[150,.12,'triangle',.6,0,60]],hurt:[[600,.25,'sawtooth',.25,0,80]],fire:[[700,.1,'triangle',.4,0,120]],life:[[523,.1],[659,.1],[784,.1],[1046,.3]],death:[[494,.15],[466,.15],[440,.15],[349,.35],[262,.5]],win:[[523,.15],[659,.15],[784,.15],[1046,.2],[784,.15],[1046,.5]]};let d=0;for(const n of lists[name]||[]){this.tone(n[0],n[1],n[2]||'square',n[3]||.3,d+(n[4]||0),n[5]||0);d+=n[1]*.8;}}
 update(){if(!this.context||muted||state!=='playing')return;const c=this.context;if(this.next<c.currentTime)this.next=c.currentTime+.04;while(this.next<c.currentTime+.12){const melody=stage===3?[52,0,55,57,52,0,59,55,50,0,53,55,50,0,57,53]:stage===1?[64,0,67,71,67,0,64,62,59,0,62,66,62,0,59,57]:[76,0,76,0,72,76,79,0,67,0,72,0,67,0,64,0,69,71,70,69,67,76,79,81,77,79,0,76,72,74,71,0];const note=melody[this.beat%melody.length];if(note)this.tone(440*2**((note-69)/12),.12,'square',.11,this.next-c.currentTime);if(this.beat%2===0)this.tone(440*2**(([48,48,53,55][Math.floor(this.beat/8)%4]-69)/12),.17,'triangle',.23,this.next-c.currentTime);if(this.beat%4===2)this.tone(95,.03,'triangle',.2,this.next-c.currentTime,30);this.next+=time<60?.11:.145;this.beat++;}}
}
const audio=new AudioEngine();
const art={"grub":[".....DDDDD......","...DDDDDDDDD....","..DDDDDDDDDDD...",".DDWWDDDDWWDDD..",".DDWKDDDDKWDDD..","DDDDDHHHHDDDDDD.","DDDDDDDDDDDDDDD.","..DDDDDDDDDDD...","...TTTTTTTTT....","...TTTTTTTTT....","..KKKK...KKKK...",".KKKKK...KKKKK.."],"turtle":["......GGGG......",".....GGGGGG.....","....GGWWGGGG....","....GGWKGGGG....",".....GGGGGG.....",".....YYYYG......","...DDDDDDDD.....","..DGGGGGGGGD....",".DGGGGGGGGGGD...",".DGGGDDDDGGGD...",".DDDDGGGGDDDD...","..DGGGGGGGGD....","...DDDDDDDD.....","..YY......YY....",".YYYY....YYYY..."],"mushroom":[".....RRRRRR.....","...RRWWRRWWRR...","..RRWWWWWWWWRR..",".RRRWWRRRRWWRRR.",".RRRRRRRRRRRRRR.","RRWWRRRRRRRRWWRR","RWWWWRRRRRRWWWWR","RRWWRRRRRRRRWWRR","....SSSSSSSS....","....SSKSSKSS....","....SSSSSSSS....",".....SSSSSS....."],"flower":[".....YYYYYY.....","...YYWWWWWWYY...","..YWWRRRRRRWWY..","..YWRWWRRWWRWY..","..YWRWKRRKWRWY..","..YWWRRRRRRWWY..","...YYWWWWWWYY...",".....YYYYYY.....",".......GG.......","..GGG..GG..GGG..","...GGGGGGGGGG...",".....GGGGGG....."],"dorayaki":["...DDDDDDDD...","..DDDDDDDDDD..",".DDTTTTTTTTDD.","DDTSSSSSSSSTDD","DDTSSSSSSSSTDD",".DDTTTTTTTTDD.","..DDDDDDDDDD..","...DDDDDDDD..."],"dragonball":["....YYYYYY....","..YYYYYYYYYY..",".YYYYYYYYYYYY.","YYYYRYYRYYYYYY","YYYYYYYYYYYYYY","YYYRYYYYRYYYYY","YYYYYYYYYYYYYY",".YYYYYYYYYYYY.","..YYYYYYYYYY..","....YYYYYY...."],"mysticOrb":[".....BBBB.....","...BBWWWWBB...","..BBWWWWWWBB..",".BBWWKWWWWBB.","BBWWKWWKWWWWBB","BBWWWWKWWWWWBB",".BBWWWWWWWWBB.","..BBWWWWWWBB..","...BBWWWWBB...",".....BBBB....."],"lotus":["......PP......","...P.PPPP.P...","..PPPPPPPPPP..",".PPPPYYYYPPPP.","PPPPYYYYYYPPPP",".PPPYWWYYPPPP.","..PPYYYYYYPP..","...PPYYYYPP...","....PPPPPP....","......GG......"],"star":[".......YY.......","......YYYY......","......YYYY......",".YYYYYYYYYYYYYY.","..YYYYYYYYYYYY..","...YYKYYKYYYY...","....YKYYKYYY....","...YYYYYYYYYY...","...YYYYYYYYYY...","..YYYYY..YYYYY..","..YYY......YYY..",".YY..........YY."]};
Object.assign(art,PixelQuestCharacters.art);
const {ids:characterIds,palette,colors:{soldier:soldierColors,mystic:mysticColors,dora:doraColors,goku:gokuColors,nezha:nezhaColors}}=PixelQuestCharacters;
function sprite(name,x,y,flip=false,scale=1,colors={}){const rows=art[name];if(!rows)return;ctx.save();ctx.translate(Math.round(x)+(flip?Math.max(...rows.map(r=>r.length))*scale:0),Math.round(y));ctx.scale(flip?-scale:scale,scale);for(let y=0;y<rows.length;y++)for(let x=0;x<rows[y].length;x++){let c=rows[y][x];if(c!=='.'){ctx.fillStyle=colors[c]||palette[c];ctx.fillRect(x,y,1,1);}}ctx.restore();}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}
function text(s,x,y,size=8,color='#fff4d6',align='left'){ctx.font=`bold ${size}px monospace`;ctx.textAlign=align;ctx.fillStyle='#263442';ctx.fillText(s,Math.round(x)+1,Math.round(y)+1);ctx.fillStyle=color;ctx.fillText(s,Math.round(x),Math.round(y));}
function makeWorld(n){const tiles=new Map(),collect=[],enemies=[],platforms=[];const lengths=[220,210,220,230],length=lengths[n];const set=(x,y,type,content)=>tiles.set(x+','+y,{x:x*T,y:y*T,w:T,h:T,type,content,bump:0});const ground=(a,b,y=14)=>{for(let x=a;x<b;x++)for(let r=y;r<17;r++)set(x,r,'ground');};const block=(x,y,type='brick',content)=>set(x,y,type,content);const line=(a,b,y)=>{for(let x=a;x<=b;x++)collect.push({x:x*T+4,y:y*T+3,w:8,h:11});};const pipe=(x,height=2)=>{for(let y=14-height;y<14;y++)for(let a=0;a<2;a++)set(x+a,y,y===14-height?'pipeTop':'pipe');};const enemy=(x,type='grub',y=14)=>enemies.push({x:x*T,y:y*T-(type==='turtle'?16:12),w:14,h:type==='turtle'?16:12,vx:-.42-n*.06,vy:0,type,alive:true,shell:false,kicked:false,timer:0});const stairs=(x,count)=>{for(let i=0;i<count;i++)for(let j=0;j<=i;j++)set(x+i,13-j,'stone');};
 if(n===0){[[0,47],[50,80],[83,116],[120,157],[160,length]].forEach(a=>ground(...a));block(16,10,'question','mushroom');block(20,10,'brick');block(21,10,'question','coin');block(22,10,'brick');block(23,10,'question','coin');block(24,10,'brick');block(22,6,'question','star');pipe(30,2);pipe(39,3);pipe(58,2);for(let x=66;x<73;x++)block(x,9);block(69,5,'question','flower');line(66,72,8);for(let x=89;x<94;x++)block(x,10,x===91?'question':'brick',x===91?'mushroom':null);line(96,101,9);for(let x=98;x<104;x++)block(x,10);stairs(108,5);pipe(128,3);block(132,9,'question','star');for(let x=137;x<145;x++)block(x,10,x%3===0?'question':'brick','coin');line(148,154,10);stairs(165,4);stairs(175,6);block(185,8,'question','flower');enemy(24);enemy(43);enemy(63);enemy(76,'turtle');enemy(94);enemy(100);enemy(136,'turtle');enemy(150);enemy(170);}
 if(n===1){[[0,41],[44,75],[78,112],[116,145],[148,176],[180,length]].forEach(a=>ground(...a));for(let x=0;x<length;x++)set(x,2,'stone');for(let x=13;x<22;x++)block(x,10,x===15?'question':'brick',x===15?'mushroom':null);line(13,21,9);pipe(29,3);stairs(35,4);for(let x=49;x<56;x++)block(x,9);block(52,8,'question','flower');line(60,67,10);for(let x=60;x<68;x++)block(x,11);pipe(70,2);for(let x=86;x<94;x++)block(x,9);line(86,93,8);block(90,5,'question','star');stairs(102,5);for(let x=121;x<129;x++)block(x,10,x%2?'question':'brick','coin');block(127,6,'question','mushroom');pipe(137,3);for(let x=153;x<161;x++)block(x,9);line(154,160,8);stairs(166,5);stairs(184,6);enemy(24);enemy(52,'turtle');enemy(63);enemy(83);enemy(95);enemy(128,'turtle');enemy(157);enemy(161);enemy(187,'turtle');}
 if(n===2){[[0,27],[31,49],[53,70],[75,96],[101,123],[128,152],[156,179],[183,length]].forEach(a=>ground(...a));block(12,10,'question','mushroom');line(19,25,10);for(let x=20;x<27;x++)block(x,11,'cloud');for(let x=35;x<41;x++)block(x,10,'cloud');line(35,40,9);block(38,6,'question','flower');pipe(44,2);for(let x=58;x<65;x++)block(x,10,'cloud');line(58,64,9);for(let x=80;x<87;x++)block(x,11,'cloud');block(84,7,'question','star');for(let x=105;x<113;x++)block(x,9,'cloud');line(105,112,8);pipe(117,3);for(let x=134;x<141;x++)block(x,10,'cloud');block(138,6,'question','mushroom');line(143,149,10);for(let x=162;x<168;x++)block(x,10,'cloud');line(162,167,9);stairs(172,5);stairs(190,7);for(const x of [29,51,72,98,125,154,181])platforms.push({x:x*T,y:12*T,w:32,h:8,base:x*T,t:0,range:18,vx:0});enemy(21,'turtle');enemy(36,'turtle',10);enemy(61);enemy(84,'turtle');enemy(111,'turtle',9);enemy(144);enemy(165,'turtle',10);enemy(189);}
 if(n===3){[[0,39],[43,70],[74,105],[110,137],[142,170],[175,length]].forEach(a=>ground(...a));for(let x=0;x<length;x++)set(x,2,'stone');block(13,10,'question','flower');for(let x=20;x<28;x++)block(x,11,'stone');line(20,27,10);pipe(33,3);for(let x=48;x<55;x++)block(x,9,'stone');block(51,8,'question','star');line(58,65,10);stairs(63,5);for(let x=81;x<88;x++)block(x,10,'stone');block(85,6,'question','flower');pipe(97,3);for(let x=116;x<123;x++)block(x,10,'stone');line(116,122,9);block(129,9,'question','mushroom');stairs(132,4);for(let x=149;x<159;x++)block(x,10,'stone');block(154,6,'question','flower');stairs(163,4);stairs(185,6);enemy(24,'turtle');enemy(50);enemy(59,'turtle');enemy(85);enemy(93,'turtle');enemy(119,'turtle');enemy(153);enemy(160,'turtle');enemies.push({x:202*T,y:14*T-32,w:30,h:32,vx:-.45,vy:0,type:'boss',alive:true,hp:5,timer:0});}
 block(n===0?10:17,9,'hidden','star');
 if(n!==2){const plantPipes=n===0?[39,128]:n===1?[29,137]:[33,97];for(const x of plantPipes){const base=(14-3)*T;enemies.push({x:x*T+8,y:base,w:16,h:20,base,vx:0,vy:0,type:'plant',alive:true,age:x*3,active:false});}}
 const flagX=(n===0?190:length-13)*T;return {tiles,collect,enemies,platforms,length:length*T,flagX,exitX:flagX+9*T,checkpointX:Math.floor(length/2)*T,theme:themes[n]};}
function loadStage(n,respawn=false){stage=n;world=makeWorld(n);camera=0;particles=[];popups=[];items=[];shots=[];fireworks=[];time=300;finishTime=0;exitPhase='';exitTick=0;const tier=respawn?0:(player?.power||0),weapon=selectedCharacter!=='soldier'||respawn||tier===0?'none':tier===1?'rifle':player?.weapon==='lightning'?'lightning':'spread';player={x:respawn&&checkpoint?checkpoint:40,y:160,w:12,h:16,vx:0,vy:0,facing:1,ground:false,character:selectedCharacter,power:tier,weapon,inv:90,star:0,coyote:0,buffer:0,jumps:0,jumpKind:'normal',jumpVisual:false,bufferKind:'normal',fire:0,dead:0};if(player.character!=='explorer'){player.y-=8;player.w=player.character==='dora'?18:14;player.h=24;}else if(player.power)resizeHero(true);$('#stage-label').textContent=String(n+1).padStart(2,'0')+' / '+themes[n].name;audio.beat=0;if(state!=='title')save();}
function save(){try{localStorage.setItem('pq-save',JSON.stringify({stage,score,coins,lives,character:selectedCharacter,power:player?.power||0,weapon:player?.weapon||'none'}));if(score>best){best=score;localStorage.setItem('pq-best',best);}$('#best').textContent='BEST '+String(best).padStart(6,'0');}catch{}}
function start(resume=false){audio.init();if(resume)selectedCharacter=characterIds.includes(saved.character)?saved.character:'explorer';keys.clear();pressed.clear();$('#character-picker').hidden=true;$('.overlay-content').hidden=false;score=resume?saved.score:0;coins=resume?saved.coins:0;lives=resume?saved.lives:3;checkpoint=0;player={power:resume?saved.power:0,weapon:resume?saved.weapon:undefined};state='playing';loadStage(resume?saved.stage:0);$('#overlay').hidden=true;canvas.focus();}
function modal(tag,title,copy,button,hint='PRESS ENTER TO CONTINUE'){ $('#character-picker').hidden=true;$('.overlay-content').hidden=false;$('#overlay-tag').textContent=tag;$('#overlay-title').innerHTML=title;$('#overlay-copy').textContent=copy;$('#play').innerHTML=button+' <span>▶</span>';$('#continue').hidden=true;$('#home').hidden=true;$('#cancel-home').hidden=true;$('#overlay-hint').textContent=hint;$('#overlay').hidden=false;updateOverlayMode();}
function activate(){if(state==='title')showCharacterPicker();else if(state==='selecting')start();else if(state==='paused'){state='playing';$('#overlay').hidden=true;canvas.focus();}else if(state==='confirmhome')returnHome();else if(state==='gameover'||state==='victory')showCharacterPicker();else if(state==='stageclear'){checkpoint=0;loadStage(stage+1);state='playing';$('#overlay').hidden=true;canvas.focus();}}
function showPause(){state='paused';modal('TAKE A BREATHER','PAUSED','Your adventure will be right here.','KEEP PLAYING','P OR ENTER TO RESUME · ESC FOR HOME');$('#home').hidden=false;$('#play').focus();}
function showHomeConfirmation(){if(state!=='paused')return;state='confirmhome';modal('LEAVE THIS ADVENTURE?','RETURN<span>HOME?</span>','Progress is saved. Continue restarts this world.','YES, RETURN HOME','ENTER TO CONFIRM · ESC TO CANCEL');$('#cancel-home').hidden=false;$('#play').focus();}
function cancelHome(){if(state==='confirmhome')showPause();}
function returnHome(){if(state!=='confirmhome')return;save();try{saved=JSON.parse(localStorage.getItem('pq-save'));}catch{saved=null;}state='title';score=0;coins=0;lives=3;checkpoint=0;player={power:0,weapon:'none'};loadStage(0);modal('A NEW ADVENTURE AWAITS','PIXEL<span>QUEST</span>','Four worlds. Hidden treasures. One brave little explorer.','LET’S PLAY','PRESS ENTER TO START · SOUND BEGINS WHEN YOU PLAY');$('#continue').hidden=!saved;$('#play').focus();}
function pause(){if(state==='playing')showPause();else if(state==='paused')activate();else if(state==='confirmhome')cancelHome();}
$('#play').onclick=activate;$('#continue').onclick=()=>start(true);$('#home').onclick=showHomeConfirmation;$('#cancel-home').onclick=cancelHome;$('#pause').onclick=pause;$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'SOUND OFF':'SOUND ON';if(!muted)audio.init();};$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else $('.screen').requestFullscreen?.().catch(()=>{});};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','Enter','Escape'].includes(e.code))e.preventDefault();if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(e.repeat)return;if(e.code==='Enter'){if(state==='title'&&e.target?.id==='play-badminton')playBadminton();else if(state==='title'&&e.target?.id==='play-kart')playKart();else if(state==='paused'&&e.target?.id==='home')showHomeConfirmation();else if(state==='confirmhome'&&e.target?.id==='cancel-home')cancelHome();else activate();}if(e.code==='KeyP')pause();if(e.code==='Escape'){if(state==='playing')showPause();else if(state==='paused')showHomeConfirmation();else if(state==='confirmhome')cancelHome();}if(e.code==='KeyM')$('#sound').click();if(e.code==='KeyR'&&['playing','paused','stageclear','gameover','victory'].includes(state))start();if(state==='selecting'&&['ArrowLeft','ArrowRight','KeyA','KeyD'].includes(e.code))selectCharacter(characterIds[(characterIds.indexOf(selectedCharacter)+(e.code==='ArrowLeft'||e.code==='KeyA'?characterIds.length-1:1))%characterIds.length]);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pressed.clear();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);let k=b.dataset.key;if(!keys.has(k))pressed.add(k);keys.add(k);audio.init();});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.key));});
function showCharacterPicker(){audio.init();state='selecting';keys.clear();pressed.clear();$('.overlay-content').hidden=true;$('#character-picker').hidden=false;$('#overlay').hidden=false;selectCharacter(selectedCharacter);$('#choose-'+selectedCharacter).focus();}
function selectCharacter(id){selectedCharacter=id;$('#choose-'+id).focus();for(const name of characterIds){$('#choose-'+name).setAttribute('aria-pressed',String(name===id));}$('#character-start').textContent=id==='soldier'?'DEPLOY COMMANDO ▶':id==='mystic'?'START MYSTIC QUEST ▶':id==='dora'?'LET’S GO, DORAEMON! ▶':id==='goku'?'LET’S GO, GOKU! ▶':id==='nezha'?'LET’S GO, NEZHA! ▶':'START ADVENTURE ▶';}
$('#choose-explorer').onclick=()=>selectCharacter('explorer');$('#choose-soldier').onclick=()=>selectCharacter('soldier');$('#choose-mystic').onclick=()=>selectCharacter('mystic');$('#choose-dora').onclick=()=>selectCharacter('dora');$('#choose-goku').onclick=()=>selectCharacter('goku');$('#choose-nezha').onclick=()=>selectCharacter('nezha');$('#character-start').onclick=()=>start();
// Main menu mode row. Adventure keeps the existing flow; Badminton and Pixel Kart
// hand off to their own standalone pages, which load none of this engine.
function playBadminton(){location.href='badminton.html';}
function playKart(){location.href='kart.html';}
function updateOverlayMode(){const onTitle=state==='title';$('#play-badminton').hidden=!onTitle;$('#play-kart').hidden=!onTitle;if(onTitle){$('#play').innerHTML='ADVENTURE <span>▶</span>';}}
$('#play-badminton').onclick=playBadminton;
$('#play-kart').onclick=playKart;
updateOverlayMode();
function paintPortrait(id,name,colors){const c=$(id),p=c.getContext('2d'),rows=art[name];p.imageSmoothingEnabled=false;const scale=Math.min(4,Math.floor((c.height-12)/rows.length)),ox=(c.width-Math.max(...rows.map(r=>r.length))*scale)/2,oy=(c.height-rows.length*scale)/2;for(let y=0;y<rows.length;y++)for(let x=0;x<rows[y].length;x++)if(rows[y][x]!=='.'){p.fillStyle=colors[rows[y][x]]||palette[rows[y][x]];p.fillRect(ox+x*scale,oy+y*scale,scale,scale);}}
paintPortrait('#portrait-explorer','hero',{});paintPortrait('#portrait-soldier','soldier',soldierColors);paintPortrait('#portrait-mystic','mystic',mysticColors);paintPortrait('#portrait-dora','dora',doraColors);paintPortrait('#portrait-goku','goku',gokuColors);paintPortrait('#portrait-nezha','nezha',nezhaColors);
function solidAt(x,y){return world.tiles.get(Math.floor(x/T)+','+Math.floor(y/T));}
function solids(b){let a=[];for(let y=Math.floor(b.y/T);y<=Math.floor((b.y+b.h-.01)/T);y++)for(let x=Math.floor(b.x/T);x<=Math.floor((b.x+b.w-.01)/T);x++){const t=world.tiles.get(x+','+y);if(t)a.push(t);}return a;}
function moveBody(b,head=false){b.x+=b.vx;for(const t of solids(b)){if(t.type==='hidden'||!overlap(b,t))continue;if(b.vx>0)b.x=t.x-b.w;else if(b.vx<0)b.x=t.x+t.w;b.vx=head?0:-b.vx;}b.x=Math.max(0,b.x);const prevBottom=b.y+b.h;b.y+=b.vy;b.ground=false;for(const t of solids(b)){if(!overlap(b,t)||(t.type==='hidden'&&(b.vy>=0||!head)))continue;if(b.vy>0){b.y=t.y-b.h;b.ground=true;b.vy=0;}else if(b.vy<0){b.y=t.y+t.h;b.vy=0;if(head)bump(t);}}if(b.vy>=0)for(const p of world.platforms){if(b.x+b.w>p.x&&b.x<p.x+p.w&&prevBottom<=p.y+2&&b.y+b.h>=p.y&&b.y+b.h<p.y+14){b.y=p.y-b.h;b.vy=0;b.ground=true;b.x+=p.vx;}}}
function points(n,x,y){score+=n;popups.push({s:String(n),x,y,life:55});if(score>best){best=score;$('#best').textContent='BEST '+String(best).padStart(6,'0');try{localStorage.setItem('pq-best',best);}catch{}}}
function coin(x,y){coins++;points(100,x,y);audio.sfx('coin');if(coins>=100){coins-=100;lives++;audio.sfx('life');popups.push({s:'1 UP',x,y:y-15,life:90});}}
function burst(x,y,color,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*3,vy:-Math.random()*3-1,c:color,life:35+Math.random()*20,size:2});}
function rewardFor(content){if(content==='coin'||content==='star')return content;switch(player.character){case 'soldier':return player.power===0?'weaponN':content==='flower'?'weaponS':'weaponL';case 'dora':return 'dorayaki';case 'goku':return 'dragonball';case 'mystic':return 'mysticOrb';case 'nezha':return 'lotus';default:return content==='flower'&&player.power===0?'mushroom':content;}}
const fireworkColors=['#ffe77a','#ff8f72','#9befff','#d8a8ff','#b7f48a'];
function launchFirework(){const center=world.flagX+40+Math.random()*130;fireworks.push({kind:'rocket',x:center,y:214,vx:(Math.random()-.5)*.4,vy:-3.7-Math.random(),target:65+Math.random()*65,color:fireworkColors[Math.floor(Math.random()*fireworkColors.length)],life:65});}
function updateFireworks(){for(const f of fireworks){if(f.kind==='rocket'){f.x+=f.vx;f.y+=f.vy;f.life--;if(f.y<=f.target||f.life<=0){f.kind='spark';f.life=0;const count=28;for(let i=0;i<count;i++){const angle=i*Math.PI*2/count,speed=1.1+(i%4)*.3;fireworks.push({kind:'spark',x:f.x,y:f.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:32,size:i%5===0?3:2,color:i%3===0?'#fff7db':f.color});}audio.tone(190,.08,'triangle',.08,0,55);}}else{f.x+=f.vx;f.y+=f.vy;f.vx*=.985;f.vy+=.045;f.life--;}}fireworks=fireworks.filter(f=>f.life>0);}
function completeStage(){points(Math.floor(time)*10,player.x,player.y);if(stage===3){state='victory';try{localStorage.removeItem('pq-save');}catch{}modal('THE VALLEY IS SAFE AGAIN','YOU<span>DID IT!</span>','All four worlds cleared! Final score '+String(score).padStart(6,'0')+'. Thanks for playing.','PLAY AGAIN');}else{checkpoint=0;loadStage(stage+1);state='playing';$('#overlay').hidden=true;canvas.focus();}}
function updateExit(){finishTime++;player.inv=0;player.facing=1;if(finishTime%18===1&&exitPhase!=='sink')launchFirework();updateFireworks();if(exitPhase==='approach'){player.vx=1.8;player.vy=Math.min(player.vy+.25,6);moveBody(player,true);if(player.ground&&player.x>=world.exitX-48){exitPhase='hop';exitTick=0;player.vx=0;}}else if(exitPhase==='hop'){exitTick++;const t=Math.min(1,exitTick/38),foot=224-32*t-54*4*t*(1-t);player.x=world.exitX-40+48*t;player.y=foot-player.h;player.ground=false;if(t===1){exitPhase='sink';exitTick=0;player.ground=true;audio.sfx('power');}}else if(exitPhase==='sink'){exitTick++;player.x=world.exitX+8;player.y=192-player.h+exitTick*1.6;player.vx=0;if(exitTick>=36)completeStage();}camera=clamp(player.x-W*.37,0,world.length-W);pressed.clear();}
function bump(t){if(t.type==='hidden')t.type='question';if(t.type==='question'){t.type='used';t.bump=8;const content=t.content||'coin';if(content==='coin'){coin(t.x+8,t.y-6);particles.push({x:t.x+7,y:t.y-8,vx:0,vy:-3,c:'#ffd452',life:25,size:5});}else{const type=rewardFor(content);items.push({x:t.x,y:t.y-16,w:14,h:12,vx:type==='flower'?0:1,vy:0,type,age:0});audio.sfx('bump');}}else if(t.type==='brick'){t.bump=6;audio.sfx('bump');if(player.power){world.tiles.delete(t.x/T+','+t.y/T);burst(t.x+8,t.y+8,'#bf754a',12);points(50,t.x,t.y);}}for(const e of world.enemies)if(e.alive&&Math.abs(e.y+e.h-t.y)<4&&e.x+e.w>t.x&&e.x<t.x+t.w)killEnemy(e);}
function killEnemy(e){if(!e.alive)return;e.alive=false;e.timer=30;points(e.type==='boss'?2000:200,e.x,e.y);burst(e.x+7,e.y+6,e.type==='grub'?'#bd7548':'#83bb54');audio.sfx('stomp');}
function resizeHero(big){if(player.character!=='explorer')return;const center=player.x+player.w/2,feet=player.y+player.h;player.w=big?18:12;player.h=big?24:16;player.x=center-player.w/2;player.y=feet-player.h;}
function hurt(){if(player.inv>0||player.star>0||state!=='playing')return;if(player.power){player.power=player.character!=='explorer'?player.power-1:0;if(player.character==='soldier')player.weapon=player.power?'rifle':'none';resizeHero(false);player.inv=120;audio.sfx('hurt');save();}else die();}
function die(){if(player.dead)return;player.dead=1;player.vy=-5;player.vx=0;audio.sfx('death');lives--;save();}
function power(item){const valid={explorer:['mushroom','flower'],soldier:['weaponN','weaponL','weaponS'],mystic:['mysticOrb'],dora:['dorayaki'],goku:['dragonball'],nezha:['lotus']};if(item.type!=='star'&&!valid[player.character].includes(item.type))return;const index=items.indexOf(item);if(index>=0)items.splice(index,1);if(item.type==='star'){player.star=600;}else if(player.character==='soldier'){if(player.power===0||item.type==='weaponN'){player.power=Math.max(1,player.power);player.weapon=player.power===2?player.weapon:'rifle';}else{player.power=2;player.weapon=item.type==='weaponL'?'lightning':'spread';}popups.push({s:player.power===1?'NORMAL SHOT':player.weapon==='lightning'?'LIGHTNING':'SPREAD SHOT',x:player.x,y:player.y-15,life:85});}else{player.power=player.character==='explorer'?(item.type==='flower'?2:Math.max(1,player.power)):Math.min(2,player.power+1);resizeHero(true);if(player.character==='goku')popups.push({s:['NO ATTACK','KAMEHAMEHA','SUPER SAIYAN'][player.power],x:player.x,y:player.y-15,life:100});if(player.character==='dora')popups.push({s:['NO ATTACK','AIR CANNON','SUPER AIR CANNON'][player.power],x:player.x,y:player.y-15,life:85});if(player.character==='mystic')popups.push({s:['NO ATTACK','LIGHT WAVE','RETURN ARROW'][player.power],x:player.x,y:player.y-15,life:85});if(player.character==='nezha')popups.push({s:['NO ATTACK','UNIVERSE RING','RED ARMILLARY SASH'][player.power],x:player.x,y:player.y-15,life:95});}player.inv=60;points(1000,item.x,item.y);burst(item.x+8,item.y,'#ffdf62',15);audio.sfx('power');save();}
function update(){frame++;if(state!=='playing'){pressed.clear();return;}audio.update();for(const t of world.tiles.values())if(t.bump>0)t.bump--;if(player.dead){player.dead++;player.vy+=.2;player.y+=player.vy;if(player.dead>105){if(lives>0){loadStage(stage,true);}else{state='gameover';try{localStorage.removeItem('pq-save');}catch{}modal('EVERY HERO GETS ANOTHER CHANCE','GAME<span>OVER</span>','Score '+String(score).padStart(6,'0')+' · Your next adventure starts here.','TRY AGAIN');}}pressed.clear();return;}
 if(finishTime){updateExit();return;}
 time-=1/60;if(time<=0)die();player.inv=Math.max(0,player.inv-1);player.star=Math.max(0,player.star-1);player.fire=Math.max(0,player.fire-1);player.coyote=player.ground?7:Math.max(0,player.coyote-1);let left=keys.has('ArrowLeft')||keys.has('KeyA'),right=keys.has('ArrowRight')||keys.has('KeyD'),run=keys.has('ShiftLeft')||keys.has('ShiftRight');let dir=Number(right)-Number(left),speed=run?2.75:1.65;player.vx=dir?clamp(player.vx+dir*(player.ground?.19:.12),-speed,speed):player.vx*(player.ground?.78:.96);if(Math.abs(player.vx)<.02)player.vx=0;if(dir)player.facing=dir;if(player.ground)player.jumps=0;
 const highPressed=pressed.has('Space'),normalPressed=pressed.has('KeyK')||pressed.has('ArrowUp')||pressed.has('KeyW');
 if(highPressed&&player.coyote){player.buffer=8;player.bufferKind='high';player.bufferDouble=false;}else if(normalPressed){player.buffer=8;player.bufferKind='normal';player.bufferDouble=pressed.has('KeyK');}else player.buffer=Math.max(0,player.buffer-1);
 if(player.buffer&&(player.coyote||(player.bufferDouble&&player.jumps<2))){
  const grounded=player.coyote>0;
  player.jumps=grounded?1:Math.max(1,player.jumps)+1;
  player.jumpKind=player.bufferKind;player.vy=player.jumpKind==='high'&&grounded?-8:(run?-6.1:-5.7);
  if(!grounded)burst(player.x+player.w/2,player.y+player.h,'#d5f2ef',9);
  player.ground=false;player.jumpVisual=true;player.coyote=0;player.buffer=0;audio.sfx('jump');
 }
 const normalHeld=keys.has('KeyK')||keys.has('ArrowUp')||keys.has('KeyW');
 if(player.jumpKind==='normal'&&!normalHeld&&player.vy<-4.4)player.vy=-4.4;
 player.vy=Math.min(7,player.vy+.27);const oldBottom=player.y+player.h;moveBody(player,true);if(player.ground)player.jumpVisual=false;
 for(const b of shots)if(b.weapon==='arrow'&&b.life>0&&player.vy>=0&&oldBottom<=b.y+3&&player.y+player.h>=b.y&&player.y+player.h<=b.y+12&&player.x+player.w>b.x&&player.x<b.x+b.w){if(!b.anchored){b.anchored=true;b.life=301;b.vx=0;b.vy=0;popups.push({s:'ARROW PLATFORM · 5s',x:b.x,y:b.y-10,life:75});}player.y=b.y-player.h;player.vy=0;player.ground=true;player.jumps=0;}

 if(((player.character==='soldier'||player.character==='mystic'||player.character==='dora'||player.character==='goku'||player.character==='nezha')?player.power>0:player.power===2)&&(keys.has('KeyJ')||keys.has('KeyX')||pressed.has('KeyJ')||pressed.has('KeyX'))&&!player.fire){
 if(player.character==='soldier'){const weapon=player.power===1?'rifle':player.weapon,angles=weapon==='spread'?[-.24,-.12,0,.12,.24]:[0];player.fire=weapon==='spread'?25:weapon==='lightning'?17:16;for(const angle of angles)shots.push({x:player.x+player.w/2+player.facing*10,y:player.y+11,w:weapon==='lightning'?14:5,h:weapon==='lightning'?4:3,vx:player.facing*Math.cos(angle)*5.4,vy:Math.sin(angle)*5.4,life:80,weapon,hits:new Set()});burst(player.x+player.w/2+player.facing*14,player.y+12,weapon==='lightning'?'#94ecff':'#ffda72',3);audio.tone(weapon==='lightning'?1100:180,.07,'square',.22,0,80);}
 else if(player.character==='goku'){const superSaiyan=player.power===2;player.fire=superSaiyan?40:25;shots.push({x:player.x+player.w/2+player.facing*10,y:player.y+(superSaiyan?10:12),w:superSaiyan?42:22,h:superSaiyan?11:7,vx:player.facing*(superSaiyan?6:5.8),vy:0,life:80,weapon:superSaiyan?'superKame':'kame'});burst(player.x+player.w/2+player.facing*11,player.y+14,'#b4f9ff',8);audio.tone(superSaiyan?260:520,.2,'sawtooth',.2,0,100);}
 else if(player.character==='dora'){const superAir=player.power===2;player.fire=superAir?32:20;shots.push({x:player.x+player.w/2+player.facing*12,y:player.y+(superAir?7:10),w:superAir?24:12,h:superAir?14:8,vx:player.facing*(superAir?4.3:5.2),vy:0,life:95,weapon:superAir?'superAir':'air',damage:1,hits:new Set()});burst(player.x+player.w/2+player.facing*12,player.y+12,'#d6f8ff',6);audio.tone(superAir?120:220,.13,'triangle',.4,0,50);}
 else if(player.character==='mystic'){const arrow=player.power===2;if(!arrow||!shots.some(b=>b.weapon==='arrow')){player.fire=arrow?30:18;shots.push({x:player.x+player.w/2+player.facing*9,y:player.y+12,w:arrow?28:10,h:arrow?6:5,vx:player.facing*(arrow?2.4:4.8),originX:player.x+player.w/2+player.facing*9,direction:player.facing,vy:0,life:arrow?240:90,weapon:arrow?'arrow':'wave',age:0,returning:false,anchored:false,hits:new Set()});audio.tone(arrow?440:880,.12,'triangle',.3,0,180);}}
 else if(player.character==='nezha'){if(player.power===1){player.fire=22;shots.push({x:player.x+player.w/2+player.facing*9,y:player.y+8,w:12,h:12,vx:player.facing*5.3,vy:0,life:75,weapon:'qiankun',hits:new Set()});burst(player.x+player.w/2+player.facing*11,player.y+13,'#ffdc76',5);audio.tone(690,.13,'triangle',.3,0,1020);}else{player.fire=28;shots.push({x:player.x+(player.facing>0?player.w:-42),y:player.y+3,w:42,h:19,vx:0,vy:0,life:16,weapon:'ribbon',direction:player.facing,hits:new Set()});audio.tone(340,.2,'sawtooth',.18,0,180);}}
 else{player.fire=22;shots.push({x:player.x+player.w/2,y:player.y+player.h*.35,w:5,h:5,vx:player.facing*3.8,vy:1,life:130});audio.sfx('fire');}
 }

 for(const p of world.platforms){p.t++;let old=p.x;p.x=p.base+Math.sin(p.t/65)*p.range;p.vx=p.x-old;}
 for(let i=world.collect.length-1;i>=0;i--)if(overlap(player,world.collect[i])){const c=world.collect.splice(i,1)[0];coin(c.x,c.y);burst(c.x+4,c.y,'#ffe57b',4);}
 for(const it of [...items]){it.age++;if(it.type!=='flower'){it.vy=Math.min(it.vy+.24,6);moveBody(it);if(it.type==='star'&&it.ground)it.vy=-4;}if(it.age>12&&overlap(player,it))power(it);if(it.y>H+40)items.splice(items.indexOf(it),1);}
 for(const e of world.enemies){if(!e.alive||e.x>camera+W+40||e.x<camera-100)continue;if(e.type==='plant'){e.age++;if(Math.abs(player.x-e.x)<36&&!e.active)continue;const phase=e.age%240;const height=phase<60?0:phase<90?(phase-60)*.65:phase<165?20:phase<195?(195-phase)*.65:0;e.active=height>4;e.y=e.base-height;if(e.active&&overlap(player,e)){if(player.star)killEnemy(e);else hurt();}continue;}if(e.type==='boss'){e.timer++;e.vx=e.x<198*T?.55:e.x>206*T?-.55:e.vx;if(e.timer%130===0&&e.ground)e.vy=-3.6;if(e.timer%95===0)shots.push({x:e.x,y:e.y+10,w:7,h:7,vx:-2,vy:0,life:180,enemy:true});}e.vy=Math.min(e.vy+.25,6);moveBody(e);if(e.y>H+30)e.alive=false;if(e.shell&&!e.kicked&&e.timer>0){e.timer--;if(!e.timer){e.shell=false;e.h=16;e.y-=7;e.vx=-.5;}}if(e.kicked)for(const other of world.enemies)if(other!==e&&other.alive&&overlap(e,other)){if(other.type==='boss'){other.hp--;e.kicked=false;e.vx=0;if(other.hp<=0)killEnemy(other);}else killEnemy(other);}if(!overlap(player,e))continue;if(player.star){killEnemy(e);continue;}if(e.shell&&!e.kicked){e.kicked=true;e.vx=player.x<e.x?4:-4;player.inv=15;audio.sfx('stomp');continue;}if(player.vy>=0&&oldBottom<=e.y+6){player.y=e.y-player.h;player.vy=-4;audio.sfx('stomp');if(e.type==='boss'){e.hp--;e.x+=20;player.inv=35;points(200,e.x,e.y);if(e.hp<=0)killEnemy(e);}else if(e.type==='turtle'){if(e.shell&&e.kicked){e.kicked=false;e.vx=0;e.timer=450;}else{e.shell=true;e.kicked=false;e.h=9;e.y+=7;e.vx=0;e.timer=450;points(100,e.x,e.y);}}else killEnemy(e);}else hurt();}
 for(let i=shots.length-1;i>=0;i--){const b=shots[i];b.life--;if(b.weapon==='ribbon'){b.x=player.x+(b.direction>0?player.w:-b.w);b.y=player.y+3;}if(b.weapon==='arrow'&&!b.anchored){b.age++;if(b.age>=35)b.returning=true;if(b.returning){b.vx=-(b.direction||1)*2.4;b.vy=0;if((b.x-b.originX)*(b.direction||1)<=0){shots.splice(i,1);continue;}}}b.x+=b.vx;b.y+=b.vy;if(!b.enemy){if(!b.weapon)b.vy+=.18;for(const t of (b.weapon==='ribbon'?[]:solids(b).filter(t=>t.type!=='hidden'))){if(!overlap(b,t))continue;if(b.weapon==='arrow'){if(!b.anchored)b.returning=true;continue;}if(!b.weapon&&b.vy>0&&b.y+b.h-t.y<8){b.y=t.y-b.h;b.vy=-2.5;}else b.life=0;}if(b.life>0)for(const e of world.enemies)if(e.alive&&(e.type!=='plant'||e.active)&&overlap(b,e)&&!b.hits?.has(e)){if(b.weapon==='ribbon'){const damage=b.hits.size===0?1:.5;e.hp=(e.hp??(e.type==='boss'?5:1))-damage;b.hits.add(e);if(e.hp<=0)killEnemy(e);else{e.x+=b.direction*6;popups.push({s:'50% HIT',x:e.x,y:e.y-4,life:40});}burst(e.x,e.y,'#f88aa1',6);if(b.hits.size>=2){b.life=0;break;}continue;}if(b.weapon==='superAir'){const damage=b.damage??1;e.hp=(e.hp??(e.type==='boss'?5:1))-damage;if(e.hp<=0){killEnemy(e);b.damage=damage*.5;}else{e.x+=Math.sign(b.vx)*10;e.vy=-1.5;popups.push({s:damage<1?'50% HIT':'HIT',x:e.x,y:e.y-4,life:40});}b.hits.add(e);burst(e.x,e.y,'#c6f0ff',5);if(b.hits.size>=2){b.life=0;break;}continue;}if(e.type==='boss'){e.hp-=b.weapon==='superKame'?2:1;if(e.hp<=0)killEnemy(e);}else killEnemy(e);if((b.weapon==='lightning'||b.weapon==='arrow')){b.hits.add(e);burst(e.x,e.y,'#9beaff',6);}else{b.life=0;break;}}}else if(overlap(player,b)){hurt();b.life=0;}if(b.life<=0||b.y>H+20||b.y<0||Math.abs(b.x-player.x)>600){burst(b.x,b.y,b.weapon==='lightning'?'#9beaff':'#ffbd57',3);shots.splice(i,1);}}

 if(player.y>H+20)die();if(!checkpoint&&player.x>world.checkpointX){checkpoint=world.checkpointX;popups.push({s:'CHECKPOINT',x:player.x,y:player.y-15,life:120});audio.sfx('life');save();}
 if(player.x+player.w>world.flagX&&!(stage===3&&world.enemies.some(e=>e.type==='boss'&&e.alive))){finishTime=1;exitPhase='approach';exitTick=0;score+=player.y<100?5000:player.y<160?2000:1000;audio.sfx('win');burst(player.x,player.y,'#ffe983',30);launchFirework();}
 camera=clamp(player.x-W*.37,0,world.length-W);pressed.clear();for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.12;p.life--;}particles=particles.filter(p=>p.life>0);for(const p of popups){p.y-=.3;p.life--;}popups=popups.filter(p=>p.life>0);}
function cloud(x,y,s=1){rect(x+8*s,y,24*s,6*s,'#eaf8ef');rect(x,y+6*s,44*s,10*s,'#eaf8ef');rect(x+5*s,y+16*s,35*s,4*s,'#c5e9e5');}
function hill(x,y,w,h,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w*.12,y-h*.2);ctx.lineTo(x+w*.38,y-h*.9);ctx.lineTo(x+w*.5,y-h);ctx.lineTo(x+w*.62,y-h*.9);ctx.lineTo(x+w*.88,y-h*.2);ctx.lineTo(x+w,y);ctx.fill();}
function background(){const th=world.theme;rect(0,0,W,H,th.sky);if(stage===0||stage===2){for(let i=-1;i<8;i++){let x=i*125-(camera*.16)%125;cloud(x,stage===2?60+(i%3)*24:47+(i%3)*13,stage===2?1.3:1);}if(stage===0){rect(390-camera*.05,48,24,24,'#ffea9a');for(let i=-1;i<7;i++){let x=i*170-(camera*.25)%170;hill(x,224,160,55+(i%2)*22,th.far);hill(x+55,224,120,43,th.hills);rect(x+82,205,3,7,'#348e7e');rect(x+99,205,3,7,'#348e7e');}}else{for(let i=-1;i<6;i++)cloud(i*180-(camera*.3)%180,202,3);}}else{if(stage===1){for(let i=0;i<35;i++){let x=(i*79-camera*.15)%500;if(x<0)x+=500;rect(x,50+(i*31)%150,1,2,'#80b4cb');}for(let i=-1;i<10;i++){const x=i*70-(camera*.3)%70;hill(x,224,64,45+(i%3)*10,th.hills);ctx.fillStyle='#6bc2c966';ctx.beginPath();ctx.moveTo(x+20,222);ctx.lineTo(x+26,179);ctx.lineTo(x+33,205);ctx.lineTo(x+36,223);ctx.fill();rect(x+26,188,2,23,'#9de1df');}}else{for(let i=-1;i<9;i++){let x=i*80-(camera*.23)%80;rect(x,70,52,154,th.hills);rect(x-4,68,12,8,th.hills);rect(x+20,68,12,8,th.hills);rect(x+43,68,12,8,th.hills);rect(x+19,96,14,24,'#241f31');rect(x+20,98,12,21,'#f8ac4933');}for(let i=0;i<20;i++)rect((i*61-frame*.15)%480,80+(i*37+frame*.35)%145,2,2,'#e88e50');}}
}
function drawTile(t){if(t.type==='hidden')return;let x=t.x-camera,y=t.y-(t.bump?Math.sin(t.bump/8*Math.PI)*4:0),th=world.theme;if(t.type==='ground'){rect(x,y,16,16,th.ground);if(!solidAt(t.x,t.y-1)){rect(x,y,16,3,th.grass);rect(x,y+3,16,2,th.edge);for(let i=0;i<4;i++)rect(x+i*4,y+3+(i%2),2,3,th.grass);}rect(x+1,y+7,5,2,th.edge);rect(x+9,y+12,4,2,th.dark);rect(x+4,y+14,2,2,th.dark);}else if(t.type==='brick'){rect(x,y,16,16,stage===1?'#5289a4':'#c8794b');rect(x,y,16,1,'#e3aa71');rect(x,y+7,16,1,th.dark);rect(x,y+15,16,1,th.dark);rect(x+7,y,1,7,th.dark);rect(x+3,y+8,1,7,th.dark);rect(x+12,y+8,1,7,th.dark);}else if(t.type==='question'){rect(x,y,16,16,'#9a5f29');rect(x+1,y+1,14,13,'#f8bc46');rect(x+2,y+2,12,1,'#ffe48a');rect(x+2,y+2,1,11,'#ffdc6f');rect(x+13,y+3,1,10,'#d88a32');text('?',x+8,y+12,12,'#fff2b4','center');rect(x+2,y+12,1,1,'#865725');rect(x+12,y+12,1,1,'#865725');}else if(t.type==='used'){rect(x,y,16,16,'#99704a');rect(x+1,y+1,14,14,'#b18a60');rect(x+2,y+2,1,1,'#715033');rect(x+12,y+12,1,1,'#715033');}else if(t.type==='pipe'||t.type==='pipeTop'){rect(x,y,16,16,'#2e7548');rect(x+2,y,3,16,'#9ad762');rect(x+5,y,6,16,'#65b34c');rect(x+12,y,2,16,'#1d5c3f');if(t.type==='pipeTop'){rect(x,y,16,2,'#b1e978');rect(x,y+10,16,2,'#1d5c3f');}}else if(t.type==='cloud'){rect(x,y+2,16,12,'#fff4dc');rect(x+2,y,12,2,'#fff4dc');rect(x,y+12,16,4,'#c2dbe0');rect(x+3,y+6,2,2,'#6e9ba6');rect(x+11,y+6,2,2,'#6e9ba6');}else{rect(x,y,16,16,th.dark);rect(x+1,y+1,14,14,th.ground);rect(x+2,y+2,12,2,th.edge);rect(x+2,y+4,2,9,th.edge);rect(x+4,y+13,10,1,th.dark);}}
function drawCoin(x,y){let w=[6,4,2,4][Math.floor(frame/8)%4];rect(x+4-w/2,y,w,10,'#b67629');rect(x+5-w/2,y,w-1,8,'#ffdc5b');if(w>2)rect(x+4-w/2,y+2,1,5,'#fff4a2');}
function drawPickup(it){const x=it.x-camera,y=it.y;if(it.type.startsWith('weapon')){const letter=it.type.slice(-1),color=letter==='N'?'#ff5c57':letter==='L'?'#70d9ff':'#ffce61';rect(x-1,y-1,16,14,'#223044');rect(x,y,14,12,color);rect(x+2,y+2,10,8,'#27374b');text(letter,x+7,y+10,9,'#fff8df','center');rect(x+2,y-2,10,1,'#fff4cf');}else if(it.type==='dorayaki')sprite('dorayaki',x,y,false,1,{D:'#965129',T:'#d88a45',S:'#ffe7a4'});else if(it.type==='dragonball')sprite('dragonball',x,y,false,1,{Y:'#ffc246',R:'#d35531'});else if(it.type==='mysticOrb')sprite('mysticOrb',x,y,false,1,{B:'#147ac1',W:'#c2f3ff',K:'#2753a9'});else if(it.type==='lotus')sprite('lotus',x,y,false,1,{P:'#e989ad',Y:'#ffcc6c',W:'#fff9dd',G:'#64ba72'});else sprite(it.type,x,y);}
function castle(x){rect(x,176,64,48,stage===3?'#9b8191':'#d3b792');rect(x-4,166,20,58,stage===3?'#9b8191':'#d3b792');rect(x+48,166,20,58,stage===3?'#9b8191':'#d3b792');for(let i=0;i<5;i++)rect(x-4+i*15,160,10,8,'#e9cf9f');rect(x+25,202,14,22,'#473844');rect(x+25,199,14,5,'#473844');rect(x+4,183,6,11,'#473844');rect(x+54,183,6,11,'#473844');for(let y=179;y<224;y+=9)rect(x,y,64,1,'#79695755');}
function drawExitPipe(front=false){const x=world.exitX-camera;if(x<-40||x>W+40)return;if(!front){rect(x+3,190,30,34,'#2d7947');rect(x+7,194,5,30,'#a7dc69');rect(x+14,194,5,30,'#65b750');rect(x+27,194,3,30,'#195839');rect(x+3,190,30,4,'#173c32');}else{rect(x,190,36,4,'#b8ea7b');rect(x,194,36,5,'#3e914c');rect(x+2,194,3,5,'#d0f099');rect(x+31,194,3,5,'#23613b');if(exitPhase==='sink')rect(x+2,200,32,24,'#39834a99');}}
function drawNimbus(x,y){rect(x-11,y-3,23,4,'#f8d554');rect(x-15,y,31,5,'#ffdc58');rect(x-8,y+5,19,3,'#e9a72e');rect(x-4,y-5,8,2,'#fff2a8');}
function drawWindFireWheels(x,y){for(const ox of [x-3,x+player.w-6]){rect(ox,y-5,6,6,'#f1a52e');rect(ox+1,y-4,4,4,'#fff095');rect(ox+2,y-7,2,3,'#fb5239');rect(ox-1,y-2,2,3,'#f06628');}}function drawBambooRotor(x,y){rect(x-2,y-3,5,2,'#d48d28');rect(x,y-8,2,6,'#ffe37a');const span=[10,6,2,6][Math.floor(frame/3)%4];rect(x-span,y-10,span*2+2,2,'#a47224');rect(x-span+1,y-10,span*2,1,'#fff0a3');rect(x-1,y-11,4,3,'#ffcd49');}
function drawBoss(e){let x=e.x-camera,y=e.y;rect(x+6,y+5,20,23,'#719249');rect(x+4,y+10,25,16,'#415d3c');for(let a=0;a<4;a++){rect(x+7+a*5,y+4,3,6,'#f0d4a0');rect(x+7+a*5,y+22,3,7,'#f0d4a0');}rect(x,y+2,14,15,'#d69748');rect(x+2,y,9,3,'#e4ad5a');rect(x+1,y+5,4,5,'#fff4d5');rect(x+1,y+7,2,2,'#312b38');rect(x-3,y+12,13,4,'#ecbe72');rect(x+7,y+26,8,6,'#d69748');rect(x+22,y+26,8,6,'#d69748');for(let i=0;i<5;i++)rect(x+i*6,y-8,4,2,i<e.hp?'#ffcd62':'#684959');}
function draw(){ctx.setTransform(2,0,0,2,0,0);background();castle(world.flagX+48-camera);drawExitPipe();const fx=world.flagX-camera;rect(fx+5,67,2,157,'#ffefce');rect(fx+3,63,6,6,'#ffdf63');const fy=finishTime?Math.min(206,78+finishTime*1.3):78;rect(fx-18,fy,23,14,'#fff2c5');rect(fx-17,fy+2,20,10,'#ed7160');text('★',fx-7,fy+10,8,'#fff4d5','center');
 if(stage===3){rect(0,224,W,46,'#cb513c');for(let i=0;i<60;i++)rect(i*10-(frame/4)%10,225,7,3,'#ffb04b');}for(const t of world.tiles.values())if(t.x+16>camera&&t.x<camera+W)drawTile(t);for(const p of world.platforms){rect(p.x-camera,p.y,p.w,8,'#d7aa69');rect(p.x-camera,p.y,p.w,2,'#ffe3ad');for(let x=2;x<p.w;x+=8)rect(p.x-camera+x,p.y+3,1,4,'#8d5d3e');}for(const c of world.collect)if(c.x>camera-10&&c.x<camera+W)drawCoin(c.x-camera,c.y);for(const it of items)drawPickup(it);for(const e of world.enemies){if(!e.alive||e.x<camera-32||e.x>camera+W)continue;if(e.type==='plant'){if(e.active){const x=e.x-camera,y=e.y;rect(x+6,y+9,4,e.base-y-9,'#74b850');rect(x+2,y+14,5,3,'#91ce60');rect(x+10,y+16,5,3,'#91ce60');rect(x+2,y,12,10,'#e96252');rect(x,y+2,16,6,'#e96252');rect(x+3,y+2,3,2,'#ffe9ba');rect(x+10,y+5,3,2,'#ffe9ba');rect(x+1,y,14,2,'#fff2d1');}}else if(e.type==='boss')drawBoss(e);else if(e.shell){rect(e.x-camera+2,e.y,10,3,'#aad06d');rect(e.x-camera,e.y+3,14,5,'#568943');rect(e.x-camera+2,e.y+8,10,1,'#ffd596');}else{sprite(e.type,e.x-camera,e.y,e.vx>0);if(e.type==='grub'&&Math.floor(frame/10)%2)rect(e.x-camera+2,e.y+11,3,1,'#a55b37');}}
 if(!(player.inv>0&&Math.floor(frame/5)%2)){const colors=player.star>0?{R:['#fbe458','#71dabc','#e7a8e5'][Math.floor(frame/5)%3],B:'#faf2ce'}:player.power===2?{R:'#fff1d4',B:'#df6745'}:{};const name=!player.ground?'jump':Math.abs(player.vx)>.2&&Math.floor(frame/6)%2?'walk':'hero';if(player.character==='goku'){const x=player.x-camera,superSaiyan=player.power===2;if(!player.ground&&player.jumpVisual&&!player.dead)drawNimbus(x+player.w/2,player.y+player.h,player.facing);if(superSaiyan){for(let i=0;i<4;i++){const y=player.y+((frame*2+i*7)%26);rect(x-4,y,2,4,'#ffe589');rect(x+player.w+2,y-2,2,4,'#ffcb45');}}sprite(player.fire>0?'gokuShoot':Math.abs(player.vx)>.2&&Math.floor(frame/6)%2?'gokuWalk':'goku',x-5,player.y,player.facing<0,1,superSaiyan?{...gokuColors,A:'#ffd13d',Q:'#fff2a1'}:gokuColors);}else if(player.character==='nezha'){const x=player.x-camera;if(!player.ground&&player.jumpVisual&&!player.dead)drawWindFireWheels(x,player.y+player.h);sprite(Math.abs(player.vx)>.2&&Math.floor(frame/6)%2?'nezhaWalk':'nezha',x-4,player.y,player.facing<0,1,nezhaColors);}else if(player.character==='dora'){const pose=player.ground&&Math.abs(player.vx)>.2&&Math.floor(frame/6)%2?'doraWalk':'dora';sprite(pose,player.x-camera-3,player.y,player.facing<0,1,doraColors);if(player.power>0){const x=player.x-camera+player.w/2+(player.facing>0?9:-14);rect(x,player.y+12,7,5,'#657c90');rect(x+1,player.y+12,5,1,'#bed3df');rect(x+(player.facing>0?5:0),player.y+13,2,3,'#233f54');}if(!player.ground&&!player.dead)drawBambooRotor(player.x-camera+player.w/2,player.y);}else if(player.character==='mystic'){sprite(!player.ground?'mysticJump':Math.abs(player.vx)>.2&&Math.floor(frame/6)%2?'mysticWalk':'mystic',player.x-camera-3,player.y,player.facing<0,1,mysticColors);}else if(player.character==='soldier'){const pose=!player.ground?'soldierJump':Math.abs(player.vx)>.2&&Math.floor(frame/6)%2?'soldierWalk':'soldier';sprite(pose,player.x-camera-5,player.y,player.facing<0,1,player.star>0?{...soldierColors,B:colors.R}:soldierColors);}else{const scale=player.power?1.5:1;sprite(name,player.x-camera-2*scale,player.y,player.facing<0,scale,colors);}}
 drawExitPipe(true);for(const b of shots){if(b.weapon==='qiankun'){const x=b.x-camera,y=b.y;rect(x+2,y,8,2,'#ffe27b');rect(x,y+2,2,8,'#e69b31');rect(x+10,y+2,2,8,'#e69b31');rect(x+2,y+10,8,2,'#f6b13d');rect(x+3,y+1,6,1,'#fff4bf');rect(x+10,y+3,1,5,'#fff2a1');}else if(b.weapon==='ribbon'){const x=b.x-camera,y=b.y;for(let i=0;i<8;i++){const px=x+i*5,py=y+7+Math.round(Math.sin(i*.9+frame*.45)*5);rect(px,py,7,5,i%2?'#f64b67':'#e92c4b');rect(px+1,py,5,2,'#ff9fb1');if(i===7)rect(px+5,py-2,3,9,'#ffd189');}}else if(b.weapon==='kame'||b.weapon==='superKame'){const x=b.x-camera,y=b.y;rect(x,y+1,b.w,b.h-2,'#3ebdf7');rect(x+3,y,b.w-6,b.h,'#87e6ff');rect(x+2,y+2,b.w-4,b.h-4,'#f0ffff');rect(x-(b.vx>0?4:-b.w),y+2,4,b.h-4,'#b9f5ff');}else if(b.weapon==='air'||b.weapon==='superAir'){const x=b.x-camera,y=b.y,c=b.weapon==='superAir'?(b.damage<1?'#99cbdc':'#e7fcff'):'#c0eef8';rect(x+2,y,b.w-4,2,c);rect(x+2,y+b.h-2,b.w-4,2,c);rect(x,y+2,2,b.h-4,c);rect(x+b.w-2,y+2,2,b.h-4,c);rect(x+5,y+3,b.w-10,Math.max(2,b.h-6),'#80d3f0');rect(x-3*Math.sign(b.vx),y+2,2,b.h-4,'#dcf7ff');}else if(b.weapon==='arrow'){const x=b.x-camera,y=b.y;rect(x,y+2,b.w-6,2,'#ff9e36');rect(x+2,y+1,b.w-9,1,'#ffd76b');const tip=b.vx<0?x:x+b.w-6;rect(tip,y,3,6,'#ff8b2d');rect(tip+(b.vx<0?-2:3),y+1,3,4,'#ffba4f');if(b.anchored)text(Math.ceil(b.life/60)+'s',x+b.w/2,y-4,6,'#ffe3a3','center');}else if(b.weapon==='wave'){rect(b.x-camera,b.y,10,5,'#75deef');rect(b.x-camera+2,b.y+1,7,3,'#e8ffff');}else if(b.weapon==='lightning'){rect(b.x-camera,b.y,14,4,'#207cf3');for(let i=0;i<7;i++)rect(b.x-camera+i*2,b.y+(i+frame)%2,3,2,'#c2f9ff');}else{rect(b.x-camera,b.y,b.w,b.h,b.weapon==='spread'?'#f99b62':'#fbd362');rect(b.x-camera+1,b.y+1,b.w-2,Math.max(1,b.h-2),b.weapon?'#fff4d7':Math.floor(frame/4)%2?'#f35e38':'#fff2bf');}}for(const f of fireworks){const x=f.x-camera,y=f.y;if(f.kind==='rocket'){rect(x,y,2,5,'#fff7cb');rect(x,y+5,2,3,f.color);}else if(f.life>2){rect(x,y,f.size,f.size,f.color);if(f.life>19)rect(x+f.vx*2,y+f.vy*2,1,1,'#fff9dc');}}for(const p of particles)rect(p.x-camera,p.y,p.size,p.size,p.c);for(const p of popups)text(p.s,p.x-camera,p.y,8,'#fff4d5','center');
const cp=world.checkpointX-camera;if(cp>-16&&cp<W){rect(cp,201,2,23,'#f9e1aa');rect(cp+2,201,12,8,checkpoint?'#ffc64f':'#eae6d5');rect(cp+4,203,2,4,checkpoint?'#996524':'#a7b4b2');}rect(0,0,W,31,'#142d3dce');text(player.character==='soldier'?'COMMANDO':player.character==='mystic'?'MYSTIC':player.character==='dora'?'DORAEMON':player.character==='goku'?'SON GOKU':player.character==='nezha'?'NEZHA':'PIXEL',16,12,7,'#ffc956');text(String(score).padStart(6,'0'),16,24,9);drawCoin(111,12);text('× '+String(coins).padStart(2,'0'),123,22,9);text('WORLD',218,12,7,'#bdd6d9');text((stage+1)+'–1',221,24,9);text('LIVES',318,12,7,'#bdd6d9');text('♥ × '+lives,318,24,9);text('TIME',438,12,7,'#bdd6d9','right');text(String(Math.ceil(time)).padStart(3,'0'),438,24,9,time<60?'#ff957a':'#fff4d6','right');if(player.character==='nezha')text('LV'+(player.power+1)+' '+['NO ATTACK','QIANKUN RING · J','RED SASH · J'][player.power],16,43,6,'#ffcc88');else if(player.character==='goku')text('LV'+(player.power+1)+' '+['NO ATTACK','KAMEHAMEHA · J','SUPER SAIYAN · J'][player.power],16,43,6,player.power===2?'#ffdf76':'#bcf0ff');else if(player.character==='dora')text('LV'+(player.power+1)+' '+['NO ATTACK','AIR CANNON · J','SUPER AIR CANNON · J'][player.power],16,43,6,'#bdefff');else if(player.character==='mystic')text('LV'+(player.power+1)+' '+['NO ATTACK','LIGHT WAVE · J','RETURN ARROW · J'][player.power],16,43,6,'#ffd497');else if(player.character==='soldier')text('LV'+(player.power+1)+' '+(player.power===0?'NO ATTACK · FIND N':player.power===1?'NORMAL SHOT · J':player.weapon==='lightning'?'LIGHTNING · J':'SPREAD SHOT · J'),16,43,6,player.weapon==='lightning'?'#9beaff':'#fff4d6');else if(player.power===2)text('FIRE READY · J',16,43,6,'#fff4d6');if(player.star>0)text('★ INVINCIBLE',16,43,6,'#ffe477');if(state==='playing'&&player.x<170&&stage===0&&frame<650){text('K JUMP / DOUBLE · SPACE HIGH · J FIRE',240,253,7,'#fff5d8','center');}ctx.setTransform(1,0,0,1,0,0);}
function loop(now){let dt=Math.min((now-last)/1000,.1);last=now;acc+=dt;let steps=0;while(acc>=1/60&&steps++<6){update();acc-=1/60;}draw();requestAnimationFrame(loop);}
loadStage(0); // A live scene behind the start screen.
requestAnimationFrame(loop);
// A small, read-only inspection surface for browser acceptance and bug reports.
window.PixelQuest={get state(){return state;},get snapshot(){return {state,stage,score,coins,lives,time,player:{...player},camera,enemies:world.enemies.filter(e=>e.alive).length,checkpoint};}};
