/* Local Gomoku victory records. Never changes board rules or AI decisions. */
(()=>{'use strict';
const KEY='pq-gomoku-ranking-v1',NAME='pq-gomoku-nickname', $=id=>document.getElementById(id);
const clean=value=>String(value??'').normalize('NFKC').replace(/[^A-Za-z0-9一-鿿]/gu,'').slice(0,12);
const valid=value=>/^[A-Za-z0-9一-鿿]{2,12}$/u.test(value);
const eligible=c=>c.mode==='ai'&&['hard','expert'].includes(c.difficulty);
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
function rows(){const data=read(KEY,[]);return (Array.isArray(data)?data:[]).filter(r=>r&&typeof r.id==='string'&&valid(r.nickname)&&['hard','expert'].includes(r.difficulty)&&Number.isInteger(r.stones)&&r.stones>=5&&r.stones<=113&&Number.isInteger(r.total)&&r.total>=9&&r.total<=225&&Number.isFinite(Date.parse(r.date)))}
function beijing(date){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date(date))}
const label=document.createElement('label');label.id='gk-nickname-label';label.innerHTML='排行榜昵称<input id="gk-nickname" maxlength="12" autocomplete="nickname" placeholder="2～12 个中文、英文或数字"><small>困难 / 专家挑战必须填写；获胜后记录成绩。</small>';$('color-label').after(label);
$('gk-nickname').value=clean(read(NAME,''));$('gk-nickname').addEventListener('input',()=>{$('gk-nickname').value=clean($('gk-nickname').value);$('gk-nickname').setCustomValidity('')});
const button=document.createElement('button');button.id='gk-open-ranking';button.textContent='排行榜 / LEADERBOARD';$('rematch').after(button);
const note=document.createElement('p');note.id='gk-record-note';note.setAttribute('aria-live','polite');$('result-note').after(note);
const dialog=document.createElement('dialog');dialog.id='gk-ranking';dialog.innerHTML='<div class="gk-title"><div><p class="eyebrow">GOMOKU / LEADERBOARD</p><h2>五子棋排行榜</h2></div><button id="gk-close" aria-label="关闭排行榜">✕</button></div><label>挑战难度 <select id="gk-tier"><option value="hard">困难 HARD</option><option value="expert">专家 EXPERT</option></select></label><p class="gk-caption">本机排行 · 仅当前浏览器 · 只记录战胜 AI 的成绩</p><p class="gk-caption">按玩家棋子数升序，同数按获胜时间先后；每个昵称保留最佳成绩。棋子数为获胜时玩家留在棋盘上的棋子，不是五连的 5 颗。</p><div class="gk-table"><table><thead><tr><th>名次</th><th>昵称</th><th>玩家棋子</th><th>总落子</th><th>北京时间</th><th>悔棋</th></tr></thead><tbody id="gk-rows"></tbody></table></div><p id="gk-empty">暂无成绩，战胜困难或专家 AI 后会在这里显示。</p><button id="gk-more" hidden>显示 TOP 100</button>';
document.body.append(dialog);let recorded=false,current=null,limit=20;
function sorted(tier){const best=new Map();for(const r of rows().filter(r=>r.difficulty===tier).sort((a,b)=>a.stones-b.stones||Date.parse(a.date)-Date.parse(b.date)||a.id.localeCompare(b.id))){const key=r.nickname.toLowerCase();if(!best.has(key))best.set(key,r)}return [...best.values()].slice(0,100)}
function render(){const list=sorted($('gk-tier').value);$('gk-rows').replaceChildren();for(const [i,r] of list.slice(0,limit).entries()){const tr=document.createElement('tr');if(r.nickname.toLowerCase()===clean(current?.nickname||$('gk-nickname').value).toLowerCase())tr.className='gk-current';for(const value of [i+1,r.nickname,r.stones,r.total,beijing(r.date),r.undo?'允许':'关闭']){const td=document.createElement('td');td.textContent=String(value);tr.append(td)}$('gk-rows').append(tr)}$('gk-empty').hidden=!!list.length;$('gk-more').hidden=list.length<=limit}
function open(){const c=window.PixelGomoku?.config;if(eligible(c||{}))$('gk-tier').value=c.difficulty;limit=20;render();dialog.showModal()}
button.onclick=open;$('gk-close').onclick=()=>dialog.close();$('gk-tier').onchange=()=>{limit=20;render()};$('gk-more').onclick=()=>{limit=100;render()};
window.GomokuRanking={options(c){const needed=eligible(c);label.hidden=!needed;$('gk-nickname').required=needed},begin(c){if(eligible(c)){const nickname=clean(c.nickname??$('gk-nickname').value);if(!valid(nickname)){$('gk-nickname').setCustomValidity('请输入 2～12 个中文、英文或数字');if(!$('setup').open)$('setup').showModal();label.hidden=false;$('gk-nickname').reportValidity();return null}c={...c,nickname};$('gk-nickname').value=nickname;$('gk-nickname').setCustomValidity('');save(NAME,nickname)}recorded=false;current=null;note.textContent='';return c},finish(match,c){if(recorded||!match.finished)return;recorded=true;if(!eligible(c)||match.winner!==c.human)return;const record={id:crypto.randomUUID(),nickname:c.nickname,difficulty:c.difficulty,stones:match.history.filter(m=>m.color===c.human).length,total:match.history.length,date:new Date().toISOString(),undo:!!c.undo};current=record;const all=rows();all.push(record);const saved=save(KEY,all.sort((a,b)=>a.stones-b.stones||Date.parse(a.date)-Date.parse(b.date)).slice(0,2000));const rank=sorted(c.difficulty).findIndex(r=>r.nickname.toLowerCase()===record.nickname.toLowerCase())+1;note.textContent=saved?`${record.nickname} · ${record.stones} 颗棋子战胜 AI · ${beijing(record.date)}（北京时间） · ${rank>0?'昵称最佳排名 #'+rank:'TOP 100 之外'}`:'浏览器无法保存成绩，请允许本地存储后重试。'},open,beijing,sorted};
})();
