/* Gomoku UI, direct board input and worker lifecycle, isolated from the collection. */
(()=>{'use strict';const $=id=>document.getElementById(id),match=new GomokuCore.Match(),canvas=$('board'),ctx=canvas.getContext('2d'),PAD=52,STEP=44,notes={easy:'简单：就近随机落子，仍会完成五连和防住眼前的五连。',normal:'普通：识别活三与冲四，兼顾进攻和防守。',hard:'困难：识别双三、双四，候选搜索深入三层。',expert:'专家：威胁评估与 Alpha-Beta 搜索，最多深入五层。'},names={easy:'EASY / 简单',normal:'NORMAL / 普通',hard:'HARD / 困难',expert:'EXPERT / 专家'};
let config={mode:'ai',difficulty:'normal',human:1,undo:true},worker=null,job=0,thinking=false,hover=null,pointer=null,lastTap=0,keyCell={x:7,y:7},started=false,sound=true,audio=null,lastSearch=null;
function tone(win=false){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(win?660:370,audio.currentTime);o.frequency.exponentialRampToValueAtTime(win?880:180,audio.currentTime+.11);g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.14);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.15)}catch{}}
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function stone(x,y,color,alpha=1){ctx.save();ctx.globalAlpha=alpha;const dark=color===1;for(let yy=-18;yy<=18;yy+=2){const w=Math.floor(Math.sqrt(18*18-yy*yy));rect(x-w,y+yy,w*2,2,dark?'#182127':'#eee6d4')}for(let yy=-15;yy<=15;yy+=2){const w=Math.floor(Math.sqrt(15*15-yy*yy));rect(x-w,y+yy-1,w*2,2,dark?'#27343b':'#fff6e4')}rect(x-7,y-10,7,3,dark?'#526069':'#ffffff');ctx.restore()}
function draw(){ctx.imageSmoothingEnabled=false;rect(0,0,720,720,'#c7a16b');for(let y=8;y<720;y+=12){rect(12,y,696,1,y%24?'#bc9661':'#d0ad77');for(let x=(y*7)%100;x<700;x+=128)rect(x+9,y+4,44,1,'#c19a65')}rect(18,18,684,4,'#e5c392');rect(18,18,4,684,'#e5c392');rect(18,698,684,4,'#927044');rect(698,18,4,684,'#927044');for(let i=0;i<15;i++){rect(PAD+i*STEP,PAD,2,STEP*14+2,'#614b34');rect(PAD,PAD+i*STEP,STEP*14+2,2,'#614b34')}for(const x of [3,7,11])for(const y of [3,7,11]){if(x===7&&y!==7||y===7&&x!==7)continue;rect(PAD+x*STEP-4,PAD+y*STEP-4,9,9,'#614b34')}
 for(let i=0;i<225;i++)if(match.board[i])stone(PAD+i%15*STEP,PAD+Math.floor(i/15)*STEP,match.board[i]);
 if(hover&&!match.finished&&!thinking&&!match.board[hover.y*15+hover.x]){stone(PAD+hover.x*STEP,PAD+hover.y*STEP,match.turn,.38);rect(PAD+hover.x*STEP-3,PAD+hover.y*STEP-3,6,6,'#dc9b36')}
 const last=match.history.at(-1);if(last)rect(PAD+last.x*STEP-3,PAD+last.y*STEP-3,6,6,'#df9d34');
 if(match.winning.length){for(const i of match.winning){const x=PAD+i%15*STEP,y=PAD+Math.floor(i/15)*STEP;ctx.strokeStyle='#a54827';ctx.lineWidth=3;ctx.strokeRect(x-22,y-22,44,44);rect(x-3,y-3,6,6,'#f3ba47')}}
}
function canPlay(){return started&&!match.finished&&!thinking&&(config.mode==='local'||match.turn===config.human)&&!$('setup').open}
function undoCount(){if(config.mode==='local')return match.history.length?1:0;const lastHuman=match.history.findLastIndex(m=>m.color===config.human);return lastHuman<0?0:match.history.length-lastHuman}
function sync(){const who=match.turn===1?'BLACK / 黑方':'WHITE / 白方';$('turn').innerHTML=`<i class="stone ${match.turn===1?'black':'white'}"></i><strong>${who}</strong>`;$('player-label').textContent=config.mode==='local'?`PLAYER ${match.turn} — ${match.turn===1?'BLACK':'WHITE'}`:(match.turn===config.human?'YOU':'AI')+' — '+(match.turn===1?'BLACK':'WHITE');$('level').textContent=config.mode==='local'?'LOCAL 2P / 无 AI':names[config.difficulty];$('moves').textContent=String(match.history.length).padStart(2,'0');$('thinking').hidden=!thinking;$('status').textContent=match.finished?(match.winner?'五子连线 · 对局结束':'棋盘已满 · 和棋'):thinking?'AI 正在思考':started?'等待落子':'准备开始';$('result').hidden=!match.finished;$('winner').textContent=match.winner===1?'BLACK WINS':match.winner===2?'WHITE WINS':'DRAW';$('result-note').textContent=match.winner?(match.winner===1?'黑方':'白方')+'获胜 · 棋盘已标记五颗获胜棋子':'和棋 · 双方均未连成五子';$('undo').disabled=!config.undo||match.finished||!undoCount();canvas.setAttribute('aria-label',`15乘15五子棋，${who}，已落${match.history.length}子${match.finished?'，对局结束':''}`);draw()}
function cancelAI(){job++;if(worker)worker.terminate();worker=null;thinking=false}
function scheduleAI(){if(config.mode!=='ai'||match.finished||match.turn===config.human||!started)return;cancelAI();thinking=true;hover=null;sync();const id=job,begin=performance.now();try{worker=new Worker('gomoku-worker.js');worker.onmessage=({data})=>{const remaining=Math.max(0,320-(performance.now()-begin));setTimeout(()=>{if(data.id!==job||!thinking||!started)return;if(data.error){$('status').textContent='AI 计算失败，请开启新对局';cancelAI();return}lastSearch=data;worker?.terminate();worker=null;thinking=false;if(!match.place(data.index%15,Math.floor(data.index/15))){$('status').textContent='AI 落子异常，请开启新对局';return}tone(match.finished);sync()},remaining)};worker.onerror=()=>{if(id!==job)return;cancelAI();sync();$('status').textContent='AI 加载失败，请重试新对局'};worker.postMessage({id,board:Array.from(match.board),color:match.turn,difficulty:config.difficulty})}catch{cancelAI();sync();$('status').textContent='当前浏览器无法启动 AI，请选择本地双人'}}
function place(cell){if(!cell||!canPlay())return false;if(!match.place(cell.x,cell.y))return false;hover=null;tone(match.finished);sync();scheduleAI();return true}
function start(next=config){cancelAI();config={...next};match.reset();lastSearch=null;started=true;hover=null;lastTap=0;$('setup').close();sync();scheduleAI()}
function cellAt(e){const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)*720/b.width,y=(e.clientY-b.top)*720/b.height,xx=Math.round((x-PAD)/STEP),yy=Math.round((y-PAD)/STEP);if(!GomokuCore.inside(xx,yy)||Math.abs(x-PAD-xx*STEP)>STEP*.55||Math.abs(y-PAD-yy*STEP)>STEP*.55)return null;return {x:xx,y:yy}}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||pointer!==null)return;e.preventDefault();canvas.focus({preventScroll:true});pointer=e.pointerId;canvas.setPointerCapture(pointer);hover=cellAt(e);draw()});
canvas.addEventListener('pointermove',e=>{if(pointer!==null&&pointer!==e.pointerId)return;hover=canPlay()?cellAt(e):null;draw()});
canvas.addEventListener('pointerup',e=>{if(pointer!==e.pointerId)return;e.preventDefault();pointer=null;const cell=cellAt(e),now=performance.now();if((lastTap===0||now-lastTap>240)&&place(cell))lastTap=now;hover=null;draw()});
canvas.addEventListener('pointercancel',()=>{pointer=null;hover=null;draw()});canvas.addEventListener('pointerleave',()=>{if(pointer===null){hover=null;draw()}});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('dblclick',e=>e.preventDefault());
canvas.addEventListener('keydown',e=>{const dirs={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(dirs[e.code]){e.preventDefault();keyCell.x=Math.max(0,Math.min(14,keyCell.x+dirs[e.code][0]));keyCell.y=Math.max(0,Math.min(14,keyCell.y+dirs[e.code][1]));hover=keyCell;draw()}else if(['Enter','Space'].includes(e.code)){e.preventDefault();if(!e.repeat)place(keyCell)}});
$('undo').onclick=()=>{const count=undoCount();if(!config.undo||match.finished||!count)return;cancelAI();match.undo(count);lastTap=0;sync()};$('rematch').onclick=()=>start();
function options(){const local=$('mode').value==='local';$('difficulty-label').hidden=local;$('color-label').hidden=local;$('difficulty-note').textContent=local?'同一设备轮流落子：PLAYER 1 黑子先手，PLAYER 2 白子后手。':notes[$('difficulty').value]}
$('mode').onchange=options;$('difficulty').onchange=options;$('configure').onclick=()=>{$('mode').value=config.mode;$('difficulty').value=config.difficulty;$('color').value=String(config.human);$('allow-undo').checked=config.undo;options();$('setup').showModal()};$('cancel').onclick=()=>{if(started)$('setup').close();else location.href='./'};$('setup').addEventListener('cancel',e=>{if(!started)e.preventDefault()});$('setup-form').onsubmit=e=>{e.preventDefault();start({mode:$('mode').value,difficulty:$('difficulty').value,human:Number($('color').value),undo:$('allow-undo').checked})};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent='SOUND '+(sound?'ON':'OFF')};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.cabinet').requestFullscreen()}catch{$('fullscreen').textContent='⛶'}};
window.addEventListener('pagehide',cancelAI);window.PixelGomoku={match,start,get config(){return {...config}},get thinking(){return thinking},get lastSearch(){return lastSearch},sync};options();sync();$('setup').showModal();
})();
