/* Hammer Battle owns combat, AI, respawning and match outcomes. No bomb engine dependencies. */
(function(root){'use strict';const W=15,H=13,D=[[0,-1],[1,0],[0,1],[-1,0]],I=(x,y)=>y*W+x;
const HEROES={explorer:{skill:'烈焰木棰',tip:'木棰震击，伤害 2 点'},soldier:{skill:'雷电木棰',tip:'雷电飞棰沿直线攻击'},mystic:{skill:'回旋木棰',tip:'贯穿回旋木棰，沿原路返回'},dora:{skill:'空气护盾',tip:'全队护盾并击退附近对手'},goku:{skill:'龟派冲击',tip:'强力气功弹，伤害 2 点'},nezha:{skill:'乾坤旋风',tip:'范围旋击并加速 5 秒'}};
Object.assign(HEROES,{"astro":{"skill":"原子飞棰","tip":"释放直线能量木棰"},"happy":{"skill":"机甲重击","tip":"木棰范围重击，伤害 2 点"},"wuwa":{"skill":"水浪飞棰","tip":"释放贯穿回旋木棰"}});
class Match{
constructor(options={}){this.options={mode:'solo',p1:'explorer',p2:'dora',difficulty:'medium',map:0,rivals:true,...options};this.options.map=Math.max(0,Math.min(2,+this.options.map||0));this.seed=(options.seed??Date.now())>>>0;this.serial=0;this.events=[];this.grid=Array(W*H).fill('.');this.phase='ready';this.delay=2;this.paused=false;this.elapsed=0;this.round=1;this.wins=[0,0,0,0];this.scores=[0,0,0,0];this.shots=[];this.particles=[];this.items=[];this.actors=[];this.result=null;this.itemClock=10;
for(let y=0;y<H;y++)for(let x=0;x<W;x++)this.grid[I(x,y)]=!x||!y||x===14||y===12||x%2===0&&y%2===0?'S':this.random()<.48?'B':'.';const extra=this.options.map===1?[[4,5],[10,5],[4,7],[10,7]]:this.options.map===2?[[7,4],[7,8],[3,6],[11,6]]:[];for(const [x,y]of extra)this.grid[I(x,y)]='S';const count=this.options.mode==='duel'&&!this.options.rivals?2:4,spawn=this.options.mode==='coop'?[[1,1],[13,1],[1,11],[13,11]]:[[1,1],[13,11],[13,1],[1,11]],ids=Object.keys(HEROES);for(let n=0;n<count;n++){const human=n===0||n===1&&this.options.mode!=='solo',id=n===0?this.options.p1:n===1&&human?this.options.p2:ids[(n+1)%ids.length];const p={uid:++this.serial,side:n,team:this.options.mode==='coop'?(n<2?0:1):n,id:HEROES[id]?id:'explorer',human,spawn:spawn[n],deaths:0,kills:0};this.actors.push(p);for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++){const x=spawn[n][0]+dx,y=spawn[n][1]+dy;if(x>0&&x<14&&y>0&&y<12&&Math.abs(dx)+Math.abs(dy)<=3&&this.grid[I(x,y)]!=='S')this.grid[I(x,y)]='.';}this.respawn(p);}const available=this.grid.map((t,i)=>t==='.'&&i%15>0&&i%15<14&&i>=15&&i<180&&!this.actors.some(p=>Math.abs(i%15-p.spawn[0])+Math.abs(Math.floor(i/15)-p.spawn[1])<=3)?i:-1).filter(i=>i>=0);const obstacleTarget=Math.ceil(Math.max(32,this.grid.filter(t=>t==='B').length)*4/3);while(this.grid.filter(t=>t==='B').length<obstacleTarget&&available.length){const n=Math.floor(this.random()*available.length),i=available.splice(n,1)[0];this.grid[i]='B';}this.obstacles={};for(let i=0;i<this.grid.length;i++)if(this.grid[i]!=='.'){const variant=(i*7+Math.floor(i/15)*11+this.options.map)%3;this.obstacles[i]={variant,hp:this.grid[i]==='B'&&variant===2?2:1};}this.events.push({type:'round'});}
random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
respawn(p){const [x,y]=p.spawn;Object.assign(p,{cx:x,cy:y,x:x+.5,y:y+.5,target:null,dir:2,alive:true,hp:1,maxHp:1,mounted:false,energy:p.energy??100,inv:1,guard:0,guardTime:0,haste:0,speed:3.3,cool:0,action:null,attackFlash:0,anim:0,think:0,respawnTime:0,weapon:'normal',weaponTime:0});this.spark(x+.5,y+.5,'#bceaff',10);}
spark(x,y,color,n=10){for(let i=0;i<n;i++){const a=this.random()*Math.PI*2,s=1+this.random()*3;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+this.random()*.3,color});}}
walkable(x,y){return x>0&&x<14&&y>0&&y<12&&this.grid[I(x,y)]==='.';}
move(p,dir,dt){if(!p.target&&dir>=0&&dir<4){p.dir=dir;const [dx,dy]=D[dir],x=p.cx+dx,y=p.cy+dy;if(this.walkable(x,y))p.target={x,y,progress:0};}if(p.target){p.target.progress+=dt*p.speed*(p.haste>0?1.3:1);const t=Math.min(1,p.target.progress);p.x=p.cx+.5+(p.target.x-p.cx)*t;p.y=p.cy+.5+(p.target.y-p.cy)*t;p.anim+=dt*12;if(t===1){p.cx=p.target.x;p.cy=p.target.y;p.x=p.cx+.5;p.y=p.cy+.5;p.target=null;}}}
line(x,y,xx,yy){const n=Math.ceil(Math.hypot(xx-x,yy-y)*4);for(let k=1;k<=n;k++){const i=I(Math.floor(x+(xx-x)*k/n),Math.floor(y+(yy-y)*k/n));if(this.grid[i]!=='.')return false;}return true;}
attack(p){if(!p.alive||p.cool>0)return false;p.cool=p.weapon==='heavy'?.8:.56;p.action={age:0,dir:p.dir,hits:[],crateHits:[],radial:p.weapon==='thunder',damage:p.weapon==='heavy'?2:1,range:p.weapon==='heavy'?1.65:1.4};p.attackFlash=.4;if(p.weapon==='boomerang')this.projectile(p,1,true);this.events.push({type:'attack',side:p.side});return true;}
projectile(p,damage,returning=false){const [dx,dy]=D[p.dir];this.shots.push({uid:++this.serial,owner:p.uid,x:p.x+dx*.4,y:p.y+dy*.4,vx:dx*7,vy:dy*7,damage,returning,hits:[],age:0,life:returning?1.0:.8});}
hit(owner,p,damage,dx,dy){if(this.phase==='finished'||!p.alive||p.inv>0||owner.team===p.team)return false;if(p.guard>0){p.guard--;p.inv=.35;this.events.push({type:'shield'});return true;}p.hp-=damage;if(p.mounted&&p.hp<3){p.mounted=false;p.maxHp=2;}p.inv=.4;this.spark(p.x,p.y,'#ffd994',10);this.events.push({type:'hit'});const x=p.cx+Math.sign(dx),y=p.cy+Math.sign(dy);if(this.walkable(x,y)){p.cx=x;p.cy=y;p.x=x+.5;p.y=y+.5;p.target=null;}if(p.hp<=0){p.alive=false;p.target=null;p.action=null;p.respawnTime=0;p.deaths++;owner.kills++;this.wins[owner.team]++;this.scores[owner.side]+=200;owner.energy=Math.min(100,owner.energy+20);this.events.push({type:'out',side:p.side});this.respawn(p);if(this.wins[owner.team]>=10)this.finish(owner.team);}return true;}
finish(team){if(this.phase==='finished')return;this.phase='finished';this.result={winner:team,wins:this.wins.slice(),scores:this.scores.slice(),rankings:this.actors.map(p=>({side:p.side,id:p.id,team:p.team,score:this.scores[p.side],wins:this.wins[p.team],kills:p.kills,deaths:p.deaths})).sort((a,b)=>b.wins-a.wins||b.kills-a.kills)};this.events.push({type:'result',winner:team});}
skill(p){if(!p.alive||p.energy<100)return false;p.energy=0;p.attackFlash=.5;if(p.id==='dora'){for(const a of this.actors)if(a.alive&&a.team===p.team){a.guard=2;a.guardTime=8;}for(const a of this.actors)if(a.alive&&a.team!==p.team&&Math.hypot(a.x-p.x,a.y-p.y)<2)this.hit(p,a,1,a.x-p.x,a.y-p.y);}else if(['soldier','mystic','goku','astro','wuwa'].includes(p.id))this.projectile(p,p.id==='goku'?2:1,['mystic','wuwa'].includes(p.id));else{p.action={age:0,dir:p.dir,hits:[],crateHits:[],radial:true,damage:['explorer','happy'].includes(p.id)?2:1,range:1.7};if(p.id==='nezha')p.haste=5;}this.events.push({type:'skill',side:p.side,name:HEROES[p.id].skill});return true;}
strike(p){const a=p.action;if(!a||a.age<.08||a.age>.33)return;const [dx,dy]=D[a.dir];for(const foe of this.actors){if(!foe.alive||foe.team===p.team||a.hits.includes(foe.uid))continue;const xx=foe.x-p.x,yy=foe.y-p.y,dot=xx*dx+yy*dy;if(Math.hypot(xx,yy)<=a.range&&(a.radial||dot>-.05&&Math.abs(xx*dy-yy*dx)<.8)&&this.line(p.x,p.y,foe.x,foe.y)){a.hits.push(foe.uid);this.hit(p,foe,a.damage,xx,yy);}}
for(let y=Math.max(1,p.cy-2);y<=Math.min(11,p.cy+2);y++)for(let x=Math.max(1,p.cx-2);x<=Math.min(13,p.cx+2);x++){const i=I(x,y),xx=x+.5-p.x,yy=y+.5-p.y;if(this.grid[i]==='B'&&!a.crateHits.includes(i)&&Math.hypot(xx,yy)<=a.range&&(a.radial||xx*dx+yy*dy>.1&&Math.abs(xx*dy-yy*dx)<.8)){a.crateHits.push(i);const obstacle=this.obstacles[i];if(obstacle){obstacle.hp-=a.damage;if(obstacle.hp>0){this.spark(x+.5,y+.5,'#dbb17c',5);continue;}delete this.obstacles[i];}this.grid[i]='.';this.scores[p.side]+=10;this.spark(x+.5,y+.5,'#c99874');if(this.random()<.35)this.items.push({i,type:['heavy','thunder','boomerang','shield','mount','heal','energy'][Math.floor(this.random()*7)],delay:0});}}}
ai(p,dt){p.think-=dt;if(p.think>0)return {};p.think={easy:.28,medium:.13,hard:.06}[this.options.difficulty]||.13;const foes=this.actors.filter(a=>a.alive&&a.team!==p.team).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y));const foe=foes[0];if(!foe)return {};const xx=foe.x-p.x,yy=foe.y-p.y;if(Math.hypot(xx,yy)<1.35&&(Math.abs(xx)<.75||Math.abs(yy)<.75)&&this.line(p.x,p.y,foe.x,foe.y)){p.dir=Math.abs(xx)>Math.abs(yy)?xx>0?1:3:yy>0?2:0;if(p.energy>=100)this.skill(p);return {attack:true};}if(p.target)return {};const target=I(foe.cx,foe.cy),start=I(p.cx,p.cy),q=[start],seen=new Set(q),first={};let best=start,bestDist=999;for(let j=0;j<q.length;j++){const i=q[j],x=i%W,y=Math.floor(i/W),d=Math.abs(x-foe.cx)+Math.abs(y-foe.cy);if(d<bestDist){best=i;bestDist=d;}if(i===target)break;for(let n=0;n<4;n++){const [dx,dy]=D[n],nx=x+dx,ny=y+dy,ii=I(nx,ny);if(nx<1||nx>13||ny<1||ny>11||seen.has(ii)||this.grid[ii]==='S')continue;seen.add(ii);first[ii]=first[i]??n;q.push(ii);}}const dir=first[best]??-1;if(dir>=0){const [dx,dy]=D[dir];if(this.grid[I(p.cx+dx,p.cy+dy)]==='B'){p.dir=dir;return {attack:true};}}return {dir};}
pickup(p,it){if(['heavy','thunder','boomerang'].includes(it.type)){p.weapon=it.type;p.weaponTime=12;}else if(it.type==='shield'){p.maxHp=Math.max(p.maxHp,2);p.hp=Math.max(p.hp,2);}else if(it.type==='mount'){p.maxHp=3;p.hp=3;p.mounted=true;}else if(it.type==='heal')p.hp=Math.min(p.maxHp,p.hp+1);else p.energy=Math.min(100,p.energy+40);this.scores[p.side]+=25;this.items.splice(this.items.indexOf(it),1);this.events.push({type:'pickup',side:p.side,name:it.type});}
step(dt,inputs=[]){if(this.paused||this.phase==='finished')return;dt=Math.min(1/30,Math.max(0,dt));for(const f of this.particles){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;}this.particles=this.particles.filter(f=>f.life>0);if(this.phase==='ready'){this.delay-=dt;if(this.delay<=0)this.phase='playing';return;}this.elapsed+=dt;this.itemClock-=dt;if(this.itemClock<=0){const free=this.grid.map((t,i)=>t==='.'?i:-1).filter(i=>i>=0);this.items.push({i:free[Math.floor(this.random()*free.length)],type:['heavy','thunder','boomerang','shield','mount','heal','energy'][Math.floor(this.random()*7)],delay:0});this.itemClock=10;}
for(const p of this.actors){if(!p.alive){p.respawnTime-=dt;if(p.respawnTime<=0)this.respawn(p);continue;}p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);p.attackFlash=Math.max(0,p.attackFlash-dt);p.haste=Math.max(0,p.haste-dt);p.guardTime=Math.max(0,p.guardTime-dt);if(!p.guardTime)p.guard=0;p.weaponTime=Math.max(0,p.weaponTime-dt);if(!p.weaponTime)p.weapon='normal';p.energy=Math.min(100,p.energy+dt*8);const input=p.human?(inputs[p.side]||{}):this.ai(p,dt);this.move(p,input.dir??-1,dt);if(input.attack)this.attack(p);if(input.skill)this.skill(p);if(p.action){p.action.age+=dt;this.strike(p);if(p.action.age>.4)p.action=null;}const it=this.items.find(it=>it.i===I(Math.floor(p.x),Math.floor(p.y)));if(it)this.pickup(p,it);if(this.phase==='finished')return;}
for(const s of this.shots){s.age+=dt;s.life-=dt;if(s.returning&&s.age>=.45&&!s.returned){s.vx*=-1;s.vy*=-1;s.returned=true;}const n=Math.ceil(Math.hypot(s.vx,s.vy)*dt/.15);for(let i=0;i<n&&s.life>0;i++){s.x+=s.vx*dt/n;s.y+=s.vy*dt/n;if(!this.walkable(Math.floor(s.x),Math.floor(s.y))){s.life=0;break;}const owner=this.actors.find(p=>p.uid===s.owner);for(const p of this.actors)if(p.alive&&p.team!==owner.team&&!s.hits.includes(p.uid)&&Math.hypot(p.x-s.x,p.y-s.y)<.45){s.hits.push(p.uid);this.hit(owner,p,s.damage,s.vx,s.vy);if(!s.returning)s.life=0;}}}this.shots=this.shots.filter(s=>s.life>0);}
snapshot(){return {phase:this.phase,paused:this.paused,mode:this.options.mode,map:this.options.map,elapsed:this.elapsed,actors:this.actors.map(p=>({...p,target:p.target?{...p.target}:null,action:p.action?{...p.action}:null})),wins:this.wins.slice(),scores:this.scores.slice(),result:this.result};}}
const api={Match,HEROES,W,H,DIRS:D,idx:I};root.PixelHammerCore=api;if(typeof module==='object')module.exports=api;
})(typeof globalThis==='object'?globalThis:this);
