(()=>{'use strict';const C=JungleCore,$=id=>document.getElementById(id),match=new C.Match(),tierNames={easy:'简单',normal:'普通',hard:'困难',expert:'专家'};let config={mode:'ai',difficulty:'normal',human:1},selected=null,worker=null,job=0,thinking=false,started=false,sound=true,audio=null,last=null,lastSearch=null;
function tone(type='move'){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type='triangle';o.frequency.setValueAtTime(type==='win'?660:type==='capture'?450:280,t);o.frequency.exponentialRampToValueAtTime(type==='win'?880:160,t+.15);g.gain.setValueAtTime(.04,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(audio.destination);o.start();o.stop(t+.21)}catch{}}
function portrait(rank){const c=document.createElement('canvas');c.width=c.height=80;JungleArt.animal(c.getContext('2d'),rank,0,0,80);return c}
function draw(){const s=match.s,legal=selected===null?[]:C.moves(s).filter(m=>m.from===selected);$('board').replaceChildren(...s.board.map((p,i)=>{const b=document.createElement('button'),t=C.tile(i),m=legal.find(m=>m.to===i);b.type='button';b.dataset.cell=i;b.className=[t.type,i===selected?'selected':'',m?m.capture?'capture':'legal':''].join(' ');b.setAttribute('aria-label',`${i%7+1}列 ${Math.floor(i/7)+1}行，${p?(p>0?'红':'蓝')+C.names[Math.abs(p)]+' 等级'+C.rank(s.board,i):t.type==='water'?'河流':t.type==='trap'?(t.owner>0?'红':'蓝')+'方陷阱':t.type==='den'?(t.owner>0?'红':'蓝')+'方兽穴':'空地'}${m?'，合法目标':''}`);const terrain=document.createElement('span');terrain.className='terrain-label';terrain.textContent=t.type==='water'?'河':t.type==='trap'?'陷阱':t.type==='den'?'兽穴':'';b.append(terrain);if(p){const piece=document.createElement('span');piece.className='piece'+(p<0?' blue-piece':'')+(last===i?' new':'');const name=document.createElement('small');name.textContent=C.names[Math.abs(p)]+' '+C.rank(s.board,i);piece.append(portrait(Math.abs(p)),name);b.append(piece)}b.onclick=()=>click(i);return b}));$('turn').textContent=(s.turn===1?'RED / 红方':'BLUE / 蓝方')+(config.mode==='ai'?(s.turn===config.human?' · YOU':' · AI'):'');$('turn').style.color=s.turn===1?'#f5a09d':'#96c7f5';$('mode-label').textContent=config.mode==='local'?'LOCAL 2P / 本地双人':`1P VS AI · ${config.difficulty.toUpperCase()} / ${tierNames[config.difficulty]}`;$('thinking').hidden=!thinking;$('status').textContent=s.winner!==null?'对局结束':thinking?'AI 正在思考…':selected!==null?'选择金色移动格或红色吃子格':started?'请选择己方动物':'准备开始';for(const side of [1,-1]){const name=side===1?'red':'blue';$(''+name+'-count').textContent=s.board.filter(p=>Math.sign(p)===side).length;const captured=$(''+name+'-captured');captured.replaceChildren();for(let r=1;r<=8;r++)if(!s.board.includes(-side*r)){const canvas=portrait(r);canvas.title='已吃掉'+C.names[r];canvas.setAttribute('aria-label','已吃掉'+C.names[r]);captured.append(canvas)}}$('result').hidden=s.winner===null;$('winner').textContent=s.winner===1?'RED WINS':s.winner===-1?'BLUE WINS':'DRAW';$('reason').textContent=s.reason;$('undo').disabled=undoCount()===0}
function cancelAI(){job++;worker?.terminate();worker=null;thinking=false}
function scheduleAI(){if(!started||match.s.winner!==null||config.mode!=='ai'||match.s.turn===config.human)return;cancelAI();thinking=true;selected=null;draw();const id=job,begin=performance.now();worker=new Worker('jungle-worker.js');worker.onmessage=({data})=>{setTimeout(()=>{if(data.id!==job||!thinking)return;worker?.terminate();worker=null;thinking=false;if(data.error||!data.move||!match.play(data.move.from,data.move.to)){draw();$('status').textContent='AI 计算异常，请重新开始对局。';return}lastSearch=data;last=data.move.to;tone(match.s.winner!==null?'win':data.move.capture?'capture':'move');draw()},Math.max(0,300-(performance.now()-begin)))};worker.onerror=()=>{if(job!==id)return;cancelAI();draw();$('status').textContent='AI 加载失败，请重试或选择本地双人。'};worker.postMessage({id,state:match.s,difficulty:config.difficulty})}
function click(i){if(!started||thinking||match.s.winner!==null||$('setup').open||$('rules').open||config.mode==='ai'&&match.s.turn!==config.human)return;const p=match.s.board[i];if(Math.sign(p)===match.s.turn){selected=selected===i?null:i;last=null;draw();return}const m=selected===null?null:C.moves(match.s).find(m=>m.from===selected&&m.to===i);selected=null;if(m&&match.play(m.from,m.to)){last=i;tone(match.s.winner!==null?'win':m.capture?'capture':'move');draw();scheduleAI()}else{last=null;draw()}}
function start(next=config){cancelAI();config={...next};match.reset();last=null;lastSearch=null;selected=null;started=true;$('setup').close();draw();scheduleAI()}
function undoCount(){if(config.mode==='local')return match.history.length?1:0;const i=match.history.findLastIndex(s=>s.turn===config.human);return i<0?0:match.history.length-i}
$('undo').onclick=()=>{const count=undoCount();if(!count)return;cancelAI();match.undo(count);selected=null;last=null;lastSearch=null;draw();scheduleAI()};$('rematch').onclick=()=>start();
function options(){const local=$('mode').value==='local';$('difficulty-label').hidden=local;$('side-label').hidden=local}$('mode').onchange=options;$('configure').onclick=()=>{$('mode').value=config.mode;$('difficulty').value=config.difficulty;$('side').value=config.human;$('sound-option').checked=sound;options();$('setup').showModal()};$('cancel').onclick=()=>started?$('setup').close():location.href='./';$('setup').addEventListener('cancel',e=>{if(!started)e.preventDefault()});$('setup-form').onsubmit=e=>{e.preventDefault();sound=$('sound-option').checked;$('sound').textContent='SOUND '+(sound?'ON':'OFF');start({mode:$('mode').value,difficulty:$('difficulty').value,human:Number($('side').value)})};$('sound').onclick=()=>{sound=!sound;$('sound').textContent='SOUND '+(sound?'ON':'OFF')};$('rules-open').onclick=()=>$('rules').showModal();$('rules-close').onclick=()=>$('rules').close();for(let r=8;r>=1;r--){const d=document.createElement('div'),name=document.createElement('small');name.textContent=C.names[r]+' '+r;d.append(portrait(r),name);$('animal-guide').append(d)}window.addEventListener('pagehide',cancelAI);window.PixelJungle={match,start,draw,click,get config(){return {...config}},get thinking(){return thinking},get lastSearch(){return lastSearch}};draw();options();$('setup').showModal();
})();
