(function(root){'use strict';const C=root.JungleCore||(typeof require==='function'?require('./jungle-core.js'):null),values=[0,380,240,300,380,480,700,790,900];
function evaluate(s,side){if(s.winner!==null)return s.winner===0?0:s.winner===side?100000:-100000;let score=0;const enemyMoves=C.moves(s,-side),ourMoves=C.moves(s,side),threats=new Set(enemyMoves.filter(m=>m.capture).map(m=>m.to)),ours=new Set(ourMoves.filter(m=>m.capture).map(m=>m.to));for(let i=0;i<63;i++){const p=s.board[i];if(!p)continue;const owner=Math.sign(p),r=Math.abs(p),dist=Math.abs(i%7-3)+Math.abs(Math.floor(i/7)-(owner===1?0:8));let v=values[r]+(11-dist)*17;if(C.rank(s.board,i)===0)v-=values[r]*.85;if((owner===side?threats:ours).has(i))v-=values[r]*.6;if(r===1&&C.tile(i).type==='water')v+=30;if([6,7].includes(r))v+=(owner===side?ourMoves:enemyMoves).filter(m=>m.from===i&&Math.abs(m.to-m.from)>7).length*20;score+=owner===side?v:-v}return score}
function choose(s,tier='normal',options={}){const legal=C.moves(s);if(!legal.length)return {move:null,nodes:0,depth:0};const side=s.turn,instant=legal.find(m=>C.step(s,m).winner===side);if(instant)return {move:instant,nodes:1,depth:1,reason:'immediate-win'};if(tier==='easy'){const captures=legal.filter(m=>m.capture),pool=captures.length?captures:legal;return {move:pool[Math.floor((options.rng||Math.random)()*pool.length)],nodes:legal.length,depth:0,reason:'capture-or-random'}}
const target={normal:2,hard:3,expert:5}[tier]||2,budget=options.budget??({normal:150,hard:650,expert:1400}[tier]),end=performance.now()+budget,maxNodes=options.maxNodes??90000;let nodes=0,depthDone=0,best=legal[0];const tt=new Map();
const hash=s=>C.key(s)+'/'+s.quiet+'/'+Object.entries(s.seen).sort().map(([k,v])=>k+'='+v).join(';');
function order(s,ms,preferred){return ms.map(m=>({m,v:(preferred&&m.from===preferred.from&&m.to===preferred.to?1e6:0)+(m.capture?values[Math.abs(m.capture)]*4:0)+evaluate(C.step(s,m),s.turn)})).sort((a,b)=>b.v-a.v).map(o=>o.m)}
function search(s,d,alpha,beta){if(++nodes>maxNodes||performance.now()>end)throw 'budget';if(!d||s.winner!==null)return evaluate(s,s.turn);const k=tier==='expert'?hash(s):null,hit=k?tt.get(k):null;if(hit&&hit.depth>=d){if(hit.flag==='exact')return hit.score;if(hit.flag==='lower')alpha=Math.max(alpha,hit.score);else beta=Math.min(beta,hit.score);if(alpha>=beta)return hit.score}const startAlpha=alpha,startBeta=beta;let value=-Infinity,move=null;for(const m of order(s,C.moves(s),hit?.move)){const v=-search(C.step(s,m),d-1,-beta,-alpha);if(v>value){value=v;move=m}alpha=Math.max(alpha,v);if(alpha>=beta)break}if(k&&tt.size<20000)tt.set(k,{depth:d,score:value,move,flag:value<=startAlpha?'upper':value>=startBeta?'lower':'exact'});return value}
// Root fallback rejects an immediately losing move whenever a safe move exists.
const safe=legal.filter(m=>{const n=C.step(s,m);return !C.moves(n).some(reply=>C.step(n,reply).winner===n.turn)}),pool=safe.length?safe:legal;best=order(s,pool)[0];
for(let d=1;d<=target;d++){let candidate=best,score=-Infinity;try{for(const m of order(s,pool,best)){const v=-search(C.step(s,m),d-1,-Infinity,-score);if(v>score){score=v;candidate=m}}best=candidate;depthDone=d}catch(e){if(e!=='budget')throw e;break}}
return {move:best,nodes,depth:depthDone,reason:tier==='expert'?'iterative-alpha-beta-tt':tier==='hard'?'alpha-beta':'shallow-search',tableSize:tt.size}}
root.JungleAI={choose,evaluate};if(typeof module!=='undefined')module.exports=root.JungleAI;
})(globalThis);
