/* Saved physical-key bindings; mode engines continue receiving their original actions. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.ArcadeKeys=api;api.install();}})(typeof globalThis!=='undefined'?globalThis:this,()=>{'use strict';
const action=(id,label,...codes)=>({id,label,codes});const move1=[action('up','1P 上 / 前移','KeyW'),action('right','1P 右移','KeyD'),action('down','1P 下 / 后移','KeyS'),action('left','1P 左移','KeyA')],move2=[action('up2','2P 上移','ArrowUp'),action('right2','2P 右移','ArrowRight'),action('down2','2P 下移','ArrowDown'),action('left2','2P 左移','ArrowLeft')];const pause=action('pause','暂停 / 继续','KeyP');
const modes={adventure:{name:'冒险闯关',actions:[action('left','左移','KeyA','ArrowLeft'),action('right','右移','KeyD','ArrowRight'),action('jump','普通跳 / 二段跳','KeyK'),action('jumpAlt','普通跳（备用）','KeyW','ArrowUp'),action('high','高跳','Space'),action('attack','攻击','KeyJ','KeyX'),action('run','奔跑','ShiftLeft','ShiftRight'),pause,action('restart','重新开始','KeyR'),action('sound','声音开关','KeyM')]},badminton:{name:'羽毛球对战',actions:[action('left','左移','KeyA','ArrowLeft'),action('right','右移','KeyD','ArrowRight'),action('up','前移','KeyW','ArrowUp'),action('down','后移','KeyS','ArrowDown'),action('jump','跳跃','Space','KeyK'),action('clear','高远球 / 发球','KeyJ'),action('drop','吊球','KeyL'),action('smash','扣杀','KeyH'),action('special','角色技能','KeyE'),pause]},fighting:{name:'横版格斗',actions:[...move1.map(a=>a.id==='up'?{...a,label:'1P 跳跃'}:a.id==='down'?{...a,label:'1P 格挡'}:a),action('punch','1P 挥拳','KeyJ'),action('kick','1P 踢腿','KeyK'),action('roll','1P 翻滚','KeyL'),action('special','1P 技能','KeyU'),action('ultimate','1P 终极','KeyI'),...move2.map(a=>a.id==='up2'?{...a,label:'2P 跳跃'}:a.id==='down2'?{...a,label:'2P 格挡'}:a),action('punch2','2P 挥拳','Digit1','Numpad1'),action('kick2','2P 踢腿','Digit2','Numpad2'),action('roll2','2P 翻滚','Digit3','Numpad3'),action('special2','2P 技能','Digit4','Numpad4'),action('ultimate2','2P 终极','Digit5','Numpad5'),pause]},tank:{name:'坦克大战',actions:[...move1,action('fire','1P 射击','KeyJ','Space'),action('special','1P 技能','KeyK'),action('boost','1P 加速','KeyL'),...move2,action('fire2','2P 射击','Enter','Numpad0'),action('special2','2P 技能','ShiftRight','Numpad1'),action('boost2','2P 加速','Numpad2'),pause]},bomber:{name:'炸弹竞技场（炸弹 / 木棰）',actions:[...move1,action('attack','1P 炸弹 / 木棰','KeyJ','Space'),action('special','1P 技能','KeyK'),...move2,action('attack2','2P 炸弹 / 木棰','Enter','Numpad0'),action('special2','2P 技能','ShiftRight','Numpad1'),pause]},blocks:{name:'俄罗斯方块',actions:[...move1.filter(a=>a.id!=='up').map(a=>a.id==='down'?{...a,label:'1P 软降'}:a),action('cw','1P 顺时针旋转','KeyW'),action('ccw','1P 逆时针旋转','KeyQ'),action('hard','1P 硬降','Space'),action('hold','1P 暂存','KeyE'),...move2.filter(a=>a.id!=='up2').map(a=>a.id==='down2'?{...a,label:'2P 软降'}:a),action('cw2','2P 顺时针旋转','ArrowUp'),action('ccw2','2P 逆时针旋转','ShiftRight'),action('hard2','2P 硬降','Enter'),action('hold2','2P 暂存','ControlRight'),pause]}};
const STORE='pq-keybindings-v1';const allowed=c=>/^(Key[A-Z]|Digit[0-9]|Numpad[0-9]|Arrow(Up|Down|Left|Right)|Space|Enter|Shift(Left|Right)|Control(Left|Right))$/.test(c);const label=c=>({Space:'空格',Enter:'Enter',ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑',ArrowDown:'↓',ShiftLeft:'左 Shift',ShiftRight:'右 Shift',ControlLeft:'左 Ctrl',ControlRight:'右 Ctrl'}[c]||c.replace('Key','').replace('Digit','').replace('Numpad','小键盘 '));
function read(){try{const v=JSON.parse(localStorage.getItem(STORE)||'{}');return v&&typeof v==='object'?v:{};}catch{return{};}}
function bindings(mode,data=read()){const saved=data[mode]||{};return modes[mode].actions.map(a=>({...a,keys:allowed(saved[a.id])?[saved[a.id]]:a.codes.slice(),custom:allowed(saved[a.id])&&saved[a.id]!==a.codes[0]}));}
function conflict(mode,id,code,data){return bindings(mode,data).find(a=>a.id!==id&&a.keys.includes(code));}
function set(mode,id,code){if(!modes[mode]?.actions.some(a=>a.id===id)||!allowed(code))return{error:'请选择字母、数字、方向键、空格、Enter、Shift 或 Ctrl 单键。'};const data=read(),action=modes[mode].actions.find(a=>a.id===id),checks=code===action.codes[0]?action.codes:[code],other=checks.map(c=>conflict(mode,id,c,data)).find(Boolean);if(other)return{error:`此键已用于“${other.label}”，请换一个键。`};data[mode]={...data[mode],[id]:code};if(code===action.codes[0])delete data[mode][id];try{localStorage.setItem(STORE,JSON.stringify(data));}catch{return{error:'浏览器无法保存设置，请检查本地存储是否可用。'};}if(typeof window!=='undefined')window.dispatchEvent(new Event('arcade-keys-changed'));return{ok:true};}
function reset(mode){const data=read();delete data[mode];try{localStorage.setItem(STORE,JSON.stringify(data));if(typeof window!=='undefined')window.dispatchEvent(new Event('arcade-keys-changed'));return true;}catch{return false;}}
function resolve(mode,code,data){const list=bindings(mode,data),assigned=list.find(a=>a.keys.includes(code));if(assigned)return assigned.codes[0];if(list.some(a=>a.codes.includes(code)&&!a.keys.includes(code)))return null;return code;}
function current(){const file=location.pathname.split('/').pop();return({'badminton.html':'badminton','fighting.html':'fighting','tank.html':'tank','bomber.html':'bomber','blocks.html':'blocks'}[file]||'adventure');}
function active(mode){if(mode==='adventure')return ['playing','paused','confirmhome','stageclear','gameover','victory'].includes(globalThis.PixelQuest?.state);if(mode==='badminton')return globalThis.PixelBadminton?.snapshot?.phase!=='setup'&&!!globalThis.PixelBadminton;if(mode==='fighting')return !!globalThis.PixelFighting&&globalThis.PixelFighting.snapshot.phase!=='setup';if(mode==='tank')return !!globalThis.PixelTank?.battle;if(mode==='bomber')return !!globalThis.PixelBomber?.match;return !!globalThis.PixelBlocks?.match;}
function install(){let data=read();const down=new Map(),translated=new WeakSet();window.addEventListener('storage',e=>{if(e.key===STORE)data=read();});window.addEventListener('arcade-keys-changed',()=>{data=read();hints();});const mode=current();function onkey(e){if(translated.has(e)||(e.target?.closest?.('input,select,textarea,[contenteditable=true],#lobby-dialog')&&!(e.type==='keyup'&&down.has(e.code))))return;let output;if(e.type==='keyup'&&down.has(e.code)){output=down.get(e.code);down.delete(e.code);}else{if(!active(mode))return;output=resolve(mode,e.code,data);if(e.type==='keydown')down.set(e.code,output);}if(output===e.code)return;e.preventDefault();e.stopImmediatePropagation();if(output===null)return;const event=new KeyboardEvent(e.type,{code:output,key:output.startsWith('Key')?output.slice(3).toLowerCase():output.startsWith('Digit')?output.slice(5):output==='Space'?' ':output,bubbles:true,cancelable:true,repeat:e.repeat,shiftKey:e.shiftKey,ctrlKey:e.ctrlKey,altKey:e.altKey,metaKey:e.metaKey,location:e.location});translated.add(event);(e.target?.dispatchEvent?e.target:document.body).dispatchEvent(event);if(event.defaultPrevented)e.preventDefault();}window.addEventListener('keydown',onkey,true);window.addEventListener('keyup',onkey,true);window.addEventListener('blur',()=>down.clear());
function hints(){let el=document.getElementById('custom-key-hint');const list=bindings(mode,data).filter(a=>a.custom);if(!list.length){el?.remove();return;}if(!el){el=document.createElement('p');el.id='custom-key-hint';el.style.cssText='color:#a8dce7;font:12px monospace;line-height:1.8;padding:14px;border:1px solid #557482;border-radius:5px;background:#20343e;';const host=document.querySelector('.controls,.instructions,#game-instructions');(host||document.querySelector('main')||document.body).append(el);}el.textContent='自定义按键（以下设置优先，其他按键默认）：'+list.map(a=>a.label+' '+label(a.keys[0])).join(' · ');}
window.addEventListener('DOMContentLoaded',hints);window.addEventListener('storage',hints);}
return{modes,STORE,allowed,label,read,bindings,conflict,set,reset,resolve,install};});
