const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');require('./assault-map');require('./assault-ai');const {Match}=require('./assault-core');const data=JSON.parse(fs.readFileSync('assault-preservation.json','utf8'));for(const [f,h]of Object.entries(data))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),h,f+' existing gameplay untouched');
let m=new Match(),p=m.players[0];m.step(.01,[{x:1,y:-1}]);assert(Math.abs(p.x-400-Math.SQRT1_2*2.1)<1e-7);const x=p.x;m.step(.01,[{}]);assert.equal(p.x,x);assert(m.blocked(100,2120));assert(!m.blocked(400,2120));
for(let level=1;level<=5;level++){m.shots=[];p.cooldown=0;p.weapon=level;m.primary(p);assert.equal(m.shots.length,[0,1,1,2,3,5][level]);if(level===2)assert(p.cooldown<.24);if(level===5)assert(p.cooldown<.14);}m=new Match();p=m.players[0];p.invincible=0;m.damage(p,2);assert.equal(p.hp,3);m.damage(p,3);assert.equal(p.hp,3);p.invincible=0;m.damage(p,3);assert.equal(p.lives,2);assert.equal(p.hp,5);assert.equal(p.invincible,2);p.shield=2;p.invincible=0;m.damage(p,2);assert.equal(p.hp,5);
m=new Match();p=m.players[0];p.x=150;p.y=3220;m.rescue(p);m.rescue(p);assert.equal(m.rescued,1);assert.equal(m.score,500);for(const h of m.hostages){p.x=h.x;p.y=h.y;m.rescue(p);}assert.equal(m.rescued,5);const score=m.score;m.furthest=500;m.camera=0;m.updateBoss(.1);m.boss.hp=1;m.boss.open=1;m.damageBoss(3);assert.equal(m.phase,'victory');assert(m.score-score>=5500);assert(m.summary.allRescued);
m=new Match({mode:'local'});p=m.players[1];p.invincible=0;m.shots=[{x:p.x,y:p.y,vx:0,vy:0,team:'player',damage:5,r:4,life:1}];m.updateShots(.1);assert.equal(p.hp,5);m.explosives=[{x:p.x,y:p.y,time:0,r:70,damage:8}];m.blast(m.explosives[0]);assert.equal(p.hp,5);for(let i=0;i<700;i++)m.step(1/120,[{y:-1},{}]);assert(Math.abs(m.players[0].y-m.players[1].y)<=321);assert(m.players.every(p=>p.y>=m.camera-1&&p.y<=m.camera+540));
for(const ai of ['easy','normal','hard']){m=new Match({mode:'ai',ai});for(let i=0;i<1200;i++)m.step(1/120,[{y:-1,fire:true}]);const bot=m.players[1];assert(bot.ai);assert(bot.y>=m.camera&&bot.y<=m.camera+540);m.pickups=[{x:bot.x,y:bot.y,type:'weapon'}];m.collect(bot);assert(!m.pickups[0].taken);assert(bot.ammo>=2);}
m=new Match({mode:'ai',ai:'hard'});const bot=m.players[1];m.enemies=[m.enemy('mine',bot.x+45,bot.y,77)];const mineInput=AssaultAI.input(m,bot,.2);assert(mineInput.x<0,'AI moves away from visible mine');bot.brain.wait=0;m.warnings=[{x:bot.x,y:bot.y,r:46,time:1}];const dodge=AssaultAI.input(m,bot,.2);assert(Math.abs(dodge.x)>0||Math.abs(dodge.y)>0,'AI avoids blast warning');const a=new Match({difficulty:'easy'}),h=new Match({difficulty:'hard'});assert(h.enemies.length>a.enemies.length);assert(h.settings.fire<a.settings.fire);assert(h.settings.speed>a.settings.speed);assert(h.settings.bullets>a.settings.bullets);m=new Match();p=m.players[0];m.camera=0;for(let i=0;i<1000;i++)m.enemyCombat(1/120);assert(!m.shots.length);m.camera=2700;p.y=3070;for(let i=0;i<1000;i++)m.enemyCombat(1/120);assert(m.shots.some(s=>s.team==='enemy'));m=new Match();m.furthest=450;m.camera=0;p=m.players[0];p.y=430;m.updateBoss(.1);m.boss.hp=70;m.boss.open=1;m.damageBoss(40);assert.equal(m.boss.hp,60);assert(m.boss.phaseShield>0);m.damageBoss(100);assert.equal(m.boss.hp,60);
for(const id of ['explorer','soldier','mystic','dora','goku','nezha','astro','happy','wuwa']){m=new Match({characters:[id,'dora']});p=m.players[0];assert.equal(p.hp,5);assert.equal(p.lives,3);m.step(.1,[{x:1}]);assert.equal(p.x,421);}
console.log('PASS preservation, normalized movement, bridge, 5 primary tiers, damage/shield/respawn, grouped explosions, rescue/all-rescue bonus, no friendly fire, shared camera, 3 AI difficulties, ammo reservation, offscreen attacks, boss phases, 9 equal drivers');
