const assert=require('node:assert/strict'),C=require('./number-core.js');
for(const n of [3,4,5]){let last='';for(let k=0;k<600;k++){const b=C.shuffle(n,last);assert(C.valid(b,n));assert(C.solvable(b,n));assert(!C.complete(b));assert(C.distance(b,n)>=(n===3?14:n===4?32:60));assert.notEqual(b.join(','),last);last=b.join(',')}const b=C.solved(n);[b[0],b[1]]=[b[1],b[0]];assert(!C.solvable(b,n))}console.log('PASS 1800 solvable, sufficiently shuffled, non-repeating boards; impossible parity rejected');
let clock=100;const m=new C.Match(3,[1,2,3,4,5,6,0,7,8],()=>clock);assert.equal(m.move(2),false);assert.equal(m.elapsed(),0);assert.equal(m.moves.length,0);assert(m.move(7));clock=1100;assert.equal(m.elapsed(),1000);assert(!m.move(3));assert.equal(m.moves.length,1);clock=1723;assert(m.move(8));assert(C.complete(m.board));assert.equal(m.elapsed(),1623);clock=9900;assert.equal(m.elapsed(),1623);assert(!m.move(7));console.log('PASS adjacent movement, invalid clicks, first valid move timer, real elapsed time, immediate stop');
let clock4=0;const b4=C.solved(4);[b4[14],b4[15]]=[b4[15],b4[14]];const q=new C.Match(4,b4,()=>clock4);assert(q.move(15));assert(C.complete(q.board));assert.equal(q.moves.length,1);assert.throws(()=>new C.Match(4,C.solved(4)));assert.throws(()=>new C.Match(5,[]));console.log('PASS 4x4 goal and invalid starting boards rejected');
const rows=[{id:'a',mode:3,nickname:'玩家A',time_ms:900,moves:20,finished_at:'2026-10-08T00:00:00Z'},{id:'b',mode:3,nickname:'玩家a',time_ms:1000,moves:10,finished_at:'2026-10-08T00:00:01Z'},{id:'c',mode:3,nickname:'玩家B',time_ms:900,moves:19,finished_at:'2026-10-08T00:00:03Z'},{id:'d',mode:3,nickname:'玩家C',time_ms:900,moves:19,finished_at:'2026-10-08T00:00:02Z'},{id:'e',mode:4,nickname:'玩家A',time_ms:100,moves:8,finished_at:'2026-10-08T00:00:00Z'}];assert.deepEqual(C.best(rows,3).map(x=>x.id),['d','c','a']);assert.equal(C.best(rows,4).length,1);assert.equal(C.nickname('  玩家<script>123!'),'玩家script123');assert.equal(C.time(61234),'01:01.234');console.log('PASS independent best-per-nickname rankings: time/moves/date, case-insensitive, safe nicknames');

const b5=C.solved(5);[b5[23],b5[24]]=[b5[24],b5[23]];const m5=new C.Match(5,b5);assert(!m5.move(19));assert(m5.move(24));assert(C.complete(m5.board));assert.equal(m5.moves.length,1);rows.push({id:'five',mode:5,nickname:'玩家A',time_ms:1,moves:1,finished_at:'2026-10-09T00:00:00Z'});assert.equal(C.best(rows,5)[0].id,'five');assert.equal(C.best(rows,3).length,3);assert.equal(C.best(rows,4).length,1);console.log('PASS 5x5 goal, illegal movement and independent leaderboard');

for(const n of [3,4,5]){
 for(let k=0;k<30;k++){const initial=C.shuffle(n);for(let target=0;target<n*n;target++){const m=new C.Match(n,initial,()=>123),z=initial.indexOf(0),path=C.slidePath(target,z,n),expected=[...initial];let zero=z,steps=0;for(const j of path){[expected[zero],expected[j]]=[expected[j],expected[zero]];zero=j;steps++;if(C.complete(expected))break}assert.equal(m.move(target),path.length>0);assert.deepEqual(m.board,expected);assert.equal(m.moves.length,steps);assert(C.solvable(m.board,n));for(let j=0,zero=z;j<m.moves.length;j++){assert(C.adjacent(zero,m.moves[j],n));zero=m.moves[j]}if(!path.length)assert.equal(m.started,null)}}
 const initial=C.solved(n),first=n*n-n;for(let z=n*n-1;z>first;z--)[initial[z],initial[z-1]]=[initial[z-1],initial[z]];const m=new C.Match(n,initial,()=>300);assert(m.move(n*n-1));assert(C.complete(m.board));assert.equal(m.moves.length,n-1);assert.equal(m.ended,300);assert(!m.move(first));
}
assert.deepEqual(C.slidePath(4,0,5),[1,2,3,4]);assert.deepEqual(C.slidePath(0,4,5),[3,2,1,0]);assert.deepEqual(C.slidePath(20,0,5),[5,10,15,20]);assert.deepEqual(C.slidePath(0,20,5),[15,10,5,0]);assert.deepEqual(C.slidePath(5,4,5),[]);assert.deepEqual(C.slidePath(6,0,5),[]);assert.deepEqual(C.slidePath(-1,0,5),[]);console.log('PASS multi-tile slides all four directions / all sizes, no row wrapping/diagonals, primitive move counts/replay, solve and lock');
