const assert=require('node:assert/strict'),C=require('./blocks-core.js');let count=0;function test(n,f){f();count++;console.log('PASS',n);}
test('each bag contains all seven pieces',()=>{const b=new C.Bag(777);for(let n=0;n<50;n++){const batch=Array.from({length:7},()=>b.next());assert.equal(new Set(batch).size,7);}});
test('independent identical seeded sequences despite different play speeds',()=>{const a=new C.Bag(11),b=new C.Bag(11),seq=Array.from({length:200},()=>a.next());assert.deepEqual(Array.from({length:200},()=>b.next()),seq);});
test('initial obstacles exactly 0 through 10 rows, never full',()=>{for(let n=0;n<=10;n++){const g=C.garbage(n,40);assert.equal(g.filter(r=>r.some(Boolean)).length,n);for(const r of g.filter(r=>r.some(Boolean)))assert.equal(r.filter(Boolean).length,9);}});
test('identical initial fields and pieces',()=>{const m=new C.Match({seed:300,rows:10});assert.deepEqual(m.boards[0].grid,m.boards[1].grid);assert.deepEqual(m.boards[0].active,m.boards[1].active);assert.deepEqual(m.boards[0].bag.preview(),m.boards[1].bag.preview());});
test('moving cannot cross wall or occupied cells',()=>{const b=new C.Board();b.active={type:'O',rot:0,x:-1,y:5,id:1};assert.equal(b.action('left'),false);b.grid[6][2]='G';assert.equal(b.action('right'),false);});
test('four rotations restore each tetromino',()=>{for(const t of C.TYPES){let p={type:t,x:3,y:4,rot:0};const g=C.garbage(0,1);for(let i=0;i<4;i++)p=C.rotate(g,p,1);assert.deepEqual(p,{type:t,x:3,y:4,rot:0});}});
test('I wall kick at right boundary and floor',()=>{const g=C.garbage(0,1);const p={type:'I',x:7,y:16,rot:1};assert(C.valid(g,p));const q=C.rotate(g,p,1);assert(q);assert(C.valid(g,q));const r=C.rotate(g,{type:'I',rot:0,x:3,y:18},1);assert(r&&C.valid(g,r));});
test('hold is once per piece and swaps correctly',()=>{const b=new C.Board({seed:3}),t=b.active.type;b.action('hold');assert.equal(b.hold,t);assert.equal(b.action('hold'),false);b.action('hard');assert.equal(b.holdUsed,false);b.action('hold');assert.equal(b.active.type,t);});
test('ghost gives exactly hard-drop landing',()=>{const b=new C.Board({rows:3,seed:2}),q=C.landing(b.grid,b.active);assert(C.valid(b.grid,q));assert(!C.valid(b.grid,{...q,y:q.y+1}));});
test('soft and hard drop score accurately',()=>{const b=new C.Board();assert(b.action('soft'));assert.equal(b.score,1);const dist=C.landing(b.grid,b.active).y-b.active.y;b.action('hard');assert.equal(b.score,1+dist*2);});
function tetris(b){b.grid=C.garbage(0,1);for(let y=16;y<20;y++)for(let x=0;x<10;x++)if(x!==4)b.grid[y][x]='G';b.grid[15][0]='G';b.active={type:'I',rot:1,x:2,y:16,id:++b.serial};b.lock();}
test('four-line clear scoring and animation delay',()=>{const b=new C.Board();tetris(b);assert.equal(b.lines,0);assert.equal(b.clearTime,.18);b.step(.2);assert.equal(b.lines,4);assert.equal(b.score,800);assert.equal(b.grid[19][0],'G');});
test('personal combo and back-to-back bonuses',()=>{const b=new C.Board();tetris(b);b.step(.2);tetris(b);b.step(.2);assert.equal(b.score,2050);});
test('clearing never changes opponent board or score',()=>{const m=new C.Match({mode:'local',seed:7}),other=JSON.stringify(m.boards[1]);tetris(m.boards[0]);m.boards[0].step(.2);assert.equal(JSON.stringify(m.boards[1]),other);});
test('level advances at ten lines',()=>{const b=new C.Board();b.lines=8;tetris(b);b.step(.2);assert.equal(b.level,2);});
test('survival last alive wins',()=>{const m=new C.Match({mode:'local',rule:'survival'});m.boards[1].alive=false;m.step(.01);assert.equal(m.winner,0);});
test('finished match rejects actions and updates',()=>{const m=new C.Match();m.finish(0,'test');const old=JSON.stringify(m.boards);m.action(0,'hard');m.step(.05);assert.equal(JSON.stringify(m.boards),old);});
test('spawn collision and lock above board top out',()=>{const b=new C.Board();b.grid[0].fill('G');b.spawn('O');assert(!b.alive);const a=new C.Board();a.active={type:'T',rot:0,x:3,y:-1};a.lock();assert(!a.alive);});
test('lock delay allows movement, bounded resets',()=>{const b=new C.Board();b.active={type:'O',rot:0,x:3,y:18,id:1};b.step(.4);assert(b.active);b.action('left');assert.equal(b.lockTime,0);b.step(.4);assert(b.active);for(let i=0;i<30;i++)b.action(i%2?'left':'right');assert.equal(b.resets,15);b.step(.5);assert.equal(b.serial,2);});
test('survival speed multiplier applies independently and equally',()=>{const a=new C.Board(),b=new C.Board();a.step(.4,5);b.step(.4,5);assert.deepEqual(a.active,b.active);assert(a.active.y> -1);});
test('AI does visible engine actions, no teleport',()=>{const b=new C.Board(),ai=new C.AI('normal',1);const x=b.active.x;ai.step(b,.1);assert.equal(b.active.x,x);ai.step(b,.1);assert(Math.abs(b.active.x-x)<=1);});
test('all AI levels can place pieces and clear lines',()=>{for(const difficulty of ['easy','normal','hard']){const b=new C.Board({seed:999,difficulty:'easy'}),ai=new C.AI(difficulty,111);let ticks=0;while(b.alive&&b.serial<75&&ticks++<25000){ai.step(b,.05);b.step(.05);b.events.length=0;}assert(b.serial>20,difficulty);assert(b.lines>0,difficulty);console.log('AI',difficulty,'pieces',b.serial,'lines',b.lines);}});
test('AI difficulty does not alter bags or initial conditions',()=>{const a=new C.Match({seed:90,ai:'easy',rows:6}),b=new C.Match({seed:90,ai:'hard',rows:6});assert.deepEqual(a.boards[1].grid,b.boards[1].grid);assert.deepEqual(a.boards[1].bag.preview(),b.boards[1].bag.preview());});
test('engine has no outgoing attacks or cancellation state',()=>{const b=new C.Board();for(const k of ['attack','pendingGarbage','garbageQueue','incoming','cancel'])assert.equal(b[k],undefined);});


test('survival is mandatory even with old score or race options',()=>{for(const rule of ['score','lines','survival']){const m=new C.Match({mode:'local',rule,target:1,duration:.01});m.boards[0].lines=100;m.boards[0].score=99999;m.step(.05);assert.equal(m.phase,'playing');m.boards[0].alive=false;m.step(.05);assert.equal(m.winner,1);}});
test('simultaneous topouts draw regardless of score',()=>{const m=new C.Match({mode:'local'});m.boards[0].score=999;m.boards.forEach(b=>b.alive=false);m.step(.05);assert.equal(m.winner,null);});
test('slower AI respects minimum placement time',()=>{for(const [difficulty,min]of [['easy',1.1],['normal',.85],['hard',.65]]){const b=new C.Board(),ai=new C.AI(difficulty,1);let elapsed=0;while(b.serial===1&&elapsed<12){ai.step(b,.05);b.step(.05);elapsed+=.05;}assert(elapsed>=min,difficulty);}});
test('nine survival matches at three AI speeds and obstacle heights finish',()=>{for(const rows of [0,5,10])for(const difficulty of ['easy','normal','hard']){const m=new C.Match({mode:'local',seed:902,rows,difficulty:'normal'}),ais=[new C.AI(difficulty,4),new C.AI('normal',8)];let ticks=0;while(m.phase==='playing'&&ticks++<18000){ais.forEach((a,i)=>a.step(m.boards[i],.05));m.step(.05);m.boards.forEach(b=>b.events.length=0);}assert.equal(m.phase,'finished');for(const b of m.boards)assert(Number.isFinite(b.score));console.log('SURVIVAL',rows,difficulty,m.elapsed.toFixed(1),'seconds');}});
console.log(count+' Russian Blocks checks passed.');
