const assert=require('node:assert/strict'),{Match}=require('./frost-core.js'),S=require('./frost-stages.js'),A=require('./frost-ai.js'),P=require('./frost-physics.js');let count=0;function test(n,f){try{f();console.log('PASS '+n);count++;}catch(e){console.error('FAIL '+n);throw e;}}const tick=(m,n,inputs)=>{for(let i=0;i<n;i++)m.update(1/120,inputs||[]);};
test('10 bounded layouts, bosses on 5 and 10, ascending platform reachability',()=>{assert.equal(S.stages.length,10);assert(S.stages[4].boss);assert(S.stages[9].boss);for(const s of S.stages){assert(s.enemies.length>=3);const seen=new Set([s.platforms[0]]);for(let i=0;i<10;i++)for(const p of s.platforms)if([...seen].some(q=>q.y>=p.y&&q.y-p.y<=115&&Math.max(p.x,q.x)<=Math.min(p.x+p.w,q.x+q.w)+100))seen.add(p);assert.equal(seen.size,s.platforms.length);}});
test('jump height reaches first ledges; one-way platforms pass from below and land on top',()=>{const b={x:40,y:346,w:16,h:24,vx:0,vy:-425};let min=400;for(let i=0;i<150;i++){P.move(b,1/120,S.stages[0].platforms);min=Math.min(min,b.y);}assert(min<266);assert.equal(b.y,266);assert(b.ground);});
test('every enemy stops both axes at one-third freeze, below threshold still moves',()=>{for(const type of ['slime','runner','jumper','shooter','shield','flyer','heavy']){const m=new Match(),e=A.create(type,300,250);m.time=1;e.lastFreeze=1;e.freeze=e.maxFreeze/3-.01;A.update(e,1/120,m);assert.notEqual(e.x,300,type+' below threshold moves');e.freeze=e.maxFreeze/3;e.vx=80;e.vy=-100;e.timer=0;const pos=[e.x,e.y];for(let i=0;i<100;i++)A.update(e,1/120,m);assert.deepEqual([e.x,e.y],pos,type+' frozen position');assert.equal(e.vx,0);assert.equal(e.vy,0);assert.equal(m.enemyShots.length,0);}});
test('freeze hit stops immediately; heavy threshold is relative to its maximum; thaw resumes motion',()=>{const m=new Match();for(const type of ['slime','heavy']){const e=A.create(type,300,350);m.freeze(e,{power:25,owner:0,vx:e.face*100});assert(e.vx!==0);m.freeze(e,{power:25,owner:0,vx:e.face*100});assert.equal(e.freeze,50);assert.equal(e.vx,0);assert.equal(e.vy,0);const x=e.x;A.update(e,.1,m);assert.equal(e.x,x);m.time+=5;A.update(e,3,m);assert(e.freeze<e.maxFreeze/3);assert.notEqual(e.x,x);}});
test('normal enemies require four separate hits and turn into stationary snowballs',()=>{const m=new Match(),e=m.enemies[0];for(let i=0;i<3;i++)m.freeze(e,{power:25,owner:0,vx:100});assert(e.alive);assert.equal(e.freeze,75);m.freeze(e,{power:25,owner:0,vx:100});assert(!e.alive);assert.equal(m.balls.length,1);assert(!m.balls[0].rolling);});
test('freeze decays after grace period; heavy takes six hits; shields can break',()=>{const m=new Match();m.time=6;const e=A.create('heavy',100,350);e.freeze=75;A.update(e,1,m);assert(e.freeze<75);e.freeze=0;for(let i=0;i<5;i++)m.freeze(e,{power:25,owner:0,vx:100});assert(e.alive);m.freeze(e,{power:25,owner:0,vx:100});assert(!e.alive);const s=A.create('shield',100,350);m.freeze(s,{power:25,owner:0,vx:-s.face*100});assert.equal(s.freeze,0);assert.equal(s.shield,1);m.freeze(s,{power:25,owner:0,vx:s.face*100});assert.equal(s.freeze,25);});
test('kick can launch teammate snowballs, chain eliminates source and multiple enemies',()=>{const m=new Match({mode:'2p',random:()=>1}),p=m.players[1];m.enemies=[A.create('slime',170,350),A.create('runner',205,350)];m.balls=[{x:130,y:346,w:24,h:24,vx:0,vy:0,life:12,rolling:false,owner:0,chain:0,bounces:0,angle:0,type:'slime'}];p.x=105;p.y=346;p.face=1;assert(m.kick(p));tick(m,70);assert(!m.enemies.some(e=>e.alive));assert.equal(m.balls[0].chain,3);assert.equal(m.score,600);assert.equal(m.players[0].lives,3);assert.equal(p.lives,3);});
test('rolling ball bounces walls and breaks on expiry',()=>{const b={x:603,y:346,w:24,h:24,vx:240,vy:0,life:9,rolling:true,bounces:0,angle:0};P.ballStep(b,.02,S.stages[0].platforms);assert(b.vx<0);assert.equal(b.bounces,1);b.life=.01;assert(P.ballStep(b,.02,S.stages[0].platforms));});
test('stationary snowball thaws so missed kicks cannot remove stage enemies',()=>{const m=new Match();m.enemies=[];m.balls=[{x:200,y:346,w:24,h:24,vx:0,vy:0,life:.01,rolling:false,bounces:0,angle:0,type:'slime'}];tick(m,3);assert.equal(m.balls.length,0);assert(m.enemies.some(e=>e.alive));assert.equal(m.phase,'playing');});
test('players cannot hurt each other with shots or snowballs',()=>{const m=new Match({mode:'2p'});m.enemies=[];m.players.forEach(p=>p.inv=0);m.players[1].x=90;tick(m,60,[{fire:true,kick:true},{}]);assert(m.players.every(p=>p.lives===3));});
test('three lives, short defeat, exact two-second respawn grace, human gameover',()=>{const m=new Match({mode:'2p'}),p=m.players[0];p.inv=0;assert(m.hurt(p));assert.equal(p.lives,2);tick(m,91);assert.equal(p.x,p.spawnX);assert(p.inv>1.9);assert(!m.hurt(p));m.players.forEach(p=>{p.lives=0});tick(m,1);assert.equal(m.phase,'gameover');});
test('powerups temporary, shield blocks one, giant next ball only',()=>{const m=new Match(),p=m.players[0];m.pickup(p,{type:'boots'});assert.equal(p.buffs.boots,10);m.pickup(p,{type:'shield'});p.inv=0;assert.equal(m.hurt(p),'shield');assert.equal(p.lives,3);assert(!p.shield);m.pickup(p,{type:'giant'});m.freeze(m.enemies[0],{power:100,owner:0,vx:100});assert.equal(m.balls[0].w,34);assert(!p.giant);tick(m,121);assert(p.buffs.boots<10);});
test('both bosses immune to freezing shots and take rolling snowball damage',()=>{for(const stage of [4,9]){const m=new Match({stage});const hp=m.boss.hp;m.shots=[{x:m.boss.x,y:m.boss.y,w:56,h:48,vx:0,vy:0,life:1,owner:0,power:100}];tick(m,1);assert.equal(m.boss.hp,hp);m.balls=[{x:m.boss.x,y:346,w:24,h:24,vx:1,vy:0,rolling:true,life:9,chain:1,owner:0,bounces:0,angle:0}];tick(m,1);assert.equal(m.boss.hp,hp-1);}});
test('boss replenishes snowball minions and has multiple attack patterns',()=>{const m=new Match({stage:9});m.enemies=[];tick(m,1000);assert(m.enemies.some(e=>e.alive));assert(m.boss.phase>=2);assert(m.enemyShots.length>0);});
test('stage clear only after all required enemies, balls and boss are gone',()=>{const m=new Match({stage:4});m.enemies=[];tick(m,1);assert.equal(m.phase,'playing');m.boss.alive=false;tick(m,1);assert.equal(m.phase,'clear');tick(m,361);assert.equal(m.stage,5);const n=new Match({stage:9});n.enemies=[];n.boss.alive=false;tick(n,362);assert.equal(n.phase,'victory');});
test('ride rolling snowball carries player without damage',()=>{const m=new Match();m.enemies=[];const p=m.players[0];p.x=210;p.y=322;p.vy=0;p.inv=0;m.balls=[{x:205,y:346,w:24,h:24,vx:100,vy:0,rolling:true,life:9,bounces:0,angle:0,chain:1,owner:0}];tick(m,1);assert(p.x>210);assert.equal(p.y,322);assert.equal(p.lives,3);});
test('AI teammate chooses jumps to reach elevated targets',()=>{const m=new Match({teammate:'normal'}),p=m.players[1];p.ground=true;p.platform=m.platforms[0];m.enemies=[A.create('slime',180,270)];assert(A.teammate(p,m).jump);});
test('respawn returns control to both humans and AI, with a nonnegative timer',()=>{const m=new Match({teammate:'normal'});m.players[1].inv=0;m.hurt(m.players[1]);tick(m,100);assert.equal(m.players[1].respawn,0);const x=m.players[1].x;tick(m,60);assert.notEqual(m.players[1].x,x);});
test('all three AI teammate difficulties finish the first stage with normal three-life rules',()=>{for(const difficulty of ['easy','normal','hard']){const m=new Match({teammate:difficulty,difficulty,random:()=>.99});for(let i=0;i<120*120&&m.phase==='playing';i++)m.update(1/120,[A.teammate(m.players[0],m)]);assert.equal(m.phase,'clear');assert(m.players[0].lives>0);}});
console.log(count+' Frost mechanic checks passed.');
for(let stage=0;stage<10;stage++){const m=new Match({stage,mode:'2p',random:()=>.99});m.players.forEach(p=>p.lives=500);for(let i=0;i<120*300&&m.stage===stage&&m.phase==='playing';i++)m.update(1/120,m.players.map(p=>A.teammate(p,m)));console.log('SOAK stage',stage+1,'phase',m.phase,'alive',m.enemies.filter(e=>e.alive).length,'balls',m.balls.length,'boss',m.boss?.hp,'score',m.score);assert.notEqual(m.phase,'playing','AI co-op must navigate and finish stage '+(stage+1));}

