const assert=require('node:assert/strict'),C=require('./flight-core.js'),A=require('./flight-ai.js');
let s=C.initial();assert.equal(s.planes.flat().filter(p=>p===-1).length,16);s=C.roll(s,1);assert.equal(s.turn,1);assert.equal(s.phase,'roll');s=C.roll(C.initial(),6);assert.deepEqual(C.legal(s),[0,1,2,3]);assert.throws(()=>C.roll(s,6));s=C.move(s,2);assert.equal(s.planes[0][2],0);assert.equal(s.turn,0);assert.equal(s.phase,'roll');assert.throws(()=>C.move(s,1));console.log('PASS initialization, fair 6 takeoff/extra roll, no move pass, duplicate roll/move rejected');
for(let color=0;color<4;color++){let s=C.initial();s.turn=color;s.planes[color][0]=5;s=C.roll(s,2);s=C.move(s,0);assert.equal(s.planes[color][0],7);assert.equal(s.turn,(color+1)%4);assert.equal(C.destination(3,1,color).to,8);assert.equal(C.destination(15,1,color).to,28);assert.equal(C.destination(11,1,color).to,28);assert.equal(C.destination(49,3,color).to,52);assert.equal(C.destination(55,2,color).to,57);assert.equal(C.destination(55,5,color).to,54);assert.equal(C.destination(57,6,color),null)}console.log('PASS four routes, +4 color jump, +12 flight and combined jump, private home lane, exact goal and bounce');
s=C.initial();s.planes[0][0]=5;s.planes[1][0]=46;s.planes[1][1]=46;s.planes[2][0]=33;s=C.roll(s,2);s=C.move(s,0);assert.equal(s.last.captured.length,3);assert.equal(s.planes[1][0],-1);assert.equal(s.planes[1][1],-1);assert.equal(s.planes[2][0],-1); // global 7
s=C.initial();s.planes[0][0]=12;s.planes[1][0]=0;s=C.roll(s,1);s=C.move(s,0);assert.equal(s.planes[0][0],13);assert.equal(s.planes[1][0],0); // safe global13
s=C.initial();s.planes[0][0]=15;s.planes[1][0]=15;s=C.roll(s,1);s=C.move(s,0);assert.equal(s.planes[1][0],-1);assert.equal(s.last.to,28); // jump final collision
s=C.initial();s.planes[0]=[57,57,57,55];s=C.move(C.roll(s,2),3);assert.equal(s.winner,0);assert.equal(s.phase,'finished');assert.throws(()=>C.roll(s,6));console.log('PASS multiple stacked opponents hit, safety, jump landing collision and all-four victory');
let calls=0;const fake={getRandomValues(a){a[0]=calls++?5:4294967295}};assert.equal(C.dice(fake),6);assert.equal(calls,2);
let seed=14;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32};let difference=false;for(let k=0;k<300;k++){const t=C.initial();t.planes=Array.from({length:4},()=>Array.from({length:4},()=>Math.floor(random()*58)-1));t.dice=Math.floor(random()*6)+1;t.phase='choose';for(const tier of ['easy','normal','hard']){const i=A.choose(t,tier,random);assert(i===null||C.legal(t).includes(i))}if(A.choose(t,'normal')!==A.choose(t,'hard'))difference=true}assert(difference);s=C.roll(C.initial(),6);s.planes[0][0]=40;assert.notEqual(A.choose(s,'easy',()=>0),0);console.log('PASS dice rejection sampling, three legal AI policies, hard probability scoring changes actual decisions');
for(const tier of ['easy','normal','hard']){let game=C.initial(),rounds=0;while(game.winner===null&&rounds<3000){if(game.phase==='roll')game=C.roll(game,Math.floor(random()*6)+1);else game=C.move(game,A.choose(game,tier,random));rounds++}assert.notEqual(game.winner,null);console.log('PASS complete four-player match',tier,rounds,'winner',game.winner)}

require('./flight-art.js');const art=globalThis.FlightArt;assert.equal(art.route.length,52);assert.equal(new Set(art.route.map(x=>x.join(','))).size,52);for(let i=0;i<52;i++){const [x,y]=art.route[i];assert.deepEqual(art.route[(i+13)%52],[14-y,x])}for(let c=0;c<4;c++)for(let j=0;j<6;j++){const [x,y]=art.homes[c][j];assert.deepEqual(art.homes[(c+1)%4][j],[14-y,x])}console.log('PASS original 52-cell board and four home routes are rotationally symmetric');
